### ISSUE TITLE
feature_request是否可以增加pp.ua的支持

### ISSUE THREAD

**Issue by fredericky123** [luolongfei/freenom#10]
**Is your feature request related to a problem? Please describe.**
是否可以增加pp.ua自动续期的支持
非常感谢！

**Comment by fredericky123** [comment]
哪怕是检测快要到期后就行提醒呢

**Comment by luolongfei** [comment]
pp.ua 是什么？

**Comment by fredericky123** [comment]
> pp.ua 是什么？

另一个免费域名的站点
https://www.daniao.org/13806.html

**Comment by luolongfei** [comment]
这种一般到期前官方会发提醒邮件吧，抱歉，本项目只接受和 freenom 相关的功能请求。

**Comment by fredericky123** [comment]
我的有个11月份到期，好像也没提醒，偶然看见就续期了，现在这种免费域名大概率不自动提醒

**Comment by fredericky123** [comment]
其实之所以关注pp.ua域名是因为cloudflare已经不支持freenom的域名托管，只好选择其他的

**Comment by luolongfei** [comment]
目前cloudflare好像恢复支持freenom了，可以关注一下
