### ISSUE TITLE
希望能支持使用telegram bot推送

### ISSUE THREAD

**Issue by rhjdvsgsgks** [luolongfei/freenom#10]

**Comment by luolongfei** [comment]
后续会考虑追加tg和微信推送

**Comment by mlch911** [comment]
+1

**Comment by jindaxia** [comment]
smtp服务器改成  smtp.qq.com可以通过QQ邮箱发

**Comment by luolongfei** [comment]
@rhjdvsgsgks 感谢你的提交，由于新版改动较大不太容易整合，所以我自己实现了一个版本

**Comment by luolongfei** [comment]
@mlch911 @rhjdvsgsgks 目前已支持telegram bot推送，需要手动在`config.php`中启用，同时如果你不想使用邮件推送，可以将邮件推送方式停用，具体参照文档

**Comment by luolongfei** [comment]
@jindaxia 目前已支持自动判断邮箱类型，简化了配置

**Comment by rhjdvsgsgks** [comment]
感谢

**Comment by rhjdvsgsgks** [comment]
@luolongfei 那把readme.md merge下吧，增加了systemd-timer的配置

**Comment by luolongfei** [comment]
@rhjdvsgsgks systemd-timer和crontab相比并没有什么显著优势，而且还增加配置复杂度，所以暂时不考虑。

**Comment by rhjdvsgsgks** [comment]
@luolongfei systemd现在的Linux一般都自带，与cron相比不仅不用手动安装，还可以很直观的显示运行的状态以及上次输出的结果，最重要的是可以直接设置运行目录而不是像cron一样需要cd过去

**Comment by luolongfei** [comment]
@rhjdvsgsgks cron一般Linux系统也是自带的，文档里提醒安装一遍是为保险，手动安装也就一行命令的事，cron实际上也可以输出上次的执行结果，而运行目录也是一句命令里多几个字符而已。 systemd-timer配置还得似乎还得新建.service配置文件，增加配置复杂度。

**Comment by rhjdvsgsgks** [comment]
希望能加到readme里，让用户自行选择。另外arch上cron需要手动安装，我懒得装所以研究了下systemd-timer😂

**Comment by luolongfei** [comment]
手动安装cron就一行命令。。。而systemd-timer还得新建配置文件。。。这是有多懒😂

**Comment by rhjdvsgsgks** [comment]
我证书续签也用的systemd-timer，所以顺手也为这个写了一个配置
