### ISSUE TITLE
php.run运行报错

### ISSUE THREAD

**Issue by wxfyes** [luolongfei/freenom#102]
**描述问题**
```
PHP Fatal error:  Call to undefined function Luolongfei\Lib\config() in /data/wwwroot/freenom/libs/Log.php on line 35

Fatal error: Call to undefined function Luolongfei\Lib\config() in /data/wwwroot/freenom/libs/Log.php on line 35
```
部署到vps这个错误，请问这是怎么回事啊？

**环境信息**
 - centos7 x64
 - php7.1
 - freenom续期脚本版本 最新版

**额外的备注**
- Add any other context about the problem here.

**Comment by luolongfei** [comment]
应该是环境问题，看起来像是 composer 的 autoload 没有生效，试试先把 PHP 升级到 7.2 以上？或者加我qq593198779，我空了远程看看什么情况，或者等 docker 版本

**Comment by luolongfei** [comment]
你安装了 composer 吗？在项目根目录下，执行 composer update 试试

**Comment by wxfyes** [comment]
php出问题可能是因为vps的问题，换了一台vps没问题，出问题的那台是甲骨文的免费机器，有空再研究下，你有空也用甲骨文机器测试吧，看能不能跑起来！谢谢回复！项目很不错，支持~~-

**Comment by luolongfei** [comment]
@wxfyes 我这边没有甲骨文的免费机器。。要是可以的话你可以考虑分享出来测试，测试完后修改机器密码。

**Comment by luolongfei** [comment]
已支持在 Docker 部署本项目。
