### ISSUE TITLE
请问为何我运行起来之后想再次编辑env配置却找不到

### ISSUE THREAD

**Issue by jaychoubaby** [luolongfei/freenom#104]
**描述问题**

```
我已经成功运行了并且可以收到邮件推送，我想添加一个微信推送，结果却找不到.env配置文件
```

**你做了哪些尝试**

```
百度了一些教程也找不到文件位置
```

**环境信息**

- 系统：  *（例如 debian11 x64）*
- PHP 版本：  *（例如 php8.0）*
- 脚本版本：  *（例如 v0.4.5）*
- 是否 Docker：  *（例如 是）*

**Comment by luolongfei** [comment]
.env 在项目根目录，在默认情况下，这个文件是被隐藏的，执行 ls -a 便能看到这个文件。

**Comment by jaychoubaby** [comment]
> .env 在项目根目录，在默认情况下，这个文件是被隐藏的，执行 ls -a 便能看到这个文件。

确实使用的ls -a命令，但是没有，我重新安装之后出现了

**Comment by luolongfei** [comment]
可能被误删了吧

**Comment by jaychoubaby** [comment]
> 可能被误删了吧

应该不至于，不过重装之后就好了，感谢开发了这么好的工具
