### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by 12123ads** [luolongfei/freenom#104]
**描述问题**
```
只配置多账户的话会提示：
执行出错：检测到你尚未配置 freenom 账户信息，请修改 .env 文件中与账户相关的项，否则程序无法正常运作(Error code: 34520001) [{"file":"\/root\/freenom\/app\/Console\/FreeNom.php","line":353,"function":"getAccounts","class":"Luolongfei\\App\\Console\\FreeNom","type":"->","args":[]},{"file":"\/root\/freenom\/run","line":71,"function":"handle","class":"Luolongfei\\App\\Console\\FreeNom","type":"->","args":[]}]
```

**重现步骤**
```
配置文件只配置多账户，不配置单账户
```

**截图&日志**
执行出错：检测到你尚未配置 freenom 账户信息，请修改 .env 文件中与账户相关的项，否则程序无法正常运作(Error code: 34520001) [{"file":"\/root\/freenom\/app\/Console\/FreeNom.php","line":353,"function":"getAccounts","class":"Luolongfei\\App\\Console\\FreeNom","type":"->","args":[]},{"file":"\/root\/freenom\/run","line":71,"function":"handle","class":"Luolongfei\\App\\Console\\FreeNom","type":"->","args":[]}]
**你做了哪些尝试**
```
配置了单账户之后只续期单账户
```

**环境信息**
 - centos7 x64
 - php7.2
 - freenom续期脚本版本 v0.3

**额外的备注**
- Add any other context about the problem here.

**Comment by luolongfei** [comment]
@12123ads 只配置单账户的情况下是否能执行成功？

**Comment by 12123ads** [comment]
可以


---Original---
From: ***@***.***&gt;
Date: Fri, May 28, 2021 09:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [luolongfei/freenom] bug_report (#104)




 
@12123ads 只配置单账户的情况下是否能执行成功？
 
&mdash;

**Comment by luolongfei** [comment]
你多账户配置项的值的格式是怎样的？现在应该是你配置的格式不正确。

**Comment by luolongfei** [comment]
多个账户和密码的格式必须是“<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>”，注意不要省略“<>”符号。

**Comment by 12123ads** [comment]
可以了，，，，就是账户格式错了
谢谢
