### ISSUE TITLE
拉取源码执行出现如下错误

### ISSUE THREAD

**Issue by lm379** [luolongfei/freenom#109]
**描述问题**
index.php根目录执行 php run报错
[2022-06-26 18:44:42] {"type":64,"message":"require(): Failed opening required '\/www\/wwwroot\/freenom\/resources\/lang\/zh_cn:zh.php' (include_path='.:\/www\/server\/php\/73\/lib\/php')","file":"\/www\/wwwroot\/freenom\/libs\/Lang.php","line":22} 

**你做了哪些尝试**
重新拉取源码，再次执行
```
描述你发现问题后做了哪些尝试，以及尝试结果，方便我快速排除某些问题，提高沟通效率。
仍然报错

**环境信息**

- 系统：  *（例如 ubuntu 20.04 x64）*
- PHP 版本：  *（例如 php7.3）*
- 脚本版本：  *（例如 v0.5）*
- 是否 Docker：  *（例如 否）*

**额外的备注**
腾讯云轻量应用服务器安装宝塔面板
- Add any other context about the problem here.
- 可额外备注比如你的运行环境是否 NAS，是否宝塔面板等信息

**Comment by luolongfei** [comment]
你的 php 版本，环境信息是什么

**Comment by luolongfei** [comment]
另外，.env 中语言部分填的什么

**Comment by lm379** [comment]
> 你的 php 版本，环境信息是什么

php7.3 Ubuntu20.04

**Comment by lm379** [comment]
> > 你的 php 版本，环境信息是什么
> 
> php7.3 Ubuntu20.04

我试了没填env同样的报错

**Comment by luolongfei** [comment]
你填的什么语言配置

**Comment by lm379** [comment]
> 你填的什么语言配置

zh

**Comment by lm379** [comment]
以前在另一台服务器（已过期，一直到服务器5月29号到期都正常运行）上跑过这个脚本，只不过是0.2版本，同样的系统，同样的配置，没有报错，现在转移到这台服务器上就报错了

**Comment by luolongfei** [comment]
你是使用什么用户登录的 vps？是 root 账户吗

**Comment by luolongfei** [comment]
这种环境问题不太好调查，只能一一排除，因为同一个报错可能的原因很多，如果实在找不到原因，还是推荐直接使用 docker。

**Comment by lm379** [comment]
> 你是使用什么用户登录的 vps？是 root 账户吗

是，两台服务器都是，甚至都一样，但只有这台报错了

**Comment by lm379** [comment]
> 这种环境问题不太好调查，只能一一排除，因为同一个报错可能的原因很多，如果实在找不到原因，还是推荐直接使用 docker。

目前用raliway部署成功了

**Comment by luolongfei** [comment]
自己有 vps 的话，最推荐的方式是通过 docker。两台服务器配置一样，也有可能是权限问题，有的 vps 提供商，默认并不是使用 root 账户登录

**Comment by lm379** [comment]
> 自己有 vps 的话，最推荐的方式是通过 docker。两台服务器配置一样，也有可能是权限问题，有的 vps 提供商，默认并不是使用 root 账户登录
这台服务器也用了很久了，早就修改了root登陆

**Comment by lm379** [comment]
> 自己有 vps 的话，最推荐的方式是通过 docker。两台服务器配置一样，也有可能是权限问题，有的 vps 提供商，默认并不是使用 root 账户登录

问题难找我还是关了吧

**Comment by luolongfei** [comment]
早就修改了 root 登录是什么意思？当前是以 root 身份登录的吗？包括执行命令的时候

**Comment by luolongfei** [comment]
> > 自己有 vps 的话，最推荐的方式是通过 docker。两台服务器配置一样，也有可能是权限问题，有的 vps 提供商，默认并不是使用 root 账户登录
> 
> 问题难找我还是关了吧

没关系，依然可以讨论

**Comment by lm379** [comment]
> 早就修改了 root 登录是什么意思？当前是以 root 身份登录的吗？包括执行命令的时候

对的，腾讯云默认不是root，根据官方文档改成了root

**Comment by luolongfei** [comment]
你在 .env 所在目录，执行 chmod -Rf 777 ./
然后再执行任务php run 看看报什么错

**Comment by lm379** [comment]
> 你在 .env 所在目录，执行 chmod -Rf 777 ./ 然后再执行任务php run 看看报什么错

root@VM-8-8-ubuntu:/www/wwwroot/freenom# php run
[2022-06-26 21:16:43] {"type":64,"message":"require(): Failed opening required '\/www\/wwwroot\/freenom\/resources\/lang\/zh_cn:zh.php' (include_path='.:\/www\/server\/php\/73\/lib\/php')","file":"\/www\/wwwroot\/freenom\/libs\/Lang.php","line":22} 
一样的

**Comment by luolongfei** [comment]
把语言配置成 en 呢？我看它去加载名为 /www/wwwroot/freenom/resources/lang/zh_cn:zh.php 的文件，有点奇怪

**Comment by lm379** [comment]
> 把语言配置成 en 呢？我看它去加载名为 /www/wwwroot/freenom/resources/lang/zh_cn:zh.php 的文件，有点奇怪

改en后报错居然一样

**Comment by luolongfei** [comment]
完全一样？还是说加载的文件名变了？

**Comment by lm379** [comment]
> 完全一样？还是说加载的文件名变了？

完全一致，加载文件名未改变，仍然zh.php

**Comment by luolongfei** [comment]
那蛮奇怪的，等我空了调试一下看看能不能重现这种问题

**Comment by lm379** [comment]
> 完全一样？还是说加载的文件名变了？

会不会是我修改过系统语言的问题？但另外的那台我也这样改过

**Comment by luolongfei** [comment]
系统语言应该没影响，这里最可能的还是权限问题或者加载问题

**Comment by luolongfei** [comment]
但是这种问题很难重现，要在特定的环境里才能出现

**Comment by luolongfei** [comment]
你看看你系统里有没有这个文件 /etc/selinux/config

**Comment by luolongfei** [comment]
然后看看文件里这个配置是不是这个值 SELINUX=enforcing

**Comment by lm379** [comment]
> 你看看你系统里有没有这个文件 /etc/selinux/config

没有这个文件
`root@VM-8-8-ubuntu:~# cd /etc/selinux/
root@VM-8-8-ubuntu:/etc/selinux# ls -a
.  ..  semanage.conf
`

**Comment by lm379** [comment]
> 然后看看文件里这个配置是不是这个值 SELINUX=enforcing

需要创建一个吗

**Comment by lm379** [comment]
我试了docker是可以运行的，可能与我php那里有关

**Comment by luolongfei** [comment]
/etc/selinux/semanage.conf 文件里有 SELINUX=enforcing 吗？

**Comment by luolongfei** [comment]
> 我试了docker是可以运行的，可能与我php那里有关

docker 肯定是百分百可以的。

**Comment by lm379** [comment]
> > 我试了docker是可以运行的，可能与我php那里有关
> 
> docker 肯定是百分百可以的。

没有

**Comment by luolongfei** [comment]
你系统的 php 是通过什么方式安装的？

**Comment by lm379** [comment]
> 你系统的 php 是通过什么方式安装的？

宝塔，目录是/www/server/php/




</body>
</html>

**Comment by luolongfei** [comment]
宝塔我记得默认是把 get_env 函数都给禁用了的吧？你其它配置能被正确读取？

**Comment by lm379** [comment]
> 宝塔我记得默认是把 get_env 函数都给禁用了的吧？你其它配置能被正确读取？

禁用函数get_env删了的

**Comment by lm379** [comment]
> 宝塔我记得默认是把 get_env 函数都给禁用了的吧？你其它配置能被正确读取？

好像不是函数禁用的问题，禁用函数全删了照样报错

**Comment by luolongfei** [comment]
试试执行 getenforce 命令返回什么内容？

**Comment by luolongfei** [comment]
或者 sestatus 命令

**Comment by lm379** [comment]
> 试试执行 getenforce 命令返回什么内容？
disabled

**Comment by luolongfei** [comment]
那就不是 selinux 的问题

**Comment by luolongfei** [comment]
如果把代码部署到 /www/server/ 目录下，会不会不一样

**Comment by lm379** [comment]
> 如果把代码部署到 /www/server/ 目录下，会不会不一样

一样的，甚至任何目录报错都一样

**Comment by luolongfei** [comment]
宝塔面板里，新建立的网站是放在哪个目录的？

**Comment by lm379** [comment]
> 宝塔面板里，新建立的网站是放在哪个目录的？

/www/wwwroot
之前就是放在那里的

**Comment by luolongfei** [comment]
进入  宝塔面板后台-网站-设置-网站目录

修改网站设置，网站目录里的防跨站攻击，取消打勾

试试这样设置之后，再去执行

**Comment by lm379** [comment]
> 进入 宝塔面板后台-网站-设置-网站目录
> 
> 修改网站设置，网站目录里的防跨站攻击，取消打勾
> 
> 试试这样设置之后，再去执行

一样的

**Comment by luolongfei** [comment]
那这样，尝试自己手动安装 php，然后使用你自己安装的 php 执行。安装可参考：https://tecadmin.net/how-to-install-php-on-ubuntu-22-04/

**Comment by lm379** [comment]
> 那这样，尝试自己手动安装 php，然后使用你自己安装的 php 执行。安装可参考：https://tecadmin.net/how-to-install-php-on-ubuntu-22-04/

报错一样的

**Comment by luolongfei** [comment]
你手动安装的 php 哪个版本

**Comment by luolongfei** [comment]
你确定是用的手动安装的版本执行的

**Comment by lm379** [comment]
> 你手动安装的 php 哪个版本

7.3，7.4都试过，宝塔安装的已经卸载

**Comment by luolongfei** [comment]
那就奇怪了，如果方便的话，我想直接在你 vps 上做调试，其它环境目前没法重现这种问题。

**Comment by lm379** [comment]
> 那就奇怪了，如果方便的话，我想直接在你 vps 上做调试，其它环境目前没法重现这种问题。

> 我去创建个秘钥，等下发邮件给你

**Comment by lm379** [comment]
> 那就奇怪了，如果方便的话，我想直接在你 vps 上做调试，其它环境目前没法重现这种问题。

给个联系方式，我把ssh相关配置发给你

**Comment by luolongfei** [comment]
可以设置个临时密码，发到邮箱 ff@llfapp.com，我空了看一下，验证完了后提醒你修改密码。

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/176127872-c18c45e2-3dea-4f04-bae1-36a389eb4b4d.png)

破案了。可以将 vps 的密码改回去了，我这边已退出连接。目前看到是因为你系统里单独设置了名为 LANGUAGE 的变量，值为 zh_CN:zh，而由于脚本在加载环境变量的时候为了防止影响系统功能，并没有强制覆盖已设置的系统变量，而字体包的路径是通过环境变量的值拼接而成，从而导致字体包文件路径不正确。

我一会更新一下，改成加载环境变量的时候覆盖已有的变量，目前看来对系统没有影响。

**Comment by luolongfei** [comment]
@lm379 已经更新代码了，拉取最新的代码，就可以了。

另外，目前你自己手动安装的 php 缺少 curl 库，建议重新编译安装或者使用宝塔的。

**Comment by lm379** [comment]
> @lm379 已经更新代码了，拉取最新的代码，就可以了。
> 
> 另外，目前你自己手动安装的 php 缺少 curl 库，建议重新编译安装或者使用宝塔的。

收到，感谢
