### ISSUE TITLE
TX云函数多账号出错

### ISSUE THREAD

**Issue by TT-IPIP** [luolongfei/freenom#109]
MULTIPLE_ACCOUNTS='<账户1>@<密码1>|<账户2>@<密码2>'

没有加 < >
：出错：登录 freenom 失败，请检查账户和密码是否正确

单账号测试没问题

账号密码都是对的

![2021-6-10 17-56-18](https://user-images.githubusercontent.com/31797574/121505209-38bd8300-ca15-11eb-824e-11c5ed80198f.png)

**Comment by luolongfei** [comment]
@TT-IPIP 多账户必须要加“<>”，文档中有强调，这个符号不能省略，否则正则正则无法匹配到账户信息。

**Comment by TT-IPIP** [comment]
> @TT-IPIP多账户必须要“<>”，文档还有，这个符号不能省略，否则就无法匹配到账户信息了。

我看成了不要加 <>

**Comment by luolongfei** [comment]
加上应该就正常了

**Comment by TT-IPIP** [comment]
可以了，谢谢
