### ISSUE TITLE
建议增加自定义邮箱smtp参数功能

### ISSUE THREAD

**Issue by flyisnow** [luolongfei/freenom#11]
首先，非常感谢您的这个项目。
我计划使用个人域名邮箱发送通知邮件，但是项目只支持这3个邮箱类型，gmail登录被拒，其他两个不想验证邮箱。尽管我的域名是托管在gsuit上的，smtp参数和gmail一样，项目仍无法判断出来，最终我把Mail.php当中的代码修改了一点点才可以发送成功。
因此建议增加一点配置，可以自定义smtp服务器参数。

**Comment by luolongfei** [comment]
好主意，安排上了。

**Comment by Mattraks** [comment]
> 好主意，安排上了。

建议增加[IOS Bark](https://github.com/Finb/Bark)

**Comment by luolongfei** [comment]
> > 好主意，安排上了。
> 
> 建议增加[IOS Bark](https://github.com/Finb/Bark)

可以

**Comment by luolongfei** [comment]
@Mattraks 已支持 Bark 送信，可以先拉取源码部署体验。

**Comment by luolongfei** [comment]
已支持自定义邮箱配置。

**Comment by flyisnow** [comment]
非常感谢
