### ISSUE TITLE
容器中非必要是否可以以nobody权限创建文件

### ISSUE THREAD

**Issue by 1-1-2** [luolongfei/freenom#110]
我是在普通用户环境下配置的。在尝试用 Docker 运行服务的过程中，修改 `.env` 文件时提示无权限。
发现配置文件是以 root 权限产生的，是否可以优化为 nobody？是不是会好一些？
意见供大家讨论，并感谢各位贡献者的付出~

**Comment by luolongfei** [comment]
编辑 .env 文件时可以 sudo 方式进行，.env 文件本身只是配置文件，没有任何风险，如果创建 .env 文件的所有者是 nobody，那么意味着任何 linux 用户都可读写 .env 文件（没记错的话），而你的密码和账户都在这个配置文件里面，很明显你并不想让所有 linux 用户都能看到你的密码~对吧？

**Comment by 1-1-2** [comment]
有道理！竟然忽略了密码安全的问题，大意了。
