### ISSUE TITLE
railway部署时出错

### ISSUE THREAD

**Issue by mccrena** [luolongfei/freenom#114]
**描述问题**

点Deploy Now之后过了大概十秒，出现Failed

**重现步骤**

```
我之前已经在railway上部署了huochetou，按步骤操作，就会出现此情况
```

**截图&日志**
![image](https://user-images.githubusercontent.com/95366235/178239020-8c788e00-6774-4dbe-8d27-e7a0bd98c318.png)
![image](https://user-images.githubusercontent.com/95366235/178239060-28bca8bc-2e06-4a2d-9114-bcebc8acd738.png)

**你做了哪些尝试**

```
重新试了几次，仍然不行。没有尝试删掉huochetou，怕另一个出现问题
```

**Comment by luolongfei** [comment]
试试把 Dockerfile 文件的第 16 行前面加个 # 注释掉，然后再部署。

**Comment by luolongfei** [comment]
看日志似乎是这个参数被禁了

**Comment by mccrena** [comment]
> 试试把 Dockerfile 文件的第 16 行前面加个 # 注释掉，然后再部署。

注释掉之后deploy成功，但过了大概几十秒就会crash

以下是build logs
=========================
Using Detected Dockerfile
=========================
Sending build context to Docker daemon  136.3MB
 
Step 1/10 : FROM php:7.4.19-alpine3.13
 
--> 2c5ec24306df
Step 2/10 : LABEL author="mybsdc <mybsdc@gmail.com>"     maintainer="luolongfei <luolongf@gmail.com>"
 
--> Using cache
--> 4af9423a54bd
Step 3/10 : ENV TZ Asia/Shanghai
 
--> Using cache
--> f4563b734dfb
Step 4/10 : WORKDIR /app
 
--> Using cache
--> b11284a5291b
Step 5/10 : COPY . ./
 
--> Using cache
--> cfa8786e1d93
Step 6/10 : RUN set -eux     && apk update     && apk add --no-cache tzdata bash
 
--> Using cache
--> 3566d91794de
Step 7/10 : COPY docker-entrypoint.sh /usr/local/bin/
 
--> Using cache
--> 4aa36f38760d
Step 8/10 : RUN chmod +x /usr/local/bin/docker-entrypoint.sh
 
--> Using cache
--> 44ccd072249f
Step 9/10 : ENTRYPOINT ["docker-entrypoint.sh"]
 
--> Using cache
--> 9c75fe24c468
Step 10/10 : CMD ["crond", "-f"]
 
--> Using cache
 
--> c55d2fd8461a
 
One or more build-args [WECHAT_AGENT_ID MAIL_USERNAME MULTIPLE_ACCOUNTS RAILWAY_DEPLOYMENT_ID RAILWAY_SERVICE_ID RAILWAY_STATIC_URL RAILWAY_GIT_REPO_NAME RAILWAY_GIT_REPO_OWNER VERIFY_SSL WECHAT_CORP_ID TO MAIL_ENCRYPTION RAILWAY_GIT_COMMIT_SHA RAILWAY_PROJECT_ID RAILWAY_SNAPSHOT_ID TELEGRAM_BOT_TOKEN MAIL_ENABLE NEW_VERSION_DETECTION SHOW_SERVER_INFO BARK_ENABLE BARK_ICON BARK_LEVEL FREENOM_PASSWORD FREENOM_PROXY WECHAT_CORP_SECRET BARK_SOUND ENV_FILE_VERSION MAIL_HOST WECHAT_ENABLE RAILWAY_GIT_BRANCH RAILWAY_GIT_COMMIT_MESSAGE BARK_IS_ARCHIVE BARK_JUMP_URL BARK_KEY BARK_URL RAILWAY_ENVIRONMENT_ID SCT_ENABLE SCT_SEND_KEY CUSTOM_LANGUAGE CUSTOM_TELEGRAM_HOST DEBUG MAIL_PORT RAILWAY_GIT_AUTHOR TELEGRAM_BOT_ENABLE TELEGRAM_CHAT_ID TELEGRAM_PROXY BARK_GROUP FREENOM_USERNAME MAIL_PASSWORD NOTICE_FREQ RAILWAY_ENVIRONMENT] were not consumed
 
Successfully built c55d2fd8461a
 
Successfully tagged us-west1-docker.pkg.dev/railway-infra/railway-docker-users/project/11743dc7-6365-45e5-a2e9-b154023255f8/service/0e58073c-475c-46b4-ab79-25340aa7197c:cb08bd7b-9dae-4e3b-b106-973baa10c22e
 
Build time: 1.28 seconds
================
Publishing Image
================
The push refers to repository [us-west1-docker.pkg.dev/railway-infra/railway-docker-users/project/11743dc7-6365-45e5-a2e9-b154023255f8/service/0e58073c-475c-46b4-ab79-25340aa7197c]
Preparing  30996c021402
Preparing  9e76b5d8af98
Preparing  f1f4f05f44dc
Preparing  09d300f1fbae
Waiting  30996c021402
Waiting  9e76b5d8af98
Preparing  2bac65906d53
Preparing  76340f9d7a43
Waiting  f1f4f05f44dc
Waiting  09d300f1fbae
Preparing  f66c290df141

![image](https://user-images.githubusercontent.com/95366235/178319351-746c3899-0767-4c77-954b-51360819b763.png)

**Comment by luolongfei** [comment]
了解，我抽空看看

**Comment by luolongfei** [comment]
@mccrena 我没法复现，因为我的 railway 账户又被封了，同一个 ip 只要有一个账户被封了，关联的所有账户都会被封，它们的风控实在变态。

**Comment by luolongfei** [comment]
你部署的 huochetou，Dockerfile 中 VOLUME 字段对应的是什么？是否跟 freenom 的有冲突 ["/conf", "/app/logs"]

**Comment by mccrena** [comment]
![image](https://user-images.githubusercontent.com/95366235/178395144-67f9c118-a466-4fc2-82d5-39fa6eb780ee.png)
![image](https://user-images.githubusercontent.com/95366235/178395178-89b95e63-88fb-44fd-b040-95cb0f828fe3.png)
github仓库里只有这一个文件，好像并没有看到volume字段

> 你部署的 huochetou，Dockerfile 中 VOLUME 字段对应的是什么？是否跟 freenom 的有冲突 ["/conf", "/app/logs"]

**Comment by luolongfei** [comment]
噢那应该没冲突
方便远程吗

**Comment by luolongfei** [comment]
我这边没有 railway 没法排错

**Comment by mccrena** [comment]
方便，什么方式远程

**Comment by luolongfei** [comment]
teamviewer

**Comment by luolongfei** [comment]
可以把连接信息发到这个邮箱   ff@llfapp.com

**Comment by luolongfei** [comment]
你把送信邮箱配置正确，看看呢

**Comment by mccrena** [comment]
应该是我配置有问题，我试着改改，感谢您的帮助

**Comment by luolongfei** [comment]
目前看起来应该是 Dockerfile 中的 Volume 关键字被 railway 禁用了。我想想怎么修改。你试试把所有配置改正确，看能不能成功执行续期，如果能成功的话，接下来的版本我会把 Volume 关键字移除。

**Comment by mccrena** [comment]
![image](https://user-images.githubusercontent.com/95366235/178399571-4c8a2379-37c5-4e79-b075-16e86f032b3c.png)
![image](https://user-images.githubusercontent.com/95366235/178399615-5c97373d-6404-4933-b856-afce8a455d62.png)
已经把variables配置为只有帐号密码，而且亲自登出登录试了一下，是正确的，depoly log里还是提示出错

**Comment by luolongfei** [comment]
这个错误是因为检测了是否有 .env 文件，实际上这种环境是不用检测的，再来远程一下？

**Comment by luolongfei** [comment]
因为把挂载 .env 相关的代码删除了，所以程序检测到没有 .env 文件

**Comment by mccrena** [comment]
可以

**Comment by luolongfei** [comment]
现在能成功执行到续期那一步了吗？

**Comment by mccrena** [comment]
执行成功，今次没有需要续期的域名。
可以了

> 现在能成功执行到续期那一步了吗？

**Comment by luolongfei** [comment]
ok，那问题定位没问题

**Comment by luolongfei** [comment]
我刚刚更新了代码，可以试试 fork 最新代码是否能执行成功。新代码里已不再指定数据卷关键字。

**Comment by mccrena** [comment]
执行成功

**Comment by luolongfei** [comment]
ok!

**Comment by leohxj** [comment]
> 

相当变态, 而且也不回复邮件.

我切到 Render.com 部署了
