### ISSUE TITLE
关于Freenom账户

### ISSUE THREAD

**Issue by mcxiaolan** [luolongfei/freenom#117]
希望添加谷歌登录账户续期，我很多域名都在使用谷歌登录的账户上，而不是在其他邮箱。
而且在使用多账户时，可以弄一个邮件合并，而不是每一个账户分别发一个邮件。

**Comment by luolongfei** [comment]
1、通过谷歌账户登录的，可以在 freenom 资料画面绑定邮箱，然后就可以使用邮箱登录了。第三方账户登录流程经常变动，暂时不考虑。
2、合并邮件的功能将在下一个版本实现。

**Comment by immochan** [comment]
你好请问freenom怎么绑定邮箱，我是用谷歌账号登录的

**Comment by immochan** [comment]
噢已经成功了，打扰了

**Comment by luolongfei** [comment]
@immochan 资料编辑画面可以修改。

**Comment by luolongfei** [comment]
@immochan 没事

**Comment by immochan** [comment]
应该更新一下，是通过谷歌账户登录，然后退出登录后，选择重置密码，此时设置新的密码，就可以使用谷歌邮箱+新的密码直接登录

**Comment by luolongfei** [comment]
@immochan 这个页面不能修改吗？https://my.freenom.com/clientarea.php?action=details

**Comment by immochan** [comment]
> @immochan这个页面不能修改吗？https://my.freenom.com/clientarea.php?action=details

个人资料界面可以修改的，但是不知道修改后登录密码是多少，我是直接重置的，这样也能使用

**Comment by luolongfei** [comment]
@immochan 是通过忘记密码来修改的，参考这里：https://github.com/luolongfei/freenom/issues/24#issuecomment-672413792
