### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by 97668589** [luolongfei/freenom#118]
TG机器人, [2022/7/15 15:30]
主人，出错了，登录 freenom 出错。错误信息：cURL error 28: Failed to connect to my.freenom.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.freenom.com/dologin.php(Error code: 34520002)

具体是在/home/runner/work/freenom/freenom/app/Console/FreeNom.php文件的第131行，抛出了一个异常。异常的内容是登录 freenom 出错。错误信息：cURL error 28: Failed to connect to my.freenom.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.freenom.com/dologin.php(Error code: 34520002)，快去看看吧。（账户：）

**Comment by luolongfei** [comment]
请按模板提问。
