### ISSUE TITLE
出错：SMTP 错误：无法连接到 SMTP 主机。

### ISSUE THREAD

**Issue by sean908** [luolongfei/freenom#119]
**描述问题**
```
按照手册中docker配置说明配置后, 启动容器后报标题内容的错误
使用谷歌邮箱作为发件邮箱
```

**重现步骤**
```
略
```

**截图&日志**

**你做了哪些尝试**
```
确认了谷歌邮箱按照文档中邮箱配置部分配置
```

**环境信息**
 - arm架构软路由
 - docker version 19.03.12
 - freenom续期脚本版本 当前最新版v0.3

**额外的备注**
我看也有人有同样的问题, 作者回复是目前谷歌可能支持不太好.
建议使用qq或者163吗?

**Comment by luolongfei** [comment]
并不是对谷歌支持不太好，而是因为 gmail 的安全性要求更高，默认会验证客户端的 ip，首次在新 ip 登录 gmail，会被谷歌服务器拒绝。如果你的软路由每次登录 gmail 时的 ip 地址都不一样，则每次都会被谷歌服务器拒绝。

因此，如果你一定要用 gmail 作为发信邮箱，请确保你有一个固定的 ip，且首次登录失败后，需要做以下操作：

1、前往此页面开启允许不安全的访问：
https://myaccount.google.com/u/0/lesssecureapps?pli=1&pageId=none 
（注意，如果你在同一个浏览器登录过多个 gmail 账户，则 /u/ 后面的数字可能不为 0）
2、前往此地址允许访问： https://accounts.google.com/b/0/DisplayUnlockCaptcha

你此处没贴更详细的日志，“无法连接到 SMTP 主机”的话，也可能是没有可访问外网的环境。你可以先确定你的软路由是否可以访问谷歌服务。

**Comment by sean908** [comment]
> 并不是对谷歌支持不太好，而是因为 gmail 的安全性要求更高，默认会验证客户端的 ip，首次在新 ip 登录 gmail，会被谷歌服务器拒绝。如果你的软路由每次登录 gmail 时的 ip 地址都不一样，则每次都会被谷歌服务器拒绝。
> 
> 因此，如果你一定要用 gmail 作为发信邮箱，请确保你有一个固定的 ip，且首次登录失败后，需要做以下操作：
> 
> 1、前往此页面开启允许不安全的访问：
> https://myaccount.google.com/u/0/lesssecureapps?pli=1&pageId=none
> （注意，如果你在同一个浏览器登录过多个 gmail 账户，则 /u/ 后面的数字可能不为 0）
> 2、前往此地址允许访问： https://accounts.google.com/b/0/DisplayUnlockCaptcha
> 
> 你此处没贴更详细的日志，“无法连接到 SMTP 主机”的话，也可能是没有可访问外网的环境。你可以先确定你的软路由是否可以访问谷歌服务。

明白.
先把邮件通知停掉了, 真正需要时再来调试
