### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by jiangbeth** [luolongfei/freenom#12]
请教一下，安装了青龙面板。是不是影响这个呢、

**Comment by luolongfei** [comment]
网络问题或者DNS解析问题。目前 v0.4.3 已发布，建议升级到最新版，最新版支持使用代理登录 freenom 账户。

**Comment by jiangbeth** [comment]
如何升级到新版啊

**Comment by luolongfei** [comment]
你是怎么部署的？https://github.com/luolongfei/freenom 里面的代码就是最新版本。

**Comment by jiangbeth** [comment]
方式一：通过 Docker 部署（推荐，最简单的部署方式）
按这个部署的，。

**Comment by luolongfei** [comment]
在.env所在目录，执行docker rm -f freenom删除现有容器，然后再执行docker rmi -f luolongfei/freenom删除旧的镜像，然后再执行上面的docker run -d --name freenom --restart always -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom重新部署即可，这样部署后就是最新的代码了。当然，新版对应的.env文件可能有变动，不必担心，程序会自动更新.env文件内容，并将已有的配置迁移过去。
@jiangbeth

**Comment by luolongfei** [comment]
> 请教一下，安装了青龙面板。是不是影响这个呢、

应该没影响吧，青龙面板会修改网络配置吗？
