### ISSUE TITLE
docker方式下计划任务未生效?

### ISSUE THREAD

**Issue by sean908** [luolongfei/freenom#121]
**描述问题**
```
使用docker方式运行程序, 发现日志中启动时输出了计划执行时间, 但是后续查看日志并无计划执行信息
```

**重现步骤**
```
见下方附图
14号重启的应用, 15号未曾输出执行日志
```

**截图&日志**

**你做了哪些尝试**
```
无
```

**环境信息**
 - arm架构 openwrt
 - freenom续期脚本版本 v0.3

**额外的备注**
无

**Comment by luolongfei** [comment]
刚刚测试了一番，一切正常。我认为可能是你看日志的方式不对。你是直接执行 docker logs freenom 查看日志的？

注意直接执行 docker logs freenom 只能看到最近一次重启 freenom 容器产生的日志，而看不到最新计划任务执行日志，要看最新的计划任务日志：

请 cd 到 .env 文件所在目录，然后 cat logs/freenom_cron.log，这样可以看到最近一次计划任务产生的日志，或者你可以打开logs目录下，按日期查找 15 日的日志，两种方式都可以。

**Comment by sean908** [comment]
> 刚刚测试了一番，一切正常。我认为可能是你看日志的方式不对。你是直接执行 docker logs freenom 查看日志的？
> 
> 注意直接执行 docker logs freenom 只能看到最近一次重启 freenom 容器产生的日志，而看不到最新计划任务执行日志，要看最新的计划任务日志：
> 
> 请 cd 到 .env 文件所在目录，然后 cat logs/freenom_cron.log，这样可以看到最近一次计划任务产生的日志，或者你可以打开logs目录下，按日期查找 15 日的日志，两种方式都可以。

```
root@OpenWrt:~# cat logs/freenom_cron.log 
[2021-07-16 13:39:00] 当前程序版本 v0.3 
[2021-07-16 13:39:05] 由于没有启用邮件功能，故本次不通过邮件送信。 
[2021-07-16 13:39:05] 由于没有启用 Telegram Bot 功能，故本次不通过 Telegram Bot 送信。 
[2021-07-16 13:39:05] qq.com：执行成功，今次没有需要续期的域名 
```

那应该是执行了?
先前的截图是从docker的web管理页查看的日志信息.

**Comment by luolongfei** [comment]
正确执行了的，不必担心。你图形化界面看的日志是容器首次运行或者重启产生的，应该等同于在命令行执行 docker logs freenom 看到的日志。
