### ISSUE TITLE
多账户怎样配置?

### ISSUE THREAD

**Issue by WJHXD1B** [luolongfei/freenom#122]
我在多账户配置中已经填入了我第二个账号  用,隔离
但是不起作用 请问各位大佬怎样解决

**Comment by luolongfei** [comment]
MULTIPLE_ACCOUNTS='<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>'

**Comment by WJHXD1B** [comment]
> MULTIPLE_ACCOUNTS='<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>'

好的谢谢
