### ISSUE TITLE
登录 freenom 出错

### ISSUE THREAD

**Issue by hermanb001** [luolongfei/freenom#125]
**描述问题**

```
Openwrt的容器自动每天运行，以前一直正常，最近一个多星期一直提示登录出错
```

**截图&日志**
![image](https://user-images.githubusercontent.com/94038133/180102310-7f7e05a8-a206-4d07-8ba7-cd0605996a36.png)

**你做了哪些尝试**

重新提交env文件，无法修复

**Comment by luolongfei** [comment]
.env 文件中的 VERIFY_SSL 变量的值是否设置的是 0？

**Comment by DullJZ** [comment]
同样出现此问题，通过设置VERIFY_SSL为0解决

**Comment by hermanb001** [comment]
多谢大佬！

**Comment by lautokwah** [comment]
> .env 文件中的 VERIFY_SSL 变量的值是否设置的是 0？

同样出现此问题，而且 VERIFY_SSL 变量的值使用的是默认值 0。

**Comment by luolongfei** [comment]
> > .env 文件中的 VERIFY_SSL 变量的值是否设置的是 0？
> 
> 同样出现此问题，而且 VERIFY_SSL 变量的值使用的是默认值 0。

什么环境

**Comment by hermanb001** [comment]
昨天恢复，今天又不行了

![image](https://user-images.githubusercontent.com/94038133/180325182-724095f8-07ae-4728-aa1e-aa4b97b50bed.png)

![image](https://user-images.githubusercontent.com/94038133/180325290-34fcbb4c-54d0-43c8-ab92-2673ad68988a.png)

**Comment by luolongfei** [comment]
> 昨天恢复，今天又不行了
> 
> ![image](https://user-images.githubusercontent.com/94038133/180325182-724095f8-07ae-4728-aa1e-aa4b97b50bed.png)
> 
> ![image](https://user-images.githubusercontent.com/94038133/180325290-34fcbb4c-54d0-43c8-ab92-2673ad68988a.png)

你在命令行直接用 curl 访问同样的域名以及其它域名，看看报什么错

**Comment by hermanb001** [comment]
> > 昨天恢复，今天又不行了
> > ![image](https://user-images.githubusercontent.com/94038133/180325182-724095f8-07ae-4728-aa1e-aa4b97b50bed.png)
> > ![image](https://user-images.githubusercontent.com/94038133/180325290-34fcbb4c-54d0-43c8-ab92-2673ad68988a.png)
> 
> 你在命令行直接用 curl 访问同样的域名以及其它域名，看看报什么错

![image](https://user-images.githubusercontent.com/94038133/180435068-aec2c99b-f7c9-4690-a9a4-a365f006aad5.png)
无法连接

**Comment by luolongfei** [comment]
curl 访问其它域名呢，比如百度之类的

**Comment by luolongfei** [comment]
一般情况下，curl error 35 通常是由于 cURL 和 SSL 的版本不匹配、cURL 包过时、与 php 版本不匹配、防火墙限制等原因造成的，先试试把 curl 和 open ssl 包都更新到最新

**Comment by luolongfei** [comment]
你的 php 版本又是多少？

**Comment by hermanb001** [comment]
> curl 访问其它域名呢，比如百度之类的

![image](https://user-images.githubusercontent.com/94038133/180583585-3bd82fab-359a-4d41-bb22-b994db2b69b6.png)

CURL google 完全正常

**Comment by hermanb001** [comment]
> 一般情况下，curl error 35 通常是由于 cURL 和 SSL 的版本不匹配、cURL 包过时、与 php 版本不匹配、防火墙限制等原因造成的，先试试把 curl 和 open ssl 包都更新到最新

用的是esir的2022春季版openwrt里面的docker，不肯定curl, pho和ssl版本

**Comment by luolongfei** [comment]
我手边并没有装了 openwrt 的机器，你有尝试重启 docker（非容器） 吗？

**Comment by luolongfei** [comment]
这个 openwrt 里的 docker 是通过命令行进入还是通过画面操作？

**Comment by luolongfei** [comment]
如果是通过命令行，我们可以进去容器里测测情况

**Comment by sean908** [comment]
> 如果是通过命令行，我们可以进去容器里测测情况

我也有类似问题, 配置文件里 SSL检测 确认过是 0
docker可以进命令行, 有需要我来配合排查

**Comment by luolongfei** [comment]
> > 如果是通过命令行，我们可以进去容器里测测情况
> 
> 我也有类似问题, 配置文件里 SSL检测 确认过是 0 docker可以进命令行, 有需要我来配合排查
 
按模版提问
