### ISSUE TITLE
续费失败

### ISSUE THREAD

**Issue by superen7527** [luolongfei/freenom#126]
续期请求出错：cURL error 28: Operation timed out after 33001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.freenom.com/domains.php?submitrenewals=true

freenom广电网络进去太慢了 自己续费一个小时加魔法上网都没弄好 切网络还掉登录。。还以为域名不能续费了，就删了。删完才知道没有问题，记混了，是一个期限(14天内)就可以续费，我记成一个期限内就不能续费了以为不能续才报错就删了 好难受。哭哭。

用的railway 作者可以看看是不是bug，上面废话无视即可，我就报个bug，可以关闭issue

**Comment by luolongfei** [comment]
国内的网络直连网络质量肯定不佳。你上面的报错是网络超时，可能是网络问题，也可能是 freenom 的服务器没有响应，不用理会，观察下次执行是否正常。你是指定了脚本的执行时间吗？

**Comment by superen7527** [comment]
没有指定cron是默认的刚部署就放推送了。
直连不行，翻也不行，还是用的原生IP...
报错的地方，不应该是railway的网络吗 应该不在国内才对。

不过freenom服务器确实不稳定，既然是网络因素就不管了，关键是我之前记错了以为是超过限制时间无法续费就没当作是报错以为是账号问题，域名已经删除重新获取了一年，所以没办法测试，抱歉哈。


还有个问题，配置的企业微信，超过十几个域名以后，显示不全，可以考虑分批推送，而且排版没有邮箱那种好看的话，可以一行一个域名。看微信的样子，应该是\<a href=...>标签都算字数。

**Comment by luolongfei** [comment]
那可能是 freenom 的服务器问题。现在已经不能重现这个问题了吧？这个跟你到期时间没关系，程序是每天都会登录检查域名状态的，只要没报错就没问题。

企业微信的字数限制太低了，显示不全是已知问题，一直还没时间改，由于要生成含有超链接的文本，要分割起来相当繁琐，需要正好不把 a 标签对分割开，否则 a 标签就无法正确展示。如果不搞标签的话，要分批推送是分分钟的事情。这个会在后续的版本中修正，目前还没时间搞。

**Comment by luolongfei** [comment]
而且微信很坑的是，它限制是根据字节来的，不是字符，所以处理的时候还要考虑一个字符是几个字节等问题。

**Comment by superen7527** [comment]
嗯是的后来发现是和程序没关系，要是没心急等今天说不定就能看到续费成功了。

微信这个确实，我这边就被分开看到标签才知道算进去的，也就是放超链接看着字数还行实际上字数多了不止一倍了。


有2个建议：

1.域名超链接href其实没必要，有一些域名不是绑定网站跳转也没有意义。或者想就是跳转可以直接加上http前缀，让微信自己正则识别成超链接标签占字数问题就没了(记得域名也可以显示超链接刚刚就去试了一下，确实完全不需要http，而且多个域名被分开也都还是超链接，目前和你的显示效果是一样的。如果是text类型应该和企业微信客户端一样，其他显示不好说，所以完全可以不用href正常来发送)

2.不需要标签实际上字数应该够了，不过也可以再分批一下，这个字数也不是微信发消息限制的字数是企业微信那边字数还是太少了。考虑到域名都不会太长但是也不乏又多又长域名所有者，还是固定一条几个域名比较好，大概假设最长域名为几个字符计算一下，或者干脆就十个二十个域名一组。同时微信表现形式不那么美观可以一行一个显示，为了整齐可以把过期时间放前面，这样域名长短不一也无所谓，左端根据过期时间排序应该会像一个斜线对齐。

相信按你说的不考虑标签是分分钟的事情我就不多说了这些你应该都有想法。

**Comment by luolongfei** [comment]
如果是自动分批次的话，那么电报和邮件等送信方式都应该要做对应，其它端一样需要考虑标签事宜。其实没关系的，带标签也可以实现，只是写起来麻烦些，等有时间的时候加上就可以了。

**Comment by superen7527** [comment]
不需要吧 只改微信不就好了吗 也就微信有字数限制吧。分批可以不考虑别的啊 如果能全显示我倒是喜欢一次性发送(不过换行看着清爽一点一行一个)可惜微信有限制。你是全部用同一个模板吗 😂..嗯算了 你有想法就按你的来😂😂我只是提个意见

**Comment by luolongfei** [comment]
任何推送服务都有字数限制，每个服务的大概逻辑是差不多的。

**Comment by superen7527** [comment]
你好请问一下为什么推荐使用railway？使用十几天以后发邮件说停止部署。看官网说超过上限已经删除部署。

> You have used all your available resources this month. Deployments have been removed and can be re-deployed next month. Upgrade now to re-enable deploys.

那么这么快就用完的免费额度还被推荐 是因为哪里可以申请还是因为部署简单。我不太了解这些服务，希望解答一下 感谢

**Comment by luolongfei** [comment]
@superen7527 现在限制变严格了吗？请新开一个 issue 讨论，不要在别的主题下讨论。
