### ISSUE TITLE
使用Docker一键更新命令更新失败

### ISSUE THREAD

**Issue by CodeFishK** [luolongfei/freenom#128]
**描述问题**

```
使用Docker一键更新命令至最新版运行后仍提示“你当前正在使用的版本为 v0.4.4”
```

**重现步骤**

```
docker rm -f freenom && docker rmi -f luolongfei/freenom && docker run -d --name freenom --restart always -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom
```

**截图&日志**
![image](https://user-images.githubusercontent.com/38446347/182743853-5210d55d-f4b1-4b91-a630-4e30fc78b006.png)
![image](https://user-images.githubusercontent.com/38446347/182744223-c887b59f-9852-4074-8268-f7e3906b61ed.png)

**你做了哪些尝试**

```
Docker的镜像tag应该已经是latest，想尝试手动更新.env到最新版，但是在项目仓库里没找到.env配置，故打算手动删除容器重新创建
```

**环境信息**

- 系统：  CentOS 7.9 x86_64
- PHP 版本：  5.6.40
- 脚本版本：   v0.5
- 是否 Docker：  是

**额外的备注**

宝塔面板

**Comment by luolongfei** [comment]
你是不是配置了 docker 镜像？从镜像地址拉取的，不是直接从 docker hub 上拉取？

**Comment by luolongfei** [comment]
docker hub 上的才是最新版本，至于镜像地址，应该是镜像地址里的内容没有同步更新。

**Comment by CodeFishK** [comment]
我看下了宝塔的Docker设置，有以下镜像加速设置，我清空再更新试试。
```
https://0b27f0a81a00f3560fbdc00ddd2f99e0.mirror.swr.myhuaweicloud.com,https://ypzju6vq.mirror.aliyuncs.com,https://registry.docker-cn.com,http://hub-mirror.c.163.com,https://docker.mirrors.ustc.edu.cn
````

**Comment by luolongfei** [comment]
可以试试不通过镜像

**Comment by CodeFishK** [comment]
刚刚试了清空镜像加速重新创建就没有更新提示了，但是我cat .env看配置文件版本是“2.4”，不是仓库里.env.example的版本“2.5”，这是正常现象嘛？
![image](https://user-images.githubusercontent.com/38446347/182752154-49ffe329-7646-4417-9961-57e44ca652bb.png)

**Comment by luolongfei** [comment]
你启动容器，执行一遍会自动更新 .env 文件内容

**Comment by CodeFishK** [comment]
我docker restart freenom后cat .env以旧为“2.4”
![image](https://user-images.githubusercontent.com/38446347/182755610-cb5c6e1b-9f41-458f-9e28-1ab4e0cb8243.png)

**Comment by luolongfei** [comment]
看看运行日志输出的是什么

**Comment by CodeFishK** [comment]
运行输出日志已是0.5版本
![image](https://user-images.githubusercontent.com/38446347/182771359-7c633c8a-416e-4f72-b5ce-08877782c85b.png)

**Comment by luolongfei** [comment]
噢正常的，仓库里是最新版本，目前还没正式发布，容器里是稳定版本。所以是没问题的。

**Comment by CodeFishK** [comment]
好的，那我就关闭了
