### ISSUE TITLE
建议支持自部署的Server 酱

### ISSUE THREAD

**Issue by BugKun** [luolongfei/freenom#13]
建议支持自部署的Server 酱
Server 酱的配置支持自定义URL

**Comment by luolongfei** [comment]
server 酱开源了吗？如何自部署？

**Comment by BugKun** [comment]
https://github.com/easychen/wecomchan

**Comment by luolongfei** [comment]
> https://github.com/easychen/wecomchan

这个项目也是通过 企业微信 推送。

本项目已经实现通过 企业微信 推送，所以没必要再冠名为 server 酱，直接用本项目的 企业微信 渠道推送即可。
