### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by masterlinnn** [luolongfei/freenom#130]
**描述问题**
```
出错：
cURL error 6: Could not resolve host: my.freenom.com
请问如何解决
```

**重现步骤**
```
步骤一
```

**截图&日志**

**你做了哪些尝试**
```
描述你发现问题后做了哪些尝试，方便我快速排除某些问题，提高沟通效率。
```

**环境信息**
 - centos7 x64
 - php7.2
 - freenom续期脚本版本 v0.2.2

**额外的备注**
- Add any other context about the problem here.

**Comment by luolongfei** [comment]
看上去是 DNS 解析问题，更换本地的 DNS 解析服务器即可。

**Comment by masterlinnn** [comment]
> 看上去是 DNS 解析问题，更换本地的 DNS 解析服务器即可。

重启虚拟机解决，谢谢。
