### ISSUE TITLE
已开启tg推送没有调用

### ISSUE THREAD

**Issue by lq-259** [luolongfei/freenom#131]
.env：
![403acd12b1c3964d](https://user-images.githubusercontent.com/60541200/131257316-2afbd119-084e-4189-957f-ae7542dfbb46.jpg)
开启前后：
![-60f3db0d85d6285](https://user-images.githubusercontent.com/60541200/131257323-00612483-76ff-4a77-98bd-42522531a267.jpg)

**Comment by luolongfei** [comment]
你的 vps 是否在国外？配置看上去没问题，可以开启 debug 模式并提供更多相关日志，只看截图看不出问题。

**Comment by luolongfei** [comment]
另外也不排除你申请的 token 或者 chatid 存在问题。需要逐一排查。

**Comment by lq-259** [comment]
debug：
root@localhost:~/freenom# php run
[2021-08-30 11:47:30] 当前程序版本 v0.3
*   Trying 63.33.210.48...
* TCP_NODELAY set
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=my.freenom.com
*  start date: Apr 29 00:00:00 2021 GMT
*  expire date: Apr 29 23:59:59 2022 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> POST /dologin.php HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Referer: https://my.freenom.com/clientarea.php
Content-Length: 67

* upload completely sent off: 67 out of 67 bytes
< HTTP/1.1 302 Found
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 03:47:33 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Location: clientarea.php
< Pragma: no-cache
< Set-Cookie: WHMCSZH5eHTGhfvzP=u53f36p96rs4el3d8s9ruki4r2; path=/; HttpOnly
< Set-Cookie: WHMCSZH5eHTGhfvzP=4n248vb87cq4s18rj18e46qun7; path=/; HttpOnly
< Set-Cookie: WHMCSUser=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
<
* Connection #0 to host my.freenom.com left intact
* Found bundle for host my.freenom.com: 0x61e6b9da50 [can pipeline]
* Re-using existing connection! (#0) with host my.freenom.com
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
> GET /clientarea.php HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Cookie: WHMCSZH5eHTGhfvzP=4n248vb87cq4s18rj18e46qun7

< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 03:47:34 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 3813
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Encoding: gzip
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Vary: Accept-Encoding
<
* Connection #0 to host my.freenom.com left intact
* Found bundle for host my.freenom.com: 0x61e6b9da50 [can pipeline]
* Re-using existing connection! (#0) with host my.freenom.com
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
> GET /domains.php?a=renewals HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Referer: https://my.freenom.com/clientarea.php
Cookie: WHMCSZH5eHTGhfvzP=4n248vb87cq4s18rj18e46qun7

< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 03:47:35 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 4025
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Encoding: gzip
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Vary: Accept-Encoding
<
* Connection #0 to host my.freenom.com left intact
[2021-08-30 11:47:35] 由于没有启用邮件功能，故本次不通过邮件送信。
*   Trying 149.154.167.220...
* TCP_NODELAY set
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=api.telegram.org
*  start date: Mar 24 13:48:17 2020 GMT
*  expire date: May 23 16:17:38 2022 GMT
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> POST /bot1912397175:AAE4VcuxyWqJqfy7SqJbFUpOGdYah_W3p6o/sendMessage HTTP/1.1
Host: api.telegram.org
User-Agent: GuzzleHttp/6.5.1 curl/7.58.0 PHP/8.0.9
Content-Type: application/x-www-form-urlencoded
Content-Length: 989

* upload completely sent off: 989 out of 989 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.18.0
< Date: Mon, 30 Aug 2021 03:47:37 GMT
< Content-Type: application/json
< Content-Length: 988
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
<
* Connection #0 to host api.telegram.org left intact
[2021-08-30 11:47:37] Snqmebqkqkenwndnsdbabajdbd@gmail.com：执行成功，今次没有需要续期的域名

bot设置没问题，我的其他东西还能推
![Screenshot_20210830-115000](https://user-images.githubusercontent.com/60541200/131282660-1c90d9b2-5760-4ee9-b3e3-8fba89b77053.png)

**Comment by lq-259** [comment]
> 另外也不排除你申请的 token 或者 chatid 存在问题。需要逐一排查。

debug：
root@localhost:~/freenom# php run
[2021-08-30 11:47:30] 当前程序版本 v0.3
*   Trying 63.33.210.48...
* TCP_NODELAY set
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=my.freenom.com
*  start date: Apr 29 00:00:00 2021 GMT
*  expire date: Apr 29 23:59:59 2022 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> POST /dologin.php HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Referer: https://my.freenom.com/clientarea.php
Content-Length: 67

* upload completely sent off: 67 out of 67 bytes
< HTTP/1.1 302 Found
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 03:47:33 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Location: clientarea.php
< Pragma: no-cache
< Set-Cookie: WHMCSZH5eHTGhfvzP=u53f36p96rs4el3d8s9ruki4r2; path=/; HttpOnly
< Set-Cookie: WHMCSZH5eHTGhfvzP=4n248vb87cq4s18rj18e46qun7; path=/; HttpOnly
< Set-Cookie: WHMCSUser=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
<
* Connection #0 to host my.freenom.com left intact
* Found bundle for host my.freenom.com: 0x61e6b9da50 [can pipeline]
* Re-using existing connection! (#0) with host my.freenom.com
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
> GET /clientarea.php HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Cookie: WHMCSZH5eHTGhfvzP=4n248vb87cq4s18rj18e46qun7

< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 03:47:34 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 3813
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Encoding: gzip
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Vary: Accept-Encoding
<
* Connection #0 to host my.freenom.com left intact
* Found bundle for host my.freenom.com: 0x61e6b9da50 [can pipeline]
* Re-using existing connection! (#0) with host my.freenom.com
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
> GET /domains.php?a=renewals HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Referer: https://my.freenom.com/clientarea.php
Cookie: WHMCSZH5eHTGhfvzP=4n248vb87cq4s18rj18e46qun7

< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 03:47:35 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 4025
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Encoding: gzip
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Vary: Accept-Encoding
<
* Connection #0 to host my.freenom.com left intact
[2021-08-30 11:47:35] 由于没有启用邮件功能，故本次不通过邮件送信。
*   Trying 149.154.167.220...
* TCP_NODELAY set
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=api.telegram.org
*  start date: Mar 24 13:48:17 2020 GMT
*  expire date: May 23 16:17:38 2022 GMT
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> POST /bot1912397175:AAE4VcuxyWqJqfy7SqJbFUpOGdYah_W3p6o/sendMessage HTTP/1.1
Host: api.telegram.org
User-Agent: GuzzleHttp/6.5.1 curl/7.58.0 PHP/8.0.9
Content-Type: application/x-www-form-urlencoded
Content-Length: 989

* upload completely sent off: 989 out of 989 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.18.0
< Date: Mon, 30 Aug 2021 03:47:37 GMT
< Content-Type: application/json
< Content-Length: 988
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
<
* Connection #0 to host api.telegram.org left intact
[2021-08-30 11:47:37] Snqmebqkqkenwndnsdbabajdbd@gmail.com：执行成功，今次没有需要续期的域名

bot设置没问题，我的其他东西还能推
![Screenshot_20210830-115000](https://user-images.githubusercontent.com/60541200/131282660-1c90d9b2-5760-4ee9-b3e3-8fba89b77053.png)

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/131311448-64849990-bad0-49a5-905d-5ab1cbe18c1d.png)

![image](https://user-images.githubusercontent.com/34597923/131311376-c4630f84-c540-41bd-bbe9-2a31c2f11f5e.png)

我刚刚试了一下，整个流程是通的，无法重现你的问题。

你可以试试在 libs/TelegramBot.php 文件中，添加如下的代码，保存后回到命令行执行 php run，把控制台的打印的内容发出来：
添加的内容为：var_dump($rp);
![image](https://user-images.githubusercontent.com/34597923/131312584-dda3a6af-48e3-4324-85c7-07a235ac804d.png)

因为 tg 发信这里没有抛异常，所以目前应该是因为 tg 那边业务逻辑过程没有走通，没抛异常则不好定位问题，这是后续会改进的地方。所以现在请按我上面说的操作，理论上就可以破案了。

**Comment by lq-259** [comment]
> ![image](https://user-images.githubusercontent.com/34597923/131311448-64849990-bad0-49a5-905d-5ab1cbe18c1d.png)
> 
> ![image](https://user-images.githubusercontent.com/34597923/131311376-c4630f84-c540-41bd-bbe9-2a31c2f11f5e.png)
> 
> 我刚刚试了一下，整个流程是通的，无法重现你的问题。
> 
> 你可以试试在 libs/TelegramBot.php 文件中，添加如下的代码，保存后回到命令行执行 php run，把控制台的打印的内容发出来：
> 添加的内容为：var_dump($rp);
> ![image](https://user-images.githubusercontent.com/34597923/131312584-dda3a6af-48e3-4324-85c7-07a235ac804d.png)
> 
> 因为 tg 发信这里没有抛异常，所以目前应该是因为 tg 那边业务逻辑过程没有走通，没抛异常则不好定位问题，这是后续会改进的地方。所以现在请按我上面说的操作，理论上就可以破案了。

这是加了代码之后的：
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 3.18.124-g4aa1814c63b8 aarch64)
Ubuntu 18.04.5 LTS [running via Linux Deploy]
Last login: Mon Aug 30 12:35:02 2021 from 192.168.1.8
root@localhost:~# cd freenom
root@localhost:~/freenom# php run
[2021-08-30 18:10:07] 当前程序版本 v0.3
*   Trying 63.33.210.48...
* TCP_NODELAY set
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=my.freenom.com
*  start date: Apr 29 00:00:00 2021 GMT
*  expire date: Apr 29 23:59:59 2022 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> POST /dologin.php HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Referer: https://my.freenom.com/clientarea.php
Content-Length: 67

* upload completely sent off: 67 out of 67 bytes
< HTTP/1.1 302 Found
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 10:10:10 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Location: clientarea.php
< Pragma: no-cache
< Set-Cookie: WHMCSZH5eHTGhfvzP=mb0grgsmc8tkq3st4m1f1291s3; path=/; HttpOnly
< Set-Cookie: WHMCSZH5eHTGhfvzP=sdf0nk93ho3fv92q94bdnm8pj1; path=/; HttpOnly
< Set-Cookie: WHMCSUser=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
<
* Connection #0 to host my.freenom.com left intact
* Found bundle for host my.freenom.com: 0x585d6aea50 [can pipeline]
* Re-using existing connection! (#0) with host my.freenom.com
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
> GET /clientarea.php HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Cookie: WHMCSZH5eHTGhfvzP=sdf0nk93ho3fv92q94bdnm8pj1

< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 10:10:11 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 3760
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Encoding: gzip
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Vary: Accept-Encoding
<
* Connection #0 to host my.freenom.com left intact
* Found bundle for host my.freenom.com: 0x585d6aea50 [can pipeline]
* Re-using existing connection! (#0) with host my.freenom.com
* Connected to my.freenom.com (63.33.210.48) port 443 (#0)
> GET /domains.php?a=renewals HTTP/1.1
Host: my.freenom.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Referer: https://my.freenom.com/clientarea.php
Cookie: WHMCSZH5eHTGhfvzP=sdf0nk93ho3fv92q94bdnm8pj1

< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Mon, 30 Aug 2021 10:10:12 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 3979
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Encoding: gzip
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Vary: Accept-Encoding
<
* Connection #0 to host my.freenom.com left intact
[2021-08-30 18:10:12] 由于没有启用邮件功能，故本次不通过邮件送信。
*   Trying 149.154.167.220...
* TCP_NODELAY set
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=api.telegram.org
*  start date: Mar 24 13:48:17 2020 GMT
*  expire date: May 23 16:17:38 2022 GMT
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> POST /bot1912397175:AAE4VcuxyWqJqfy7SqJbFUpOGdYah_W3p6o/sendMessage HTTP/1.1
Host: api.telegram.org
User-Agent: GuzzleHttp/6.5.1 curl/7.58.0 PHP/8.0.9
Content-Type: application/x-www-form-urlencoded
Content-Length: 989

* upload completely sent off: 989 out of 989 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.18.0
< Date: Mon, 30 Aug 2021 10:10:14 GMT
< Content-Type: application/json
< Content-Length: 988
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
<
* Connection #0 to host api.telegram.org left intact
array(2) {
  ["ok"]=>
  bool(true)
  ["result"]=>
  array(6) {
    ["message_id"]=>
    int(17299)
    ["from"]=>
    array(4) {
      ["id"]=>
      int(1912397175)
      ["is_bot"]=>
      bool(true)
      ["first_name"]=>
      string(6) "e5_bot"
      ["username"]=>
      string(10) "e55bot_bot"
    }
    ["chat"]=>
    array(5) {
      ["id"]=>
      int(641981595)
      ["first_name"]=>
      string(1) "s"
      ["last_name"]=>
      string(2) "ao"
      ["username"]=>
      string(7) "verysao"
      ["type"]=>
      string(7) "private"
    }
    ["date"]=>
    int(1630318213)
    ["text"]=>
    string(279) "报告，今天没有域名需要续期，所有域名情况如下：

yswl.cf还有193天到期，更多信息可以参考Freenom官网哦~

（如果你不想每次执行都收到推送，请将 .env 中 NOTICE_FREQ 的值设为0，使程序只在有续期操作时才推送）"
    ["entities"]=>
    array(3) {
      [0]=>
      array(4) {
        ["offset"]=>
        int(25)
        ["length"]=>
        int(7)
        ["type"]=>
        string(9) "text_link"
        ["url"]=>
        string(15) "http://yswl.cf/"
      }
      [1]=>
      array(3) {
        ["offset"]=>
        int(34)
        ["length"]=>
        int(3)
        ["type"]=>
        string(4) "bold"
      }
      [2]=>
      array(4) {
        ["offset"]=>
        int(49)
        ["length"]=>
        int(9)
        ["type"]=>
        string(9) "text_link"
        ["url"]=>
        string(45) "https://my.freenom.com/domains.php?a=renewals"
      }
    }
  }
}
[2021-08-30 18:10:14] Snqmebqkqkenwndnsdbabajdbd@gmail.com：执行成功，今次没有需要续期的域名
root@localhost:~/freenom#

**Comment by luolongfei** [comment]
![2A2D6534-7A6E-420E-98FF-981AF9B1AF9D](https://user-images.githubusercontent.com/34597923/131489429-b33a212a-8641-4a06-89a1-69e7671cc14b.png)
这里看到 tg 的服务器返回的 ok=true，说明推送是成功的。你应该检查你建立的机器人 e55bot_bot 的来信。

**Comment by lq-259** [comment]
> ![2A2D6534-7A6E-420E-98FF-981AF9B1AF9D](https://user-images.githubusercontent.com/34597923/131489429-b33a212a-8641-4a06-89a1-69e7671cc14b.png)
> 这里看到 tg 的服务器返回的 ok=true，说明推送是成功的。你应该检查你建立的机器人 e55bot_bot 的来信。

尴尬，非常抱歉打扰你了🙈
