### ISSUE TITLE
railway 的每月免费额度已经更改，超限后会暂停

### ISSUE THREAD

**Issue by asadahimeka** [luolongfei/freenom#133]
免费用户每月最多运行 500 小时
https://docs.railway.app/reference/pricing#execution-time-limit

<img src="https://user-images.githubusercontent.com/31837214/184572067-d027654f-5e64-419f-8621-3ca1a0b65baf.png" width=300>

<img src="https://user-images.githubusercontent.com/31837214/184572323-43e95f11-21b0-417c-93fa-1ac190c58b8b.png" width=600>

**Comment by luolongfei** [comment]
那这个平台就不香了。。

**Comment by luolongfei** [comment]
超限后，下个月会自动重新部署吗

**Comment by asadahimeka** [comment]
> 超限后，下个月会自动重新部署吗

不太清楚，好像是会恢复运行

**Comment by luolongfei** [comment]
免费的平台限制就是多

**Comment by asadahimeka** [comment]
> 免费的平台限制就是多

<img src="https://user-images.githubusercontent.com/31837214/184598213-0e6d0b9b-0cfb-4bd7-a5bb-8218455753dd.png" width=300>

绑个卡后也有 5 刀的免费额度，还能继续凑活用，但是有了支付方式哪天扣钱就不好说了。

这波估计就是为了让免费用户绑卡 🙄

**Comment by luolongfei** [comment]
绑卡后解绑，或者限额可能会好一点。
