### ISSUE TITLE
railway不能用了

### ISSUE THREAD

**Issue by superen7527** [luolongfei/freenom#139]
You have used all your available resources this month. Deployments have been removed and can be re-deployed next month. Upgrade now to re-enable deploys.

是需要哪里领取额度还是不能免费用？ 顺便问问为什么推荐使用railway 除了变量方便写还有什么优势？

另外之前那个帖子麻烦close一下 被锁了

**Comment by superen7527** [comment]
#126

**Comment by luolongfei** [comment]
railway 是小厂商，人一多就扛不住了，改变服务条款了。所以现在不再推荐它了。目前推荐通过 heroku 部署，具体参考项目文档。

**Comment by superen7527** [comment]
哦原来是小厂 太久没上git了 原来更新说明和推荐了 白开个issue 打扰了。 顺便把这个(#126)一起关了吧

**Comment by superen7527** [comment]
Heroku 免费额度调整

2022 年 10 月 26 日，Heroku 将开始删除非活动帐户以及已停用一年以上的帐户。 

2022 年 11 月 28 日，Heroku 将停止提供免费服务。

调整后，Heroku 的价格最低为 7 美元/月。

—— Heroku Blog via 轻惋频道

heroku也不能用了hhh 昨天看到的消息

**Comment by luolongfei** [comment]
已经更新文档了

**Comment by superen7527** [comment]
嗯 #126 这个能不能关一下 close不了 要不你解除一下锁定
