### ISSUE TITLE
指定脚本执行时间问题

### ISSUE THREAD

**Issue by Mattraks** [luolongfei/freenom#14]
https://github.com/luolongfei/freenom/blob/94137327e4619391e2a2c9732da0bdc6d25afa4a/docker-entrypoint.sh#L41
判断问题导致部分Cron 表达式无法执行
[如每周一早晚10点执行任务
](https://crontab.guru/#0_10,22_*_*_1)
```
RUN_AT="0 10,22 * * 1"
```

**Comment by luolongfei** [comment]
收到，将在下个小版本修正。

**Comment by luolongfei** [comment]
源码部分已经改进了相关正则，不过修改太少，暂时不会发新版本，可以先自行通过 Dockerfile 构建新镜像，或者等待下个版本发布。

**Comment by cs0663c** [comment]
怎么设置每周一次或2次，太频繁会不会被点名

**Comment by luolongfei** [comment]
> 怎么设置每周一次或2次，太频繁会不会被点名

@cs0663c 
一天一次的频率实际上不算太频繁，自定义 cron 表达式即可实现每周一次或者两次，表达式可以参考：
https://crontab.guru/once-a-week

然后在 docker 执行命令中指定 cron 表达式： `-e RUN_AT="0 0 * * 0"`

**Comment by cs0663c** [comment]
谢谢，你的提醒 尝试成功了

**Comment by luolongfei** [comment]
@Mattraks v0.4.4 已经改进 Cron 表达式验证正则。
