### ISSUE TITLE
Heroku will soon stop offering free product plans

### ISSUE THREAD

**Issue by Elletear** [luolongfei/freenom#140]
- `Starting October 26, 2022, we will begin deleting inactive accounts and associated storage for accounts that have been inactive for over a year. Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services. We will be sending out a series of email communications to affected users.`

- `We will continue to provide low-cost solutions for compute and data resources: Heroku Dynos starts at $7/month, Heroku Data for Redis® starts at $15/month, Heroku Postgres starts at $9/month. See [Heroku Pricing Information](https://www.heroku.com/pricing) for current details. These include all the features of the free plans with additional certificate management and the assurance your dynos do not sleep to help ensure your apps are responsive.`

source [blog-news](https://blog.heroku.com/next-chapter)

**Comment by luolongfei** [comment]
@Elletear 收到。😂运气不要太好。。。不管我推荐哪个平台，哪个平台总能在不久后宣布关闭服务或者改变服务条款。
