### ISSUE TITLE
服务器上部署后运行php run报错

### ISSUE THREAD

**Issue by y785201595** [luolongfei/freenom#15]
root@debian11:/data/wwwroot/freenom# php run
PHP Fatal error:  Class 'Luolongfei\Libs\Log' not found in /data/wwwroot/freenom/run on line 54

Fatal error: Class 'Luolongfei\Libs\Log' not found in /data/wwwroot/freenom/run on line 54

用的是方式三：直接拉取源码部署的

**Comment by luolongfei** [comment]
php 版本，代码版本，系统环境提供一下

**Comment by luolongfei** [comment]
另外，你是之前就克隆代码部署过，现在只是拉取了新版本，还是全新克隆代码部署的？

**Comment by y785201595** [comment]
php 版本：PHP 5.6.40 (cli) (built: Sep  1 2021 02:34:06) 代码版本：v0.4.3 - 2021-11-07 系统环境：Debian 10.2.1-6 部署方式：全新克隆代码部署

**Comment by luolongfei** [comment]
@y785201595 php 版本最低要求 7.2 以上，不支持低版本 php。php 5.6 是古董了。如果不好升级 php 版本，建议你直接通过 docker 部署。

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/142797329-0863acd3-2aa5-4e92-85d2-b402bad7ed68.png)

**Comment by y785201595** [comment]
收到，升级到php7.2解决
