### ISSUE TITLE
feature_request 让 Actions 恢复工作

### ISSUE THREAD

**Issue by fscarmen** [luolongfei/freenom#152]
你好，十分感谢你的项目，我一直使用着，直至两个月前 Actions 跑不动，后面再查了一下资料，发现是 freenom 把 github 的 IP 列为黑名单。于是我在原来的步骤中加上安装 warp ，ac 恢复正常跑。但有点奇怪的是我用最新项目的文件跑不成功的，在最后的 php run 时报错。用一年前的版本则可以。如果可能，麻烦看看，谢谢！
以下是 run.yml 的内容
```
######  说明  ######
# 1、Fork 本仓库
# 2、在你 Fork 的本仓库下的 Settings > Secrets 画面追加以下几个 secret 变量：
# FREENOM_USERNAME、FREENOM_PASSWORD、MULTIPLE_ACCOUNTS、MAIL_USERNAME、MAIL_PASSWORD、TO、MAIL_ENABLE、TELEGRAM_CHAT_ID、
# TELEGRAM_BOT_TOKEN、TELEGRAM_BOT_ENABLE、NOTICE_FREQ
# （注：此处列出了所有可用变量，你只用追加你需要用到的变量，变量的具体含义请参考本项目的 .env 文件中的说明，一般情况下，.env 文件中的某些
#  项存在默认值，如果默认值满足你的需求则可不追加到 Secrets，它们会保持默认）
#
# 下面定时任务中的时间是世界时间，每天 10:00 执行，由于创建虚拟环境会消耗时间，故任务会延迟 30 秒左右执行
#
# @Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>
#
######  end 说明  ######

name: Run it on action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 20 20 * * 2
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.1.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Setting
        run: |
          echo 'Renew freenom domain name automatically.'
          echo '@Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>'
          echo '@Url: https://github.com/luolongfei/freenom'
          cp .env.example .env
          if [[ ('${{ secrets.FREENOM_USERNAME }}' == '' || '${{ secrets.FREENOM_PASSWORD }}' == '') && '${{ secrets.MULTIPLE_ACCOUNTS }}' == '' ]]; then echo '你在 Github 的当前项目的 Settings > Secrets 画面没有设置任何与账户信息相关的 secret 值，无法正常运行，请添加新的 secret 值，设置 FREENOM_USERNAME 与 FREENOM_PASSWORD，或者设置 MULTIPLE_ACCOUNTS，以及 .env 文件中其它必要项，各项的具体含义与格式参考本项目 .env 文件中的说明。'; fi
          if [ '${{ secrets.FREENOM_USERNAME }}' != '' ]; then sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='${{ secrets.FREENOM_USERNAME }}'/" .env; fi
          if [ '${{ secrets.FREENOM_PASSWORD }}' != '' ]; then sed -i "s/^FREENOM_PASSWORD=.*$/FREENOM_PASSWORD='${{ secrets.FREENOM_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.MULTIPLE_ACCOUNTS }}' != '' ]; then sed -i "s/^MULTIPLE_ACCOUNTS=.*$/MULTIPLE_ACCOUNTS='${{ secrets.MULTIPLE_ACCOUNTS }}'/" .env; fi
          if [ '${{ secrets.MAIL_USERNAME }}' != '' ]; then sed -i "s/^MAIL_USERNAME=.*$/MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}'/" .env; fi
          if [ '${{ secrets.MAIL_PASSWORD }}' != '' ]; then sed -i "s/^MAIL_PASSWORD=.*$/MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.TO }}' != '' ]; then sed -i "s/^TO=.*$/TO='${{ secrets.TO }}'/" .env; fi
          if [ '${{ secrets.MAIL_ENABLE }}' != '' ]; then sed -i "s/^MAIL_ENABLE=.*$/MAIL_ENABLE='${{ secrets.MAIL_ENABLE }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_CHAT_ID }}' != '' ]; then sed -i "s/^TELEGRAM_CHAT_ID=.*$/TELEGRAM_CHAT_ID='${{ secrets.TELEGRAM_CHAT_ID }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_TOKEN }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_TOKEN=.*$/TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_ENABLE }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_ENABLE=.*$/TELEGRAM_BOT_ENABLE='${{ secrets.TELEGRAM_BOT_ENABLE }}'/" .env; fi
          if [ '${{ secrets.NOTICE_FREQ }}' != '' ]; then sed -i "s/^NOTICE_FREQ=.*$/NOTICE_FREQ='${{ secrets.NOTICE_FREQ }}'/" .env; fi
          sed -i "s/^ON_GITHUB_ACTIONS=.*$/ON_GITHUB_ACTIONS=true/" .env
      - name: Install WARP
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends net-tools iproute2 openresolv dnsutils iptables wireguard-tools
          sudo echo "[Interface]
          PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
          Address = 172.16.0.2/32
          Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
          DNS = 8.8.8.8,8.8.4.4
          MTU = 1280
          [Peer]
          PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
          AllowedIPs = 0.0.0.0/0
          AllowedIPs = ::/0
          Endpoint = 162.159.193.10:2408" | sudo tee /etc/wireguard/wgcf.conf
          sudo wg-quick up wgcf
          sudo curl -s4m8 https://ip.gs/json
      - name: Run
        run: |
          php run
```

**Comment by QiTianzu** [comment]
还是在 RUN 这步失败
```
##[debug]Evaluating condition for step: 'Run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> ***
##[debug]Result: ***
##[debug]Starting: Run
##[debug]Loading inputs
##[debug]Loading env
Run php run
  **mphp run
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: ***
##[debug]/usr/bin/bash -e /home/runner/work/_temp/a59a5783-af***c-404a-a464-0b5447bcf***79.sh
[[2](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:2)022-***0-08 ***[3](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:3):38:27] 当前程序版本 v0.5.*** 
[2022-***0-08 ***3:38:27] 共发现 *** 个 freenom 账户 
[2022-***0-08 ***3:38:27] 开始处理第 *** 个 freenom 账户：*** [***/***] 
[2022-***0-08 ***3:38:35] ***：执行成功，今次没有需要续期的域名。 
[2022-***0-08 ***3:38:35] {"type":2,"message":"fopen(\/home\/runner\/work\/freenom\/freenom\/logs\/2022-***0\/08.log): failed to open stream: Permission denied","file":"\/home\/runner\/work\/freenom\/freenom\/app\/helpers.php","line":98} 
PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/home/runner/work/freenom/freenom/logs/2022-***0/08.log" could not be opened in append mode: failed to open stream: Permission denied in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:***0

Fatal error: Uncaught UnexpectedValueException: The stream or file "/home/runner/work/freenom/freenom/logs/2022-***0/08.log" could not be opened in append mode: failed to open stream: Permission denied in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:***0
Stack trace:
#0 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#*** /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(3[4](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:4)4): Monolog\Handler\AbstractProcessingHandler->handle(Array)
Stack trace:
#2 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(4[5](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:5)8): Monolog\Logger->addRecord(400, '\xE7\xA8\x8B\xE5\xBA\x8F\xE[6](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:6)\x84\x8F\xE5\xA4\x96\xE[7](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:7)\xBB\x[8](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:8)8...', Array)
#0 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(3[9](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:9)): Monolog\Handler\StreamHandler->write(Array)
#3 /home/runner/work/freenom/freenom/libs/Log.php(***7): Monolog\Logger->addError('\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
#*** /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/runner/work/freenom/freenom/run(54): Luolongfei\Libs\Log::e in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line ***0
#2 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(458): Monolog\Logger->addRecord(400, '\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
#3 /home/runner/work/freenom/freenom/libs/Log.php(***7): Monolog\Logger->addError('\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
#4 /home/runner/work/freenom/freenom/run(54): Luolongfei\Libs\Log::e in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line ***0
Error: Process completed with exit code [25](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:26)5.
##[debug]Finishing: Run
```

**Comment by fscarmen** [comment]
> 还是在 RUN 这步失败

要用项目旧的文件，新的不支持，所以我才让作者看看的。

[freenom-master.zip](https://github.com/luolongfei/freenom/files/9738506/freenom-master.zip)

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/62703343/194691959-7e03e8b2-d68c-4091-a399-9710bbbb0ab5.png">

**Comment by fscarmen2** [comment]
> 还是在 RUN 这步失败
> 
> ```
> ##[debug]Evaluating condition for step: 'Run'
> ##[debug]Evaluating: success()
> ##[debug]Evaluating success:
> ##[debug]=> ***
> ##[debug]Result: ***
> ##[debug]Starting: Run
> ##[debug]Loading inputs
> ##[debug]Loading env
> Run php run
>   **mphp run
>   shell: /usr/bin/bash -e {0}
>   env:
>     COMPOSER_PROCESS_TIMEOUT: 0
>     COMPOSER_NO_INTERACTION: ***
> ##[debug]/usr/bin/bash -e /home/runner/work/_temp/a59a5783-af***c-404a-a464-0b5447bcf***79.sh
> [[2](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:2)022-***0-08 ***[3](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:3):38:27] 当前程序版本 v0.5.*** 
> [2022-***0-08 ***3:38:27] 共发现 *** 个 freenom 账户 
> [2022-***0-08 ***3:38:27] 开始处理第 *** 个 freenom 账户：*** [***/***] 
> [2022-***0-08 ***3:38:35] ***：执行成功，今次没有需要续期的域名。 
> [2022-***0-08 ***3:38:35] {"type":2,"message":"fopen(\/home\/runner\/work\/freenom\/freenom\/logs\/2022-***0\/08.log): failed to open stream: Permission denied","file":"\/home\/runner\/work\/freenom\/freenom\/app\/helpers.php","line":98} 
> PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/home/runner/work/freenom/freenom/logs/2022-***0/08.log" could not be opened in append mode: failed to open stream: Permission denied in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:***0
> 
> Fatal error: Uncaught UnexpectedValueException: The stream or file "/home/runner/work/freenom/freenom/logs/2022-***0/08.log" could not be opened in append mode: failed to open stream: Permission denied in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:***0
> Stack trace:
> #0 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
> #*** /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(3[4](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:4)4): Monolog\Handler\AbstractProcessingHandler->handle(Array)
> Stack trace:
> #2 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(4[5](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:5)8): Monolog\Logger->addRecord(400, '\xE7\xA8\x8B\xE5\xBA\x8F\xE[6](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:6)\x84\x8F\xE5\xA4\x96\xE[7](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:7)\xBB\x[8](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:8)8...', Array)
> #0 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(3[9](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:9)): Monolog\Handler\StreamHandler->write(Array)
> #3 /home/runner/work/freenom/freenom/libs/Log.php(***7): Monolog\Logger->addError('\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
> #*** /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
> #4 /home/runner/work/freenom/freenom/run(54): Luolongfei\Libs\Log::e in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line ***0
> #2 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(458): Monolog\Logger->addRecord(400, '\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
> #3 /home/runner/work/freenom/freenom/libs/Log.php(***7): Monolog\Logger->addError('\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
> #4 /home/runner/work/freenom/freenom/run(54): Luolongfei\Libs\Log::e in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line ***0
> Error: Process completed with exit code [25](https://github.com/QiTianzu/freenom/actions/runs/3209220843/jobs/5245884889#step:6:26)5.
> ##[debug]Finishing: Run
> ```

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/92626977/194691908-55c21feb-7b4b-415a-a6a9-41618c4d0290.png">

**Comment by QiTianzu** [comment]
> > 还是在 RUN 这步失败
> 
> 要用项目旧的文件，新的不支持，所以我才让作者看看的。
> 
> [freenom-master.zip](https://github.com/luolongfei/freenom/files/9738506/freenom-master.zip)
> 
> <img alt="image" width="1659" src="https://user-images.githubusercontent.com/62703343/194691959-7e03e8b2-d68c-4091-a399-9710bbbb0ab5.png">

可以了，谢谢！

**Comment by fscarmen** [comment]
> 可以了，谢谢！

向你请教个问题，你如何快速把zip文件里的所有文件上传到github的？github限制了一次只能上传100个文件

**Comment by QiTianzu** [comment]
> > 可以了，谢谢！
> 
> 向你请教个问题，你如何快速把zip文件里的所有文件上传到github的？github限制了一次只能上传100个文件

我用的命令行

**Comment by fscarmen** [comment]
> > > 可以了，谢谢！
> > 
> > 
> > 向你请教个问题，你如何快速把zip文件里的所有文件上传到github的？github限制了一次只能上传100个文件
> 
> 我用的命令行

麻烦告诉我一下呢，我不太会用 git 命令行

**Comment by QiTianzu** [comment]
> > > > 可以了，谢谢！
> > > 
> > > 
> > > 向你请教个问题，你如何快速把zip文件里的所有文件上传到github的？github限制了一次只能上传100个文件
> > 
> > 
> > 我用的命令行
> 
> 麻烦告诉我一下呢，我不太会用 git 命令行

如果你是自己新建仓库，在本地建一个用库名命名的文件夹，在命令行中进入该文件夹，执行 `git init` 初始化仓库，把文件放到这个文件夹中，执行
```
git add .
git commit -m "Add files"
git branch -M main
git remote add origin https://github.com/githubusername/repositoryname.git
git push -u origin main
```
如果是从 GitHub 克隆已有仓库，执行 `git clone https://github.com/githubusername/repository.git`，把除了 .git 文件夹以外的文件都删除，执行 `git rm .`，再把要替换的文件放进去，执行
```
git add .
git commit -m "Replace files"
git branch -M main
git push -u origin main
```

**Comment by fscarmen** [comment]
弄好了，要建一个 Personal access token，有 repo 和  workflow 的权限，之后运行下面的才行
```
git remote set-url origin https://<githubtoken>@github.com/<username>/<repositoryname>.git
```

**Comment by fscarmen** [comment]
> > > 可以了，谢谢！
> > 
> > 
> > 向你请教个问题，你如何快速把zip文件里的所有文件上传到github的？github限制了一次只能上传100个文件
> 
> 我用的命令行

嘻嘻，用 warp 8开头的IP骗过freenom了

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/62703343/194697581-da191ab5-c6da-487f-aa8c-afb3664475cd.png">

**Comment by luolongfei** [comment]
你这个报错看起来和代码没关系，是权限问题，没法写入日志

**Comment by fscarmen** [comment]
> 你这个报错看起来和代码没关系，是权限问题，没法写入日志

这个不是报错啊，是成功的，报错的我现在弄个给你看

**Comment by fscarmen** [comment]
情况1: 这个是项目最新版本下(2022年10月8日 22:30)，没有安装 warp，运行 AC 的报错，看样子是 IP 被 freenom 限制了导致超时

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/62703343/194712762-d11309d7-51af-4def-a0db-ede6ece5aeb2.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/62703343/194713299-80ecef32-37e4-4d8b-a750-9b8bfd530091.png">

情况2: 这个是项目最新版本下(2022年10月8日 22:30)，在安装 warp 后，运行报错，看样子是能正常访问了，但后面的信息处理部份报错
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/62703343/194712605-69aba19e-e23a-4519-b440-795f975cf3c8.png">

情况3: 这个是项目一年前的版本，在安装 warp 后，ac 跑成功的。楼上的兄弟和另外两位网友也成功了，至于成功项目的压缩文件在上面，旧版本反而OK
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/62703343/194697581-da191ab5-c6da-487f-aa8c-afb3664475cd.png">

**Comment by fscarmen** [comment]
奇怪，最新的运行 ac 会报错，但 tg 仍然会收到信息

<img width="533" alt="image" src="https://user-images.githubusercontent.com/62703343/194714731-9311bea9-b3f8-431a-b311-e54ff61241bd.png">

**Comment by luolongfei** [comment]
@fscarmen 这个报错是说没有权限写日志，理论上程序是正常走逻辑的，你试试在 cp .env.example .env 的下面一行，加上 chmod -Rf 777 logs，看看能否成功，不行的话可能得改代码，改成直接输出日志不写文件

**Comment by fscarmen2** [comment]
> @fscarmen 这个报错是说没有权限写日志，理论上程序是正常走逻辑的，你试试在 cp .env.example .env 的下面一行，加上 chmod -Rf 777 logs，看看能否成功，不行的话可能得改代码，改成直接输出日志不写文件

可以，完美

**Comment by fscarmen** [comment]
> 加上 chmod -Rf 777 logs

经常完美，现在的 yml 文件是这样写的
```
######  说明  ######
# 1、Fork 本仓库
# 2、在你 Fork 的本仓库下的 Settings > Secrets 画面追加以下几个 secret 变量：
# FREENOM_USERNAME、FREENOM_PASSWORD、MULTIPLE_ACCOUNTS、MAIL_USERNAME、MAIL_PASSWORD、TO、MAIL_ENABLE、TELEGRAM_CHAT_ID、
# TELEGRAM_BOT_TOKEN、TELEGRAM_BOT_ENABLE、NOTICE_FREQ
# （注：此处列出了所有可用变量，你只用追加你需要用到的变量，变量的具体含义请参考本项目的 .env 文件中的说明，一般情况下，.env 文件中的某些
#  项存在默认值，如果默认值满足你的需求则可不追加到 Secrets，它们会保持默认）
#
# 下面定时任务中的时间是世界时间，每天 10:00 执行，由于创建虚拟环境会消耗时间，故任务会延迟 30 秒左右执行
#
# @Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>
#
######  end 说明  ######

name: Run it on action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 20 21 * * 4
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.1.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Setting
        run:  |
          echo 'Renew freenom domain name automatically.'
          echo '@Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>'
          echo '@Url: https://github.com/luolongfei/freenom'
          cp .env.example .env
          if [[ ('${{ secrets.FREENOM_USERNAME }}' == '' || '${{ secrets.FREENOM_PASSWORD }}' == '') && '${{ secrets.MULTIPLE_ACCOUNTS }}' == '' ]]; then echo '你在 Github 的当前项目的 Settings > Secrets 画面没有设置任何与账户信息相关的 secret 值，无法正常运行，请添加新的 secret 值，设置 FREENOM_USERNAME 与 FREENOM_PASSWORD，或者设置 MULTIPLE_ACCOUNTS，以及 .env 文件中其它必要项，各项的具体含义与格式参考本项目 .env 文件中的说明。'; fi
          if [ '${{ secrets.FREENOM_USERNAME }}' != '' ]; then sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='${{ secrets.FREENOM_USERNAME }}'/" .env; fi
          if [ '${{ secrets.FREENOM_PASSWORD }}' != '' ]; then sed -i "s/^FREENOM_PASSWORD=.*$/FREENOM_PASSWORD='${{ secrets.FREENOM_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.MULTIPLE_ACCOUNTS }}' != '' ]; then sed -i "s/^MULTIPLE_ACCOUNTS=.*$/MULTIPLE_ACCOUNTS='${{ secrets.MULTIPLE_ACCOUNTS }}'/" .env; fi
          if [ '${{ secrets.MAIL_USERNAME }}' != '' ]; then sed -i "s/^MAIL_USERNAME=.*$/MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}'/" .env; fi
          if [ '${{ secrets.MAIL_PASSWORD }}' != '' ]; then sed -i "s/^MAIL_PASSWORD=.*$/MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.TO }}' != '' ]; then sed -i "s/^TO=.*$/TO='${{ secrets.TO }}'/" .env; fi
          if [ '${{ secrets.MAIL_ENABLE }}' != '' ]; then sed -i "s/^MAIL_ENABLE=.*$/MAIL_ENABLE='${{ secrets.MAIL_ENABLE }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_CHAT_ID }}' != '' ]; then sed -i "s/^TELEGRAM_CHAT_ID=.*$/TELEGRAM_CHAT_ID='${{ secrets.TELEGRAM_CHAT_ID }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_TOKEN }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_TOKEN=.*$/TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_ENABLE }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_ENABLE=.*$/TELEGRAM_BOT_ENABLE='${{ secrets.TELEGRAM_BOT_ENABLE }}'/" .env; fi
          if [ '${{ secrets.NOTICE_FREQ }}' != '' ]; then sed -i "s/^NOTICE_FREQ=.*$/NOTICE_FREQ='${{ secrets.NOTICE_FREQ }}'/" .env; fi
          sed -i "s/^ON_GITHUB_ACTIONS=.*$/ON_GITHUB_ACTIONS=true/" .env
      - name: Setup WARP
        run:  |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends net-tools iproute2 openresolv dnsutils iptables wireguard-tools
          echo "[Interface]
          PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
          Address = 172.16.0.2/32
          Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
          DNS = 8.8.8.8,8.8.4.4
          MTU = 1280
          [Peer]
          PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
          AllowedIPs = 0.0.0.0/0
          AllowedIPs = ::/0
          Endpoint = 162.159.193.10:2408" | sudo tee /etc/wireguard/wgcf.conf
          sudo wg-quick up wgcf
          sudo curl -s4m8 https://ip.gs/json
      - name: Run
        run:  |
          php run
```

**Comment by luolongfei** [comment]
日志权限问题可以临时参考 https://github.com/luolongfei/freenom/issues/159#issuecomment-1294429327
