### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by WinningBuddha** [luolongfei/freenom#155]
**描述问题**

```
robot邮件报登录出错
```

**重现步骤**

```
重启服务
```

**截图&日志**

![2022-10-19_093817](https://user-images.githubusercontent.com/26793051/196579330-789ce80a-1313-43de-8f9d-926d94bf28fc.png)
![FireShot Capture 009 - Service overview - Mogenius Studio - studio mogenius com](https://user-images.githubusercontent.com/26793051/196579342-0b0c1c86-e11f-4165-afd3-262249d3ded9.png)

**你做了哪些尝试**
查看 instance logs
[2022-10-19 09:13:15] 出错：登录 freenom 出错。错误信息：cURL error 7: Failed to connect to my.freenom.com port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.freenom.com/dologin.php(Error code: 34520002) 
查看 https://curl.haxx.se/libcurl/c/libcurl-errors.html
CURLE_COULDNT_CONNECT (7)
Failed to connect() to host or proxy.
使用脚本[v0.5.1](https://github.com/luolongfei/freenom/releases/tag/v0.5.1)重新部署
邮件和 instance logs收到同样错误，参照上图
立刻手动网页登录freenom，可以登录。

```
描述你发现问题后做了哪些尝试，以及尝试结果，方便我快速排除某些问题，提高沟通效率。
```
.
**环境信息**

- 系统：  mogenius
- PHP 版本：   
- 脚本版本：  *v0.5.1*
- 是否 Docker：  *是*

**额外的备注**
环境变量里我没有添加 FREENOM_PROXY 参数
# 【可选】 Freenom 代理 [Optional] Freenom proxy e.g. http://127.0.0.1:1081 or socks5://127.0.0.1:1080
FREENOM_PROXY=''

**Comment by luolongfei** [comment]
这个是服务器那边的网络问题，代码层面无解。那个代理你必须得有才能配置。

**Comment by WinningBuddha** [comment]
> 这个是服务器那边的网络问题，代码层面无解。那个代理你必须得有才能配置。

ok,那我就关闭issue
