### ISSUE TITLE
为什么我用koyeb部署一直Unhealthy？？？

### ISSUE THREAD

**Issue by yumimik** [luolongfei/freenom#157]
**部署时能正常收到邮箱消息(日志也没有报错)，但就是一直Unhealthy然后后就变error.......................**
![屏幕截图 2022-10-23 024517](https://user-images.githubusercontent.com/108549983/197358272-5813faba-6167-4ea6-959b-6f7b45d3a1e2.png)

![屏幕截图 2022-10-23 025008](https://user-images.githubusercontent.com/108549983/197358253-d45f17ad-73dd-4d17-88a4-f6edeb8fef7e.png)
99b.png)
![屏幕截图 2022-10-23 030504](https://user-images.githubusercontent.com/108549983/197358256-dd5f41ad-07a5-47de-95c3-e74d31be5aa6.png)

**Comment by luolongfei** [comment]
部署完成后，应用地址能否正常访问？

**Comment by yumimik** [comment]
不能！

**Comment by luolongfei** [comment]
用的哪个镜像

**Comment by yumimik** [comment]
https://hub.docker.com/r/luolongfei/freenom

**Comment by yumimik** [comment]
啊  原来有  镜像有koyeb版   现在才发现..........  我不是一键进入的

**Comment by luolongfei** [comment]
下次记得读文档

**Comment by yumimik** [comment]
有读  但没讲有 KOYEB版   我直接拉最新的.........   因为我不是一键进去的
