### ISSUE TITLE
執行成功 沒收到信件

### ISSUE THREAD

**Issue by sogadisk** [luolongfei/freenom#16]
NoticeFreq 設定1
執行php run 結果為綠色執行成功
收件信箱沒收到信件  
發送信箱為gmail,收件信箱同為gmail
確認過收件信箱填寫正確  但執行成功 沒收到信件

**Comment by luolongfei** [comment]
@sogadisk 问题可能出在gmail上。请将config.php中的debug值设为true，然后执行php run >> debug.log，然后将debug.log日志的内容贴到这里，然后再附上logs目录下的日志，以便定位问题。

**Comment by sogadisk** [comment]
@luolongfei 
剛才看了一下Debug沒發現甚麼問題  .
最後去check了一下 gmail垃圾郵件箱找到了信件 .
烏龍一場  打擾了

**Comment by luolongfei** [comment]
不客气
