### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by Devil-guigui** [luolongfei/freenom#167]
只用过az的webapp部署过Oneindex，是可以的。
如果webapp可以部署，手机上也能用ksweb来搞一个了，大大有空是否能解答一下小小疑问

**Comment by luolongfei** [comment]
只有 webapp 端是什么意思？

**Comment by Devil-guigui** [comment]
不好意思，我的描述不够准确，就是一个单纯的web应用，PHP7.4的环境，不可以运行shell，方便的话，我把我的web应用给大大测试一下 。

**Comment by luolongfei** [comment]
可以发邮件给我看看 ff@llfapp.com

**Comment by Devil-guigui** [comment]
给大大发过去了，密码卡了我好久才。。。

**Comment by waahah** [comment]
windows本地PHP环境如何部署测试？

**Comment by luolongfei** [comment]
> windows本地PHP环境如何部署测试？

安装个 docker 然后用 docker 方式

**Comment by Devil-guigui** [comment]
1
