### ISSUE TITLE
feature_request 使用koyeb如何修改每天定时启动的时间？

### ISSUE THREAD

**Issue by 8ty** [luolongfei/freenom#169]
感觉看见那个续期详情挺好的，可以加个开关吗

**Comment by luolongfei** [comment]
是说续期的执行日志实时展示对吧？那个没有改过。

**Comment by 8ty** [comment]
> 是说续期的执行日志实时展示对吧？那个没有改过。

不好意思，原来是加载太慢了

**Comment by luolongfei** [comment]
自定义执行时间，需要配置一个名为 RUN_AT 的环境变量。

**Comment by luolongfei** [comment]
没关系

**Comment by 8ty** [comment]
> 自定义执行时间，需要配置一个名为 RUN_AT 的环境变量。

是cron 格式吗

**Comment by luolongfei** [comment]
可以是 cron，也可以直接是个时间点，比如 11:24

**Comment by 8ty** [comment]
> 可以是 cron，也可以直接是个时间点，比如 11:24

好，感谢
