### ISSUE TITLE
可不可以增加一个对阿里云函数的支持

### ISSUE THREAD

**Issue by KenBillionsYuan** [luolongfei/freenom#17]
在尝试部署到阿里云函数计算的时候提示
{"errorMessage":"function handler not found","errorType":"Exception","stackTrace":{"file":"\/var\/fc\/runtime\/php7.2\/src\/invoke.php","line":71,"traceString":""}}
可以尝试支持一下吗

**Comment by luolongfei** [comment]
目前只支持了腾讯云函数。阿里云函数的话能提供一下文档吗？有文档的话可以考虑支持。

**Comment by KenBillionsYuan** [comment]
[https://help.aliyun.com/product/50980.html?spm=5176.21213303.J_6704733920.7.7a103edaY6SJMm&scm=20140722.S_help%40%40%E4%BA%A7%E5%93%81%E9%A1%B5%40%4050980.S_0%2Bos.ID_50980-RL_%E5%87%BD%E6%95%B0-OR_helpmain-V_2-P0_0](url)

**Comment by luolongfei** [comment]
@KenBillionsYuan v0.4.4 已支持 阿里云函数。相关文档也已经更新了。
