### ISSUE TITLE
不能正常工作？

### ISSUE THREAD

**Issue by lhpmain** [luolongfei/freenom#17]
[2020-03-03 23:41:10] 执行出错：检测到你尚未配置freenom账户信息，请修改.env文件中与账户相关的项，否则程序无法正常运作(Error code: 32520001) [{"file":"\/www\/wwwroot\/test.lhpcn.ml\/app\/Console\/FreeNom.php","line":313,"function":"getAccounts","class":"Luolongfei\\App\\Console\\FreeNom","type":"->","args":[]},{"file":"\/www\/wwwroot\/test.lhpcn.ml\/run","line":85,"function":"handle","class":"Luolongfei\\App\\Console\\FreeNom","type":"->","args":[]}]

**Comment by luolongfei** [comment]
@lhpmain 请确保已在.env文件中正确填写账户和密码。这个报错是因为没有读取到有效的账户配置。

**Comment by j999yp** [comment]
@luolongfei  在网页登录后确认freenom和gmail的账号密码都是正确的，仍然出现此错误

**Comment by luolongfei** [comment]
@j999yp 报这个错是因为你还没有走到登录那一步，是连你的账户配置都还没读取到。方便把.env文件的内容贴出来吗？密码你可以用xxx替代

**Comment by j999yp** [comment]
@luolongfei 
FREENOM_USERNAME='j999yp@gmail.com'
FREENOM_PASSWORD='xxx'
MAIL_USERNAME='j999yp@gmail.com'
MAIL_PASSWORD='xxx'
TO='xxx@qq.com'

**Comment by luolongfei** [comment]
@j999yp 可以加我qq593198779，有时间给你远程看一下，如果按正确的文档步骤走的话不应该出现那种报错。

**Comment by luolongfei** [comment]
@j999yp @lhpmain 请贴出你们的环境情况，包括具体系统的版本，php版本，以及具体的操作流程。因为我这边无法重现你们的问题。

**Comment by j999yp** [comment]
@luolongfei 安装php后需要重启vps吗？我没有重启过

**Comment by j999yp** [comment]
@luolongfei centos 8 x64, php 7.4, 操作流程同教程

**Comment by j999yp** [comment]
@luolongfei 是否需要在防火墙放行特定端口？

**Comment by luolongfei** [comment]
@j999yp 不需要放行特定端口。我这边没centos8环境，你可以换centos7试试

**Comment by lhpmain** [comment]
> @lhpmain 请确保已在.env文件中正确填写账户和密码。这个报错是因为没有读取到有效的账户配置。

看情况是代码读取Freenom.com的帐号信息有问题引起的。

**Comment by luolongfei** [comment]
@lhpmain 你的机器环境是怎样的，在cnetos7上没法重现你说的问题。

**Comment by luolongfei** [comment]
@lhpmain 代码这一块不可能有问题。

**Comment by luolongfei** [comment]
@lhpmain @j999yp 由于没有任何回应，默认你的问题已经解决，此问题先关闭，你可以随时重新开启。
