### ISSUE TITLE
Cloudflare Workers续期代码

### ISSUE THREAD

**Issue by pencilnav** [luolongfei/freenom#171]
之前在https://github.com/luolongfei/freenom/issues/145 提过，我有一个可用的Workers续期代码，但是由于Actions事件被封仓库了。

现在找回了代码，并且将代码传到了这个仓库，有需要可自取：https://github.com/PencilNavigator/Freenom-Workers

备用仓库地址：https://dev.azure.com/PencilNavigator/Freenom-Workers

能否在这个项目的Readme添加一个友链呢?

**Comment by luolongfei** [comment]
可以的，晚点我给你加一个

**Comment by luolongfei** [comment]
已经加上了：https://github.com/luolongfei/freenom#-%E6%9C%AC%E9%A1%B9%E7%9B%AE%E7%9A%84%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%9E%E7%8E%B0

**Comment by pencilnav** [comment]
> 已经加上了：https://github.com/luolongfei/freenom#-%E6%9C%AC%E9%A1%B9%E7%9B%AE%E7%9A%84%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%9E%E7%8E%B0

好的，非常感谢！

**Comment by luolongfei** [comment]
不客气，我这个仓库也被封过，能理解这种心情。
