### ISSUE TITLE
bug_report: telegram机器人推送"登录 freenom 出错。错误信息：cURL error 28", docker 常看日志无输出

### ISSUE THREAD

**Issue by github3C** [luolongfei/freenom#178]
**描述问题**

```
telegram机器人推送信息 "登录 freenom 出错。错误信息：cURL error 28"
使用 docker logs 则没有对应日志输出
```

**重现步骤**

```
docker restart freenom
隔天会出现该状况
```

**截图&日志**
![圖片](https://user-images.githubusercontent.com/114391756/206842364-7ae52e68-3e38-40a8-b4f3-d58eda32d1af.png)

**你做了哪些尝试**

```
之前也出现过 cURL error 28
尝试过在docker中使用 curl -v https://my.freenom.com
查看是否可以正常访问
```

**环境信息**

- 系统：  *openwrt arm*
- PHP 版本：  *容器自带*
- 脚本版本：  *v0.5.1*
- 是否 Docker：  *是*

**额外的备注**

🈚

**Comment by luolongfei** [comment]
这个报错是网络超时，看起来和代码没有关系。

**Comment by github3C** [comment]
> 这个报错是网络超时，看起来和代码没有关系。

**cURL error 28** 我查了issue记录是超时, 我的意思是 `docker logs` 不是持续记录日志的吗?
以前是有的

**Comment by luolongfei** [comment]
> > 这个报错是网络超时，看起来和代码没有关系。
> 
> **cURL error 28** 我查了issue记录是超时, 我的意思是 `docker logs` 不是持续记录日志的吗? 以前是有的

docker 里面是实时记录日志的，但是 docker logs 输出的日志只输出前台执行的日志，后面定时任务执行的日志会放在 logs 目录下，不会在 docker logs 命令中输出。

**Comment by github3C** [comment]
> 

好的明白~
