### ISSUE TITLE
docker镜像 程序版本问题

### ISSUE THREAD

**Issue by paopaomalin** [luolongfei/freenom#193]
**描述问题**

```
docker pull 最新 latest镜像，运行 查看容器日志
![image](https://user-images.githubusercontent.com/95903329/211481295-c8614628-0924-4ef7-b224-7a06157c6eb3.png)
程序版本显示V 0.4.4
是否是dockerhub 未更新？
```

```

**环境信息**
群晖docker

**Comment by luolongfei** [comment]
检查你是否使用了 dockerhub 镜像地址，镜像地址里可能没有同步到最新版本。

**Comment by paopaomalin** [comment]
![image](https://user-images.githubusercontent.com/95903329/211490747-7eea03fe-b30d-407c-8eb8-a6d4e7d0ec34.png)
以确定和dockerhub latest上面的sha256 一致了

**Comment by luolongfei** [comment]
我没法重现你的问题。版本号是硬编码在代码中的，如果你更新到最新版，那版本号一定是最新的。

**Comment by luolongfei** [comment]
你可以按文档里写的步骤，在 vps 上试试看，版本号是怎样的

**Comment by paopaomalin** [comment]
谢谢。已经更换为标签：0.5.1的镜像了，目前日志里面也是0.5.1了
