### ISSUE TITLE
登陆出错，跟证书有关？

### ISSUE THREAD

**Issue by linkser** [luolongfei/freenom#2]
Curl 错误 - 登录FREENOM - 60 - Peer certificate cannot be authenticated with given CA certificates: SSL certificate problem: self signed certificate in certificate chain(Error code: 6001)

**Comment by luolongfei** [comment]
curl error code 60错误，和程序无关，一般是你服务器环境里的证书问题。可能是服务器中受信任的证书颁发机构不全。你可以试下如下操作（适用于centos7）：
```
[root@ip]# cd /etc/pki/tls/certs
[root@ip]# pwd
/etc/pki/tls/certs
[root@ip]# mv ca-bundle.crt ca-bundle.crt.bak
[root@ip]# wget https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt --no-check-certificate # 因为刚刚把证书文件更名了，所以这里不要检查证书，否则不通过。
[root@ip]# chmod 777 ca-bundle.crt
[root@ip]# service php-fpm restart （或者重启服务器也行）
```
