### ISSUE TITLE
续期出现异常时，进程返回值不应为0

### ISSUE THREAD

**Issue by garywill** [luolongfei/freenom#20]
你好，感谢你编写了这个脚本！

在服务器上部署时，打算让shell判断续期是否成功，再执行相应操作。而我发现无论`php run`成功或异常都`exit 0`，能改进下不

**Comment by luolongfei** [comment]
通过退出码来判断显然是走不通的，因为php中exit(0)方法会导致整个脚本退出。比如你有10个域名，第一个域名续期失败就exit()，那么整个脚本就结束了，不会再续期其它域名或者登录其它账户进行续期操作。

**Comment by luolongfei** [comment]
你可以尝试获取php脚本的输出，在php中追加一些echo语句，比如续期失败或抛出异常时echo xxx，然后在shell脚本中根据输出来判断续期情况。

**Comment by garywill** [comment]
那能不能有异常时先记录下来，不影响下一个域名，最后退出时再exit(n)
许多cli工具是这样的。既能够通过返回值通知用户异常，又把能做的部分做了

**Comment by luolongfei** [comment]
> 那能不能有异常时先记录下来，不影响下一个域名，最后退出时再exit(n)
> 许多cli工具是这样的。既能够通过返回值通知用户异常，又把能做的部分做了

可以这样做，但是意义不大。我比较好奇你在shell脚本里发现续期出错是要做什么操作？

**Comment by luolongfei** [comment]
@garywill 你可以在php代码中加个全局变量=true，然后一旦走到续期出错或者异常的分支，你就把这个全局变量的值改为false，然后在脚本执行的最后根据这个全局变量来决定exit(n)什么退出码。因为这里续期可能涉及多个账户的多个域名，并不能根据一个退出码来判断是所有账户都失败了，还是部分账户的部分域名失败。所以加这个退出码感觉没什么意义
