### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ffha** [luolongfei/freenom#20]
![IMG_20211204_221522](https://user-images.githubusercontent.com/79425603/144712980-93b0c732-bb7d-49fe-bc43-298cea09f7b2.jpg)

**Comment by luolongfei** [comment]
？

**Comment by ffha** [comment]
我在安卓手机上用Termux(一个Linux环境模拟器)成功运行

**Comment by luolongfei** [comment]
环境里有php？

**Comment by ffha** [comment]
用自带的包管理器装的

**Comment by luolongfei** [comment]
又多了一种使用方式
