### ISSUE TITLE
Koyeb已更新服务条款

### ISSUE THREAD

**Issue by Jakob-Boy** [luolongfei/freenom#204]
**描述问题**

Koyeb已更新服务条款，老账户登录提示```users not found```，但是通过找回密码以及重新注册都显示用户存在，新注册账户要求验证信用卡并扣款1刀验证。据Koyeb pricing 页面显示：验证卡后依然有2个免费容器可以使用。heroku倒下后越来越多的serverless要求绑卡并且限制。

**额外的备注**

[演示页面](https://freenom-luolongfei.koyeb.app/)已经404，我自己部署的服务也无法打开，应该是无了。

**Comment by luolongfei** [comment]
演示页面挂掉，可能是因为我太久没登录，如果过段时间不登录，容器也会被停掉。所以搞这种平台确实浪费时间

**Comment by Jakob-Boy** [comment]
> 演示页面挂掉，可能是因为我太久没登录，如果过段时间不登录，容器也会被停掉。所以搞这种平台确实浪费时间

现在登录也提示找不到用户，注册要信用卡，我感觉就是要求强制验证了。。很无语

**Comment by luolongfei** [comment]
免费平台基本都难逃这种情况

**Comment by Misaka-blog** [comment]
> **描述问题**
> 
> Koyeb已更新服务条款，老账户登录提示`users not found`，但是通过找回密码以及重新注册都显示用户存在，新注册账户要求验证信用卡并扣款1刀验证。据Koyeb pricing 页面显示：验证卡后依然有2个免费容器可以使用。heroku倒下后越来越多的serverless要求绑卡并且限制。
> 
> **额外的备注**
> 
> [演示页面](https://freenom-luolongfei.koyeb.app/)已经404，我自己部署的服务也无法打开，应该是无了。

我的老账户还在

**Comment by waloyn** [comment]
railway也禁止国区访问了。

Access denied
Error code 1020
You do not have access to www.railway.app.
The site owner may have set restrictions that prevent you from accessing the site.

**Comment by Jakob-Boy** [comment]
> railway也禁止国区访问了。
> 
> Access denied Error code 1020 You do not have access to [www.railway.app](http://www.railway.app). The site owner may have set restrictions that prevent you from accessing the site.

我railway一直是挂梯子上的，刚刚试了一下用cloudflare warp，也不行，是通过cloudflare防火墙做的规则，都是CN
![railway](https://ipfs-images.pages.dev/file/8011e0206021f67a41b24.png)

**Comment by waloyn** [comment]
> > railway也禁止国区访问了。
> > Access denied Error code 1020 You do not have access to [www.railway.app](http://www.railway.app). The site owner may have set restrictions that prevent you from accessing the site.
> 
> 我railway一直是挂梯子上的，刚刚试了一下用cloudflare warp，也不行，是通过cloudflare防火墙做的规则，都是CN ![railway](https://camo.githubusercontent.com/d9b46190d8f73149a93933bf9aee4276bff5d481917eed0906719fce83704d4f/68747470733a2f2f697066732d696d616765732e70616765732e6465762f66696c652f3830313165303230363032316636376134316232342e706e67)

我月初还是直连访问的，刚才说是上去更新下资料，结果拒绝访问，以为是封IP了，然后用2个不同归属地的手机卡也是拒绝访问，才知道是直接封国区了。

**Comment by luolongfei** [comment]
其实还是能用，只是过段时间要登录一下。
https://freenom-luolongfei.koyeb.app/

**Comment by Jakob-Boy** [comment]
刚刚上去看了一下，可以了，笑死，估计前几天炸了。。居然能登录了，我先关闭这个issue
