### ISSUE TITLE
[bug_report] 邮箱授权码中含#导致的配置文件解析错误

### ISSUE THREAD

**Issue by lzw-723** [luolongfei/freenom#206]
**描述问题**

```
189邮箱生成的授权码中含#导致配置文件解析错误。
```

**重现步骤**

.env中
```
# 机器人邮箱密码（Gmail 填应用专用密码，QQ 邮箱或 163 邮箱填授权码） Password of the robot email
MAIL_PASSWORD="Di#0J8=5u#8Ju!4B"
```

**截图&日志**

`执行出错：Failed to parse dotenv file due to an unexpected escape sequence.`

**你做了哪些尝试**

单引号改双引号
```
MAIL_PASSWORD="xxxx#xx"
```

**环境信息**

- 系统：  *Ubuntu 20.04.4*
- PHP 版本：  **
- 脚本版本：  *v2.6*
- 是否 Docker：  * 是*

**额外的备注**

- 是否可以在.env中备注一下这种情况

**Comment by luolongfei** [comment]
实际上文档中有提到这种情况，你需要在“#”前面加上“\”进行转义，因为在 .env 中，“#”表示注释。

**Comment by luolongfei** [comment]
可以提个 pr

**Comment by lzw-723** [comment]
谢谢解答，本人眼拙
