### ISSUE TITLE
更换为centos7后依然无法使用

### ISSUE THREAD

**Issue by j999yp** [luolongfei/freenom#21]
@luolongfei 抱歉回复晚了，这几天有空了将vps的系统更换为centos7，依然出现未配置账户信息的错误，错误代码如下：
执行出错：检测到你尚未配置freenom账户信息，请修改.env文件中与账户相关的项，否则程序无法正常运作(Error code: 32520001) [{"file":"\/data\/wwwroot\/freenom\/app\/Console\/FreeNom.php","line":313,"function":"getAccounts","class":"Luolongfei\\App\\Console\\FreeNom","type":"->"},{"file":"\/data\/wwwroot\/freenom\/run","line":69,"function":"handle","class":"Luolongfei\\App\\Console\\FreeNom","type":"->"}]

**Comment by luolongfei** [comment]
@j999yp 远程看看
