### ISSUE TITLE
企业微信送信失败：cURL error 7

### ISSUE THREAD

**Issue by sean908** [luolongfei/freenom#21]
**描述问题**
```
按照手册注册企业,创建应用,随后填入对应的键值
运行后log中提示“企业微信送信失败：cURL error 7: Failed to connect to qyapi.weixin.qq.com port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)”
```

**重现步骤**
```
无
```

**截图&日志**
![image](https://user-images.githubusercontent.com/4495319/144995073-5c87fce1-b038-4030-b2f3-6d17d2df2068.png)

**你做了哪些尝试**
```
重新核查了一遍所需配置的键值对, 无误
```

**环境信息**
 - docker 19.03.12
 - freenom续期脚本latest(2021年12月7日)

**额外的备注**
- N/A.

**Comment by luolongfei** [comment]
curl error 7 可能的原因很多，你这里后面的报错是连接被拒绝，有可能是微信屏蔽了你的 ip，所以建议你在安装了 docker 的宿主机上，执行以下命令并截图给我：
telnet qyapi.weixin.qq.com 443

上面的命令检查你宿主机到微信的服务器 443 端口是否可达

**Comment by sean908** [comment]
> curl error 7 可能的原因很多，你这里后面的报错是连接被拒绝，有可能是微信屏蔽了你的 ip，所以建议你在安装了 docker 的宿主机上，执行以下命令并截图给我： telnet qyapi.weixin.qq.com 443
> 
> 上面的命令检查你宿主机到微信的服务器 443 端口是否可达

很奇怪这个软路由没有telnet, 用ssh可以吗?
![image](https://user-images.githubusercontent.com/4495319/145170603-bedc21bb-819a-445e-a27c-8fac5ccad52e.png)
我看输出日志显示建立了连接

**Comment by luolongfei** [comment]
看起来是建立了连接。你重启 docker 或者 重启容器，还能重现这种情况吗？尝试多次，看看是否能每次都重现？看你日志里就只有企业微信的服务器无法连接过去，所以和本地的防火墙应该没关系，大概率是网络问题。

> **截图&日志** ![image](https://user-images.githubusercontent.com/4495319/144995073-5c87fce1-b038-4030-b2f3-6d17d2df2068.png)
>

**Comment by sean908** [comment]
> 看起来是建立了连接。你重启 docker 或者 重启容器，还能重现这种情况吗？尝试多次，看看是否能每次都重现？看你日志里就只有企业微信的服务器无法连接过去，所以和本地的防火墙应该没关系，大概率是网络问题。
> 
> > **截图&日志** ![image](https://user-images.githubusercontent.com/4495319/144995073-5c87fce1-b038-4030-b2f3-6d17d2df2068.png)

刚刚把容器重启了下, 看日志里依旧提示失败.
不知是否跟容器使用的网络有关? 先前用qinglong时遇到过一样的无法访问的情况.
![image](https://user-images.githubusercontent.com/4495319/145315523-9896e4be-d773-4f6a-8e96-d2962ca2ab3f.png)

**Comment by luolongfei** [comment]
容器在没有指定网络空间的情况下，默认是桥接到 docker 的网络上的，docker 又默认桥接到你宿主机的网络。加之你的这种情况，可以很明显地看到容器在请求 freenom 域名的时候是成功的，唯独访问企业微信的服务器连接失败，所以应该不是网络问题，网络有问题所有请求都该失败才对。

**Comment by luolongfei** [comment]
你能每次重启容器都百分百重现吗？尝试了几次？每次重启 docker 都能恢复正常？这种问题我这边没法重现，所以不太好定位问题。

**Comment by luolongfei** [comment]
另外可以再尝试看看，把送信配置为 bark 或者 tg 方式，看看有没有同样的问题，如果别的送信方式都没有问题，唯独企业微信的域名请求不成功，那么问题应该出在 微信 这边。

**Comment by sean908** [comment]
> 你能每次重启容器都百分百重现吗？尝试了几次？每次重启 docker 都能恢复正常？这种问题我这边没法重现，所以不太好定位问题。

没有重启docker, 里面还跑了其它容器, 所以我只重启了freenom容器.
重启了1次; 将容器移除再新建执行了3 4次. 都没收到微信推送.

我同时配置了tg跟微信, tg正常收到通知.

补充:
又试了下bark, 可以收到推送.
如果微信不需要我配合调试的话, 可以关闭issue~

**Comment by luolongfei** [comment]
也许是企业微信风控，telnet 只能说明服务可达，但是请求里表明了请求者身份就被 ban 了也有可能，不过只是猜测，想要验证的话可以配置 server 酱，server 酱的企业通道和这里的企业微信一模一样，看看通过 server 酱的服务器去发起请求能否成功，如果 server 酱的请求也不成功，那么可能就是身份问题，如果 server 酱能成功，那么可能是你宿主机器的 ip 等问题。要想进一步验证，还可以给宿主机器套一层代理。

不过这种情况看起来很少有人遇到，那么这里就先关闭 issue 了，如果有任何新的发现可以随时打开。
