### ISSUE TITLE
 查看日志的时候发现只有部署当天的日志（之后几天的时间里都没有输出日志）。是不是需要加一个定时重启的任务？

### ISSUE THREAD

**Issue by jane77u** [luolongfei/freenom#215]

**Comment by luolongfei** [comment]
docker 里你只能看到第一次执行的日志，后面定时任务只能在日志文件里看到。

**Comment by jane77u** [comment]
> docker 里你只能看到第一次执行的日志，后面定时任务只能在日志文件里看到。



> docker 里你只能看到第一次执行的日志，后面定时任务只能在日志文件里看到。

谢谢解答。我后来开启了每天通知才知道它其实是每天都在运行的，不需要添加添加定时重启。
