### ISSUE TITLE
无法登录freenom账号,bark发送失败: cURL error 6

### ISSUE THREAD

**Issue by saidenny** [luolongfei/freenom#22]
**描述问题**
```
按文档部署后测试正常,但是第二天登录查看日志时显示:
无法登录freenom账号,bark发送失败: cURL error 6
```

**重现步骤**
```
无
```

**截图&日志**
重启docker前
![image](https://user-images.githubusercontent.com/43678843/145136068-462b4c65-96d3-4864-b45c-d775d1eaed19.png)
![image](https://user-images.githubusercontent.com/43678843/145135729-d7b845b8-4592-460e-aec7-7fa6242fc3e9.png)
重启docker后
![image](https://user-images.githubusercontent.com/43678843/145136122-fc3261cd-ed44-42a7-bf3e-d53900a4fd26.png)

**你做了哪些尝试**
```
重启容器后问题依旧
重启docker后问题消失,恢复正常
```

**环境信息**
 - centos8 x64
 - Docker version 20.10.11, build dea9396
 - freenom续期脚本版本 v0.4.3

**额外的备注**
无

**Comment by cs0663c** [comment]
我的也是出错
![image](https://user-images.githubusercontent.com/59052041/145143717-a289f32b-fe99-4581-bc2e-9c46ec5b2222.png)

**Comment by luolongfei** [comment]
@cs0663c @saidenny 
curl error 6 错误是无法解析远程主机，一般是由于 DNS 解析出错，而容器中的系统默认的 DNS 服务器 是谷歌的 8.8.8.8：
![image](https://user-images.githubusercontent.com/34597923/145182039-ac226313-113d-4220-bd4f-7f0e92f7cb95.png)

可能是因为网络波动导致，但不确定，所以这边想要掌握的情况是：
1、你们在重启 docker （非重启容器）后能否再次重现这种情况？
2、你们的 docker 宿主机器是位于国内还是国外？
3、宿主机器是普通的 vps 还是例如 群晖 这类 nas？

**Comment by cs0663c** [comment]
> @cs0663c @saidenny curl error 6 错误是无法解析远程主机，一般是由于 DNS 解析出错，而容器中的系统默认的 DNS 服务器 是谷歌的 8.8.8.8： ![image](https://user-images.githubusercontent.com/34597923/145182039-ac226313-113d-4220-bd4f-7f0e92f7cb95.png)
> 
> 可能是因为网络波动导致，但不确定，所以这边想要掌握的情况是： 1、你们在重启 docker （非重启容器）后能否再次重现这种情况？ 2、你们的 docker 宿主机器是位于国内还是国外？ 3、宿主机器是普通的 vps 还是例如 群晖 这类 nas？

重启容器同样问题存在， 删除容器重新部署同样问题，
重启docker 问题消失了，好了，
韩国vps centos-7部署的 
运行没有成功也没有推送失败消息
之前是设置了每周一次 第一次是运行的，一周后出现问题，才发觉的，具体是什么原因我也不知道

**Comment by luolongfei** [comment]
@cs0663c 看来和容器关系不大。重启 docker 后，还有办法重现问题吗？

**Comment by saidenny** [comment]
> @cs0663c @saidenny curl error 6 错误是无法解析远程主机，一般是由于 DNS 解析出错，而容器中的系统默认的 DNS 服务器 是谷歌的 8.8.8.8： ![image](https://user-images.githubusercontent.com/34597923/145182039-ac226313-113d-4220-bd4f-7f0e92f7cb95.png)
> 
> 可能是因为网络波动导致，但不确定，所以这边想要掌握的情况是： 1、你们在重启 docker （非重启容器）后能否再次重现这种情况？ 2、你们的 docker 宿主机器是位于国内还是国外？ 3、宿主机器是普通的 vps 还是例如 群晖 这类 nas？

1重启docker后问题消失,试过重启docker重现不了问题
2日本 oracle vps

**Comment by luolongfei** [comment]
@saidenny 重启 docker 后，再重启容器，问题是否可以再现？可以测试多次看看

**Comment by luolongfei** [comment]
@saidenny 注意现在只重启容器，而非 docker

**Comment by saidenny** [comment]
> @saidenny 注意现在只重启容器，而非 docker

重启容器复现不了问题,现在很正常

**Comment by luolongfei** [comment]
@saidenny 挺奇怪的。要是能百分百重现问题，才好调查。那先这样，等有新的状况再看看。

**Comment by luolongfei** [comment]
@cs0663c 你这边有尝试重启 docker 吗？（注意，非重启容器）

**Comment by cs0663c** [comment]
> ）

尝试重启容器是不能解决的，删除重新部署也不行，重启docker 服务问题就没有了，
还有另外个问题，启动时间如果设置成-e RUN_AT="10 10 * * 4,6" 这样启动不成功，-e RUN_AT="10 10 * * 4" 这个可以正常

**Comment by luolongfei** [comment]
@cs0663c 现在你是重启 docker 后的状态，那么现在你再重启容器（非 docker）能重现问题吗？

这个 cron 表达式验证是已知问题，目前的源码里已经改进了，只是还没发布而已。之前的正则只考虑了每个位置都是单个字符，即只考虑每周执行一次或者每天执行一次的情况，现在新的正则已经支持所有规则了。

**Comment by cs0663c** [comment]
> 现在你是重启 docker 后的状态，那么现在你再重启容器（非 docker）能重现问题吗？

现在再重启容器（非 docker）能重现问题吗? 答：不能 ！
最起码重启几次都没出现，没有故障重现，现在设置了每周1次，看看下周会不会出现问题！

**Comment by luolongfei** [comment]
@cs0663c 那目前看起来可能是宿主机器安装的 docker 什么位置存在问题，这种情况目前解决方案就是重启 docker。

先关闭 issue 了，如果有新的状况可以随时重新打开。

**Comment by yeaman2020** [comment]
重启 docker 也不行
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-7bfeb394-1a3a-4e53-9a65-80e040a2be64/1895dc6f-9fdd-433a-b92c-0f7480c94db6.png)

**Comment by luolongfei** [comment]
@yeaman2020 参考 https://github.com/luolongfei/freenom/issues/87
