### ISSUE TITLE
尝试还可以正常手动续期记录于2023.6.21

### ISSUE THREAD

**Issue by cyao2q** [luolongfei/freenom#228]
尝试还可以正常手动续期
尝试还可以正常手动续期
尝试还可以正常手动续期
![1](https://github.com/luolongfei/freenom/assets/10820724/f6ce08a9-3759-44c9-97ec-98be26cbb2b0)
![2](https://github.com/luolongfei/freenom/assets/10820724/f0346c9c-665a-4582-b06e-c59e91615994)

**Comment by sxx1314** [comment]
freenom 现在会发域名到期的邮件提醒吗？

**Comment by misaka19002** [comment]
今天登录freenom发现有验证码了，这个程序不会出现异常吗？

**Comment by cyao2q** [comment]
> 今天登录freenom发现有验证码了，这个程序不会出现异常吗？

早就无法登录了 你那边没报警？

**Comment by misaka19002** [comment]
> > 今天登录freenom发现有验证码了，这个程序不会出现异常吗？
> 
> 早就无法登录了 你那边没报警？

现在在用eu.org域名了，突然想起来freenom还有个域名就看了一眼。快过期了，在想怎么续期。估计也只能临时手动处理一下了。

**Comment by cyao2q** [comment]
> > > 今天登录freenom发现有验证码了，这个程序不会出现异常吗？
> > 
> > 
> > 早就无法登录了 你那边没报警？
> 
> 现在在用eu.org域名了，突然想起来freenom还有个域名就看了一眼。快过期了，在想怎么续期。估计也只能临时手动处理一下了。

eu.org申请好累啊我也申请了2 历时1个多月 不过这个都是二级域名 解析也只能 dnspod或者cloudflare 不大方便 还是 tk的顶级域名好 不回收让手动续期就好
