### ISSUE TITLE
好像又没有验证了，今天突然正常了

### ISSUE THREAD

**Issue by Mrzqd** [luolongfei/freenom#229]
**描述问题**

```
好像又没有验证了，今天突然正常了，tg推送发现正常了
```

**重现步骤**

```
步骤一
```

**截图&日志**

![image](https://github.com/luolongfei/freenom/assets/104408988/f41f7195-354a-46e2-bbc5-3fc27127eaab)

**你做了哪些尝试**

```
描述你发现问题后做了哪些尝试，以及尝试结果，方便我快速排除某些问题，提高沟通效率。
```

**环境信息**

- 系统：  *（例如 debian11 x64）*
- PHP 版本：  *（例如 php8.0）*
- 脚本版本：  *（例如 v0.4.5）*
- 是否 Docker：  *（例如 是）*

**额外的备注**

- Add any other context about the problem here.
- 可额外备注比如你的运行环境是否 NAS，是否宝塔面板等信息

**Comment by luolongfei** [comment]
这个是偶尔不出现验证，一般情况下还是有的，所以也可以考虑不关容器。
