### ISSUE TITLE
支持登录间隔

### ISSUE THREAD

**Issue by superen7527** [luolongfei/freenom#237]
看到新版多次重试可以登录后，找了个稳定机子跑，专门看了日志，跑了五个多小时才登录进去，本来我挺满意的，登录会有cookie，下次短时间内不需要重新登录。

然而最近我的通知出现了很诡异的一幕，一直在不是我设置的时间登录成功返回结果，还告诉我不是新版是旧版，我多次看了github这个项目版本和我确实一样，感觉很诡异。

后来突然想明白了，是我把旧版本的服务器重启了，之前是手动关了重启后又自动启动。所以出现了旧版本的通知。

随后我观察了半个月左右，发现了，旧版的服务通知很准时，而且旧版是没有重试机制(我旧了好几个版本估摸是去年的)。说明旧版可以做到几乎百分百登录不出验证码。虽然有几次是提示登录失败，但是过几天又成功了。我想了想，在我看新版的日志的时候，前面一直重试的间隔特别短但是几乎都失败(说明如果出现验证码短时间内重试没有意义一样拦下来)，成功都是到后面一百多次重试才成功，这个时候间隔已经很长了。而我这个旧版没有重试相当于是每天都登录一次 成功率高的吓人。

***

上面是过程 小作文hhh 记录一下

***

而我一直都有一个担忧，已经出现验证码，结果不过验证码重新登录，间隔特别短还差不多规律重试，这样行为特征完全符合机器操作。而且重试机制频繁。在我了解到这个原理后，马上就想到了更好的解决方案：

登录不需要多次重试 只要保持重试间隔足够长，可以自定义时间默认2 3小时左右就够了。
为了保持在设定的时间 应该根据cookie过期时间或者是轮询定时间隔检测cookie是否失效失效先进行登录，保证在被调用的时候cookie总是可用。
这样触发频率变低，自己服务器性能损耗少。也能保证freenom官网请求量减少。第一个是为了减少自己号的异常行为，后面两个倒是没什么影响。不过毕竟都在用这个项目，一个人请求少一堆人请求就多了，freenom已经不能新注册，大家还是温柔一点吧。如果请求太多也有可能进行批量封禁，那也不好。

**Comment by luolongfei** [comment]
感谢分享。目前重试间隔时间是不固定的，最少20秒，同时会根据次数递增重试间隔。
- 下个版本可以考虑把最小间隔时间做成配置
- 另外 cookie 目前没有持久化，持久化是个好的提议
- 脚本本身占用资源几乎可以忽略不计
- 旧版成功率高可能跟服务器 ip 有关？

**Comment by luolongfei** [comment]
另外有个悲伤的消息，freenom 可能在不久将来失去域名注册资质，目前还不确定

**Comment by superen7527** [comment]
我看了一下历史通知，我旧版好像是默认配置，用的每天8:56，那个时候不太会设置cron写错了。然后最近只有两天是这个点提示登录失败其他都是直接成功。这样比较不怕检测机器行为毕竟一直有验证码还在不输入重新试太明显了。而我这个旧版居然可以共存通知，说明两个ip都互相登录挤下去还能登录成功，一天登录不了不管他过两天就能登录了。应该是间隔越长越容易触发没有验证码。(之前一直奇怪为什么重试能登录，看了日志行为还以为可以钻登录频繁的空子，现在想想应该是先登录失败然后间隔足够长就有可能不出验证码)现在的最少间隔20秒但是在前面几次没有递增，其实间隔太短就完全没有必要重试了徒增特征。

我知道一个多少请求确实没有多少损耗，只是有点话唠想总结到一起。

另外原来没有记录cookie机制吗，很建议加上。不过同时说明旧版登录完全每一次都是重新登录，那隔一天登录一次的成功率确实高的吓人。

也不用改成自定义配置，其实知道这种原理后，再加上主观避免机器行为，你已经可以写死到内部，比如根据设置的cron，提前几个小时每隔两小时左右重新试类似这样的提前拿cookie。因为我看日志登录成功也都是后面一百多次的时候，以前以为前面的一百多次失败奠定了后面的成功，现在可以得出结论和前面的一百多次没关系，只需要隔这能成功的时间段即可。(或者你可以脚本里观察一下每次成功都是间隔上次或者第一次多久 应该能得出一个大概的时间范围)


ip应该不是问题，因为我以前就是这个ip跑的登录，不能用发现要验证码给他停了，ip估计不是什么白名单。

freenom不开放新注册，不过和tk深度合作，无论如何tk都应该能继续续费，甚至以后会重新开放注册。而且这个项目是续费，还是有用的。

不要悲伤，现在都是小道消息，官方没发通知都不可信。不一定是悲伤的消息。继续等说不定就开放了。

**Comment by luolongfei** [comment]
之前重试刚出来的时候，大概10次以内就能成功，所以前期会脚本会一直尝试。

目前看起来 freenom 没有做什么很高级的检测，依赖 aws 的一个人机验证服务，失败的请求它都不一定有记录

下个版本会加上面提到的内容。

**Comment by superen7527** [comment]
哦，原来是这样 那就双重保留吧。我加了这段话可能没提示你看看。

>(或者你可以脚本里观察一下每次成功都是间隔上次或者第一次多久 应该能得出一个大概的时间范围)

**Comment by luolongfei** [comment]
这个时间间隔很随机，而且而不太可能确定，aws 的验证机制随时可能变化，所以尝试确定时间范围不是很有意义。

**Comment by superen7527** [comment]
> 这个时间间隔很随机，而且而不太可能确定，aws 的验证机制随时可能变化，所以尝试确定时间范围不是很有意义。

好的，那就根据你的想法吧 我只是把发现说了出来。只是建议，可能考虑不周到，最后还是根据你的来就好。

另外以前提过一个issue，想让超链接到修改解析的地方。不过现在微信还是会有限制字数，而现在的域名超链接是跳转到域名网站，而不一定域名都会有网站而且大部分都用来中转，所以还有个建议：
域名超链接可以换一个地方指向，或者做成配置用户自定义前缀链接，比如freenom/xxx/就是到这个域名的管理页。等等

或者直接不指向链接，这样微信等限制字数的地方可以显示完全，或者根据字数，分段发送。

**Comment by luolongfei** [comment]
域名链接最早想的是可以从邮件里点过去看看这个域名指向什么站点，而不是为了管理这个域名。

分段发送的同时要保证正确拼接链接是个很麻烦的事情，因为微信我记得是根据字节长度来限制送信长度的，所以这个想法的优先级很低。

**Comment by superen7527** [comment]
> 分段发送的同时要保证正确拼接链接是个很麻烦的事情，因为微信我记得是根据字节长度来限制送信长度的，所以这个想法的优先级很低。

不能直接计算总字节数然后发送吗？我不太了解这个，只记得有方法可以统计utf8的字节长度。如果比较麻烦那就算了吧。没事。

**Comment by superen7527** [comment]
好像免费域名解析全部被停止了。。可惜了，用不了了。

**Comment by superen7527** [comment]
昨天用cf的workerapi，国外访问不了，境内还可以，当时感觉怪怪的。今天全挂了，网站也进不去了。才突然明白freenom应该没了 马上过来看看。可惜了。
