### ISSUE TITLE
feature_request 续期任务可以调整周期吗？希望可以一周运行一次。

### ISSUE THREAD

**Issue by shaufo** [luolongfei/freenom#238]
续期任务可以调整周期吗？希望可以一周运行一次或者更长时间运行一次。毕竟一年才续期一次，感觉没必要每天都运行。

**Comment by luolongfei** [comment]
可以的，在什么环境

**Comment by shaufo** [comment]
docker

**Comment by luolongfei** [comment]
docker 设置一个环境变量 RUN_AT，值是 cron 表达式

**Comment by shaufo** [comment]
![微信截图_20231208203050](https://github.com/luolongfei/freenom/assets/63514384/174a48f4-c7d4-4fb3-ae01-e84e6e9b4934)
请问这样设置是否正确？

**Comment by luolongfei** [comment]
你这个环境是否需要加双引号，而且你希望的执行频率怎样的？自己网上找个 cron 表达式生成器吧

**Comment by shaufo** [comment]
![微信截图_20231208203639](https://github.com/luolongfei/freenom/assets/63514384/f59eb064-6a23-4b47-80c5-53c7cb3dc55b)
我配置的时候变量值没有加双引号，cron表达式是从网上生成的。因为到期前14天才可以续期，我所有域名都是同一天申请的，我就设为10天执行一次，这样总不会漏掉。我看了一下日志，应该是能正常识别的。但是以防万一，还是请你帮忙看看。

**Comment by luolongfei** [comment]
你的表达式不对，你的表达式意思是每个月10号的10点10分执行一次

**Comment by luolongfei** [comment]
推荐在这里写：https://crontab.guru/

**Comment by shaufo** [comment]
![微信截图_20231208214459](https://github.com/luolongfei/freenom/assets/63514384/25b05cb5-3e4e-41a0-af72-4074f1328cfc)
![微信截图_20231208214706](https://github.com/luolongfei/freenom/assets/63514384/460624b6-9a07-42ee-bbf1-6381fe99f3d8)
看了一下，应该每10天运行一次的表达式应该是正确的。

**Comment by shaufo** [comment]
我应该明白你的意思了，你说我的这个表达式是不是只能每个月的1号，11号，21号，31号运行，不能从今天8号，18，28这样运行？

**Comment by luolongfei** [comment]
你是对的，我看错了，太久没写这玩意儿了

**Comment by luolongfei** [comment]
只要能过我的正则验证就说明写法没问题，具体频率怎么写就看你自己折腾了
