### ISSUE TITLE
这个多久会执行一次？

### ISSUE THREAD

**Issue by donald005** [luolongfei/freenom#24]
多长时间执行一次？

**Comment by luolongfei** [comment]
默认是每天执行一次，你也可以自定义 cron 表达式指定具体的执行时机。

**Comment by donald005** [comment]
我在你的freenom/.env.example里面没有看到有cron配置呢

**Comment by luolongfei** [comment]
你是用的哪种部署方式？cron 的指定并不在 .env 中。

**Comment by donald005** [comment]
用VPS是在docker-entrypoint.sh这里修改么 ？

**Comment by luolongfei** [comment]
建议你使用 docker ，可以直接通过参数指定，如果直接拉取源码部署，需要依赖 crontab，这个在文档中有写具体怎么设置 cron，具体参考文档。

**Comment by donald005** [comment]
再请教一下这个说明里的telegram bot 是给所有人发消息么 ？能否设置成只给我自己发 ？

**Comment by luolongfei** [comment]
tg bot 只会给你发消息，不会有其他人收到。
