### ISSUE TITLE
Call to a member function getValue() on null

### ISSUE THREAD

**Issue by catsimple** [luolongfei/freenom#242]
```
主人，未捕获的异常

具体的异常内容是：
Call to a member function getValue() on null
```

只有每次第一次启动容器可以执行，后面的定时都是报这个错误

**Comment by luolongfei** [comment]
收到，待调查

**Comment by luolongfei** [comment]
版本和环境是怎样的

**Comment by catsimple** [comment]
> 版本和环境是怎样的

docker部署 Linux/amd64:latest

**Comment by luolongfei** [comment]
ok

**Comment by vipnetant** [comment]
`具体的异常内容是： Call to a member function getValue() on null`
环境：群晖Docker V0.5.4
12月14日更新到V0.5.4版本，一直到12月23日都是正常的。

**Comment by luolongfei** [comment]
> `具体的异常内容是： Call to a member function getValue() on null` 环境：群晖Docker V0.5.4 12月14日更新到V0.5.4版本，一直到12月23日都是正常的。

报错那天是正好有可以续期的域名吗

**Comment by vipnetant** [comment]
> > `具体的异常内容是： Call to a member function getValue() on null` 环境：群晖Docker V0.5.4 12月14日更新到V0.5.4版本，一直到12月23日都是正常的。
> 
> 报错那天是正好有可以续期的域名吗

不是，是倒数30天。
今天是29天，就正常了。

**Comment by luolongfei** [comment]
> > > `具体的异常内容是： Call to a member function getValue() on null` 环境：群晖Docker V0.5.4 12月14日更新到V0.5.4版本，一直到12月23日都是正常的。
> > 
> > 
> > 报错那天是正好有可以续期的域名吗
> 
> 不是，是倒数30天。 今天是29天，就正常了。

看来这个无法百分百重现？是偶发事件对吧

**Comment by vipnetant** [comment]
> > > > `具体的异常内容是： Call to a member function getValue() on null` 环境：群晖Docker V0.5.4 12月14日更新到V0.5.4版本，一直到12月23日都是正常的。
> > > 
> > > 
> > > 报错那天是正好有可以续期的域名吗
> > 
> > 
> > 不是，是倒数30天。 今天是29天，就正常了。
> 
> 看来这个无法百分百重现？是偶发事件对吧

12月28日又出现同样问题，一星期内2次，不能算偶发，只能说无规律了。

**Comment by evan8623** [comment]
我的情况和上面的一样，环境是arm64/甲骨文的VPS，每天都续约的时间都发邮件提示Call to a member function getValue() on null
，我重启VPS和docker，首次启动没有问题，次日起肯定报错

**Comment by evan8623** [comment]
> 我的情况和上面的一样，环境是arm64/甲骨文的VPS，每天都续约的时间都发邮件提示Call to a member function getValue() on null ，我重启VPS和docker，首次启动没有问题，次日起肯定报错

log只有首次启动时续期的日志，次日起报错的日志均没有提示

**Comment by luolongfei** [comment]
重新拉取最新版本的镜像。
