### ISSUE TITLE
出错：SMTP服务器连接失败

### ISSUE THREAD

**Issue by 2899** [luolongfei/freenom#25]
**问题描述**

执行
$ cd /data/wwwroot/freenom/ && php run
该命令后可以正常提示域名到期时间，但邮件服务提示如下：

`出错：SMTP服务器连接失败。 https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting [{"file":"\/data\/wwwroot\/freenom\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php","line":1587,"function":"smtpSend","class":"PHPMailer\\PHPMailer\\PHPMailer","type":"->","args":["Date: Sun, 26 Apr 2020 19:20:26 +0800\r\n`

已尝试Gmail和QQmail，均会出现此错误。

**环境信息**
 - centos7 x64
 - php 7.2
 - freenom续期脚本版本 v0.2.2

请大佬帮忙看一下是什么问题，谢谢！

**Comment by luolongfei** [comment]
@2899 根据这个简单的报错信息无法做出推断，你可以把config.php中的debug的值改为true，然后跑脚本看下输出的日志，把日志贴出来

**Comment by 2899** [comment]
日志已上传，请大佬帮忙看一下是什么问题，谢谢！
[freenom_crontab.log](https://github.com/luolongfei/freenom/files/4537149/freenom_crontab.log)

**Comment by luolongfei** [comment]
@2899 你没开debug吧，把config.php中的debug的值改为true，然后执行
cd /data/wwwroot/freenom/ && php run >> debug.log
然后上传debug.log的内容

**Comment by 2899** [comment]
debug.log已上传，请大佬过目~
[debug.log](https://github.com/luolongfei/freenom/files/4538136/debug.log)

**Comment by luolongfei** [comment]
@2899 你的问题和代码没关系，是你环境的问题，参考这里解决：https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host

**Comment by 2899** [comment]
好的，感谢大佬。
