### ISSUE TITLE
登录freenom失败，请检查账户和密码是否正确(Error code: 34520009)

### ISSUE THREAD

**Issue by sean908** [luolongfei/freenom#26]
**描述问题**
```
部署完成, 使用 php run 测试程序
发送如标题所述失败邮件

账号/密码我手动登录网站证明可用
```

**环境信息**
 - centos7 x64
 - php7.4.5
 - freenom续期脚本版本 v0.2.2

**Comment by luolongfei** [comment]
@sean908 这种情况我这边没法重现。你可以尝试下面三条：
1.确保在.env文件中账户和密码配置正确。
2.检查你的密码里是否有特殊字符，某些特殊字符，比如“"”、“\”等需要特殊处理才能正确读取。
3.配置.env文件中时，每个“=”两边不能有空格。

**Comment by sean908** [comment]
> @sean908 这种情况我这边没法重现。你可以尝试下面三条：
> 1.确保在.env文件中账户和密码配置正确。
> 2.检查你的密码里是否有特殊字符，某些特殊字符，比如“"”、“\”等需要特殊处理才能正确读取。
> 3.配置.env文件中时，每个“=”两边不能有空格。

1. 是正确的
2. 密码没有特殊字符, 纯字母数字的简单密码
3. 未留空格

我之后尝试又找了一个freenom的操作脚本
登录同样提示失败
怀疑是不是freenom对账户登录做了限制?

**Comment by luolongfei** [comment]
@sean908 不太可能，我刚刚测试能正常登录。

**Comment by luolongfei** [comment]
@sean908 我也很好奇你这个情况，因为只有密码或账户写错才会走那个分支，你用的是什么登录方式？目前只支持使用邮箱账户登录，不支持使用第三方账户登录。

**Comment by sean908** [comment]
@luolongfei 我是邮箱账号登录

**Comment by luolongfei** [comment]
@sean908 那就很奇怪了，你服务器是国内的吗

**Comment by sean908** [comment]
@luolongfei 机器在台湾机房

**Comment by luolongfei** [comment]
@sean908 你有几个账号，换个账号会出现这个情况吗

**Comment by luolongfei** [comment]
@sean908 可以加我qq593198779，等我有时间给你远程看看

**Comment by sean908** [comment]
@luolongfei 就一个, freenom 后来想再注册账号发现注册不上了, 那我先+一下吧~

**Comment by sean908** [comment]
问题解决.
<br>
**原因:**
php部署不完整.
`php.ini`缺失; 无`curl`模块
**处理方案:**
使用一键脚本重新安装.
