### ISSUE TITLE
你好，群晖docker上是luolongfei/freenom不是luolongfei/next-freenom

### ISSUE THREAD

**Issue by kittyzero520** [luolongfei/freenom#3]
你好，群晖docker上是luolongfei/freenom不是luolongfei/next-freenom，直接用双击下载luolongfei/freenom，是不是最新的吗？

**Comment by luolongfei** [comment]
你好，之前的仓库 luolongfei/freenom 由于 GitHub action 事件被封锁了，所以在 GitHub 这边源代码已经迁移到 luolongfei/next-freenom 项目下。但是 docker 版本项目的名字依然是 luolongfei/freenom。docker 版本的地址是：https://hub.docker.com/r/luolongfei/freenom 

虽然 docker 仓库和 GitHub 仓库是不同的平台，但是 docker 版本（ https://hub.docker.com/r/luolongfei/freenom ）是用 luolongfei/next-freenom 最新的代码生成的。所以直接下载的 docker 版本是最新的。

**Comment by luolongfei** [comment]
目前的做法是当 https://github.com/luolongfei/next-freenom 发布新版本的时候，会同步用最新代码更新 docker 仓库 https://hub.docker.com/r/luolongfei/freenom ，所以两边是同步的。

**Comment by kittyzero520** [comment]
你好，再咨询一个问题docker部署，docker run -d --name freenom --restart always -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom

要建立2个文件夹对吧，一个conf一个是logos，文件夹名字可以随便更换不？

**Comment by luolongfei** [comment]
不是你建立的，是程序建的，不能随便更换。

**Comment by kittyzero520** [comment]
群晖自带的docker，都是要自己建文件夹
![Uploading 群晖docker.png…]()
的

**Comment by kittyzero520** [comment]
必须手动指定挂载目录
![image](https://user-images.githubusercontent.com/33313886/135033104-df6d680a-1b9b-4331-8f3d-bce7a9fa9810.png)

**Comment by luolongfei** [comment]
群晖的 docker 是否可以通过命令执行？

**Comment by luolongfei** [comment]
如果是通过界面来运行容器的话，手动创建的目录名理论上可以随意定义（最好是纯英文无空格），并且最好是新建立的空目录，只要映射到容器内部的路径没问题就可以了。不过我一般是通过命令行执行，在命令行的话 docker 里的 -v 是会自动创建映射目录的。

**Comment by luolongfei** [comment]
总的来说就是，容器内的文件夹名是程序创建，容器外需要跟容器内产生映射关系的文件夹，可以随意自定义，不过最好是跟容器内的文件夹名一致，简明好认即可。

**Comment by Mattraks** [comment]
> 你好，之前的仓库 luolongfei/freenom 由于 GitHub action 事件被封锁了，所以在 GitHub 这边源代码已经迁移到 luolongfei/next-freenom 项目下。但是 docker 版本项目的名字依然是 luolongfei/freenom。docker 版本的地址是：https://hub.docker.com/r/luolongfei/freenom
> 
> 虽然 docker 仓库和 GitHub 仓库是不同的平台，但是 docker 版本（ https://hub.docker.com/r/luolongfei/freenom ）是用 luolongfei/next-freenom 最新的代码生成的。所以直接下载的 docker 版本是最新的。

发送邮件support@github.com删除旧仓库,然后重命名新仓库

**Comment by luolongfei** [comment]
> > 你好，之前的仓库 luolongfei/freenom 由于 GitHub action 事件被封锁了，所以在 GitHub 这边源代码已经迁移到 luolongfei/next-freenom 项目下。但是 docker 版本项目的名字依然是 luolongfei/freenom。docker 版本的地址是：https://hub.docker.com/r/luolongfei/freenom
> > 虽然 docker 仓库和 GitHub 仓库是不同的平台，但是 docker 版本（ https://hub.docker.com/r/luolongfei/freenom ）是用 luolongfei/next-freenom 最新的代码生成的。所以直接下载的 docker 版本是最新的。
> 
> 发送邮件[support@github.com](mailto:support@github.com)删除旧仓库,然后重命名新仓库

@Mattraks 还能有这种操作？我试试

**Comment by Mattraks** [comment]
> > > 你好，之前的仓库 luolongfei/freenom 由于 GitHub action 事件被封锁了，所以在 GitHub 这边源代码已经迁移到 luolongfei/next-freenom 项目下。但是 docker 版本项目的名字依然是 luolongfei/freenom。docker 版本的地址是：https://hub.docker.com/r/luolongfei/freenom
> > > 虽然 docker 仓库和 GitHub 仓库是不同的平台，但是 docker 版本（ https://hub.docker.com/r/luolongfei/freenom ）是用 luolongfei/next-freenom 最新的代码生成的。所以直接下载的 docker 版本是最新的。
> > 
> > 
> > 发送邮件[support@github.com](mailto:support@github.com)删除旧仓库,然后重命名新仓库
> 
> @Mattraks 还能有这种操作？我试试

当然你可先问问能不能恢复，不能恢复直接删除

**Comment by luolongfei** [comment]
@Mattraks 我之前有问过，无法恢复。刚刚参照你的方法请他们把旧仓库删除了，多谢提醒！

**Comment by 1-1-2** [comment]
删库改名重建马甲一条龙，百试百灵的绝招😄
