### ISSUE TITLE
故意把freenom的密码改成错的，能收到邮件提示：主人，域名数据匹配失败，未能取得域名状态信息。这可能是由于未登录或者freenom页面改版导致(Error code: 6005)。但是用正确，收不到任何提示

### ISSUE THREAD

**Issue by aff2018** [luolongfei/freenom#3]
故意把freenom的密码改成错的，能收到邮件提示：主人，域名数据匹配失败，未能取得域名状态信息。这可能是由于未登录或者freenom页面改版导致(Error code: 6005)

但是用正确的密码，测试，收不到邮件，奇怪？（帐号上有免费域名的）

**Comment by aff2018** [comment]
不过，我的域名是近期注册的，在12月份。是因为离续期太远吗？

**Comment by luolongfei** [comment]
大家收邮件最关心的是域名续期成功与否或者程序执行是否出错，并不是每次执行都发邮件，那样太打扰了，只有续期域名成功与否或者程序执行出错的情况下才会收到邮件提醒，如果不放心程序每天有没有执行，可以去log目录查看程序写的日志，把密码改错只是为了测试能否收到邮件。

**Comment by aff2018** [comment]
我看到您放的那个截图上，有提示续费成功的，也有提示域名还有多少天要续费的。因为发生测试邮件，只有密码错误时才有邮件。有点不放心

**Comment by luolongfei** [comment]
1.我截图上造的假数据，为了展示续期失败的效果。
2.提示域名还有多少天要续费的文言：即域名还不用续期，只有到期日小于14天的域名才用续费，所以后面的文言只是起个提示作用。
3.**并不是只有密码错误时才有邮件，续期成功或者失败都会发邮件给你，程序执行出错也会发邮件给你，所有的情况都考虑到了的。**如果收到续期失败的邮件，也可以第一时间去查看什么情况。不知道还有什么不放心的……==
