### ISSUE TITLE
cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)bug_report

### ISSUE THREAD

**Issue by seal0207** [luolongfei/freenom#30]
出错：cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [{"file":"\/data\/wwwroot\/freenom\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php","line":155,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[{"sink":{},"headers":[],"response":null,"request":{},"options":{"cookies":{},"synchronous":true,"timeout":34.52,"52":true,"58":true,"debug":false,"handler":{},"allow_redirects":{"max":5,"protocols":

**Comment by luolongfei** [comment]
@seal0207 与代码无关。检查你服务器的证书
