### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by mingww64** [luolongfei/freenom#30]
**描述问题**
消息正常推送，但控制台报错。
```
[2022-01-18 09:47:24] Telegram 消息发送失败：Client error: `POST https://api.telegram.org/bot<TOKEN>/sendMessage` resulted in a `400 Bad Request` response:
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '{' is reserved and must be esc (truncated...)
```
**环境信息**
 - Termux
 - PHP 8.1.0 (cli) (built: Jan 14 2022 10:39:18) (NTS)
 - freenom续期脚本版本 v0.4.4

**Comment by luolongfei** [comment]
> can't parse entities: Character '{' is reserved and must be esc
>
看错误信息是说推送的消息里有“{”字符，具体推送的是什么样的消息？
另外，在电报上能正常收到消息？

**Comment by mingww64** [comment]
是的，
```
报告，今天没有域名需要续期

我刚刚帮小主看了一下，账户  今天并没有需要续期的域名。所有域名情况如下：

 还有 41 天到期，还有 164 天到期。

更多信息可以参考 Freenom官网 <https://my.freenom.com/domains.php?a=renewals> 哦~

（如果你不想每次执行都收到推送，请将 .env 中 NOTICE_FREQ 的值设为 0，使程序只在有续期操作时才推送）
```

luolongfei ***@***.***> 于2022年1月18日周二 11:33写道：

**Comment by luolongfei** [comment]
@wmyfelix 你这里贴的内容里并没有“{”字符，能不能提供日志，看看具体的错误信息。你能百分百重现这个错误吗？我刚刚试了无法重现这个问题

**Comment by mingww64** [comment]
> @wmyfelix 你这里贴的内容里并没有“{”字符，能不能提供日志，看看具体的错误信息。你能百分百重现这个错误吗？我刚刚试了无法重现这个问题

呜呜不会php...不然会尝试自行排错。  
是使用的跟我一样的环境吗？这边百分百复现。  
使用的代码clone自本仓库。

**Comment by luolongfei** [comment]
@wmyfelix 我刚刚提交了一个版本，你拉取最新代码看看，问题是因为“{”字符，正常情况下，我定义的通知邮件里是不含有这个字符的，估计可能存在什么报错，错误信息里意外出现了这个字符，而这个字符是电报的 markdown 保留关键字，不转义就传给电报服务器的话，电报那边会返回 400 错误。现在我已经增加了这类字符的转义，理论上没问题了。

**Comment by mingww64** [comment]
@luolongfei
终端这边没问题了。以下是新出现的Telegram推送。   
```
主人，程序意外终止

可能存在错误，这边收集到的错误信息为：{"type":8192,"message":"Return type of GuzzleHttp\Cookie\CookieJar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice","file":"/data/data/com.termux/files/home/freenom/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php","line":225}
```

**Comment by luolongfei** [comment]
@wmyfelix 跟我预想的一样，是第三方库抛出了含有“{”字符的错误。看起来是 GuzzleHttp 库还没有兼容 php8.1。

下面是推荐的做法：
- 建议你不要直接拉取代码部署，或者 php 暂时使用低于 php8 的版本
- 推荐的部署方式是通过 docker，就几行命令，而且可以保证是最合适的环境


如果一定要在现行环境部署，请尝试在 run 文件所在目录，执行：
$ curl -sS https://getcomposer.org/installer | php
$ mv composer.phar /usr/local/bin/composer
安装 composer，然后执行：
$ composer update
这样会将所有的依赖库更新到最新版本，最新版本有可能已经兼容了 php8.1

具体的原因还需要在特定环境调查。

**Comment by mingww64** [comment]
@luolongfei 
最新版本不再报错。
```
$ cat composer.json
"guzzlehttp/guzzle": "^7.4",
```

**Comment by luolongfei** [comment]
@wmyfelix 好！我会在近期更新
