### ISSUE TITLE
请问怎么设置指定续签的时间

### ISSUE THREAD

**Issue by usjinbao** [luolongfei/freenom#31]
续签之后发现只续签了好像是60天，怎么设置一次签的时间更久一些

**Comment by luolongfei** [comment]
默认每次续签应该都是一年，除非你在注册这个域名的时候，指定的续期周期是 2 month，这个天数限制是受 freenom 控制的，所以最好在注册域名的时候，就指定续期周期为一年，否则后期无法在程序中定义续期周期。
