### ISSUE TITLE
Curl 错误

### ISSUE THREAD

**Issue by NuSYiXue** [luolongfei/freenom#31]
**描述问题**
运行后出现错误
能收到老版发出的报错邮件    
最新版无法收到报错邮件

**截图&日志**
-老版报错邮件：
主人
呜哇哇哇~程序执行出错啦~

具体是在/data/www/freenom.feifei.ooo/old/index.php文件的186行，抛出了一个异常。异常的内容是Curl 错误 - 登录FREENOM - 60 - Peer certificate cannot be authenticated with given CA certificates: SSL certificate problem: certificate has expired(Error code: 6001)，快去看看吧。

-新版log
出错：cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)****************************

**环境信息**
 - Debian 8 x64
 - php7.2
 - freenom新老版本都报错

劳烦老哥帮忙看下，感谢

**Comment by Andreyzxy** [comment]
我也有這個錯誤

**Comment by Andreyzxy** [comment]
log
出错：cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by luolongfei** [comment]
@NuSYiXue @Andreyzxy curl60错误一般是因为服务器上默认的证书文件过期或者服务器不认识目标网站的证书颁发者（本地没有目标网站的证书颁发者信息），而项目中每次请求都会严格验证SSL证书（含颁发者）的有效性。验证不通过则会出现curl error 60。

解决办法很简单，更新服务器本地证书为最新版本（证书颁发者信息最全：https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt）

或者等会我发布一个不严格验证证书的版本，等我提交后你们拉取最新代码即可，稍等

**Comment by luolongfei** [comment]
@NuSYiXue @Andreyzxy 两位请拉取最新代码试试，看看问题是否解决

**Comment by Andreyzxy** [comment]
@luolongfei 問題已經解決，多謝老哥

**Comment by luolongfei** [comment]
@Andreyzxy 不客气，举手之劳

**Comment by NuSYiXue** [comment]
@luolongfei  感谢老哥，活过来了
