### ISSUE TITLE
建议三方邮箱这边也写个示例。像MAIL_ENCRYPTION都能填什么这种

### ISSUE THREAD

**Issue by Eastegg** [luolongfei/freenom#33]
建议三方邮箱这边也写个示例。像MAIL_ENCRYPTION都能填什么这种

**Comment by Eastegg** [comment]
已解决，设置了三方的端口、地址（域名）、加密方式

MAIL_ENCRYPTION='ssl'
这里纯属蒙的啊，建议三方邮箱这边也写个示例。像MAIL_ENCRYPTION都能填什么这种

**Comment by Eastegg** [comment]
> 已解决

**Comment by luolongfei** [comment]
@Eastegg 可以的，我会尽快完善文档
