### ISSUE TITLE
腾讯云函数部署无法进行smtp（Gmail）送信

### ISSUE THREAD

**Issue by Muska-Ami** [luolongfei/freenom#35]
**描述问题**
```
无法进行smtp（Gmail）送信。使用腾讯云函数部署。
已手动测试，账户和密码均无误。
```

**重现步骤**
```
腾讯云函数中配置变量，并且 .env.example 中设置相同内容。
```

**截图&日志**
![image](https://user-images.githubusercontent.com/79651409/150910796-f10ed914-e1bb-4c35-abb4-a49feeba5768.png)

**你做了哪些尝试**
```
重新配置账户，密码。
多次测试。
启用不安全应用访问，并且已经前往[这个页面](https://accounts.google.com/b/0/DisplayUnlockCaptcha)允许登录
```

**环境信息**
 - Tencent SCF
 - php7.2
 - freenom续期脚本版本 v0.2.2

**额外的备注**
- 无

**Comment by luolongfei** [comment]
@XiaMoHuaHuo-CN 在腾讯云函数部署的时候选的是什么地区？在部署的时候，有没有勾选保留固定的外部 ip？因为 gmail 会在你每次从新 ip 登录的时候都验证账户安全，而腾讯云函数每次执行的时候，如果没有勾选固定 ip 这每次都是以新 ip 发起请求，导致 gmail 不允许登录。

**Comment by Muska-Ami** [comment]
@luolongfei 香港地区，已勾选。

**Comment by luolongfei** [comment]
另外建议开启 debug 模式，然后再执行看输出信息，目前只看到很简略的信息，可能的原因有很多种。设置环境变量 DEBUG=1 即可开启 debug 模式。

**Comment by luolongfei** [comment]
@XiaMoHuaHuo-CN 这样，你换个方式，不直接使用 gmail 邮箱和密码登录，而是使用 gmail 邮箱 + 应用密码登录，这样应该就不会触发谷歌的安全机制了。我还没更新相关文档，可以参考谷歌官方进行设置：https://support.google.com/mail/answer/185833?hl=zh-Hans

设置忘了后，使用 gmail 邮箱 + 应用密码来登录

**Comment by luolongfei** [comment]
> @XiaMoHuaHuo-CN 这样，你换个方式，不直接使用 gmail 邮箱和密码登录，而是使用 gmail 邮箱 + 应用密码登录，这样应该就不会触发谷歌的安全机制了。我还没更新相关文档，可以参考谷歌官方进行设置：https://support.google.com/mail/answer/185833?hl=zh-Hans
> 
> 设置忘了后，使用 gmail 邮箱 + 应用密码来登录

需要先开启 gmail 邮箱的两步验证，然后就可以设置应用密码了

**Comment by Muska-Ami** [comment]
@luolongfei 依然无法登录。能给一份GMail的smtp给我吗

**Comment by luolongfei** [comment]
> @luolongfei 依然无法登录。能给一份GMail的smtp给我吗

给一份 gmail 的 smtp 给你是什么意思？

**Comment by luolongfei** [comment]
@XiaMoHuaHuo-CN 使用 gmail+应用密码 也不行？

**Comment by Muska-Ami** [comment]
不行。

**Comment by luolongfei** [comment]
有开启 debug 看输出日志吗开启 debug 后，会输出具体无法登录的原因

**Comment by Muska-Ami** [comment]
意思是smtp服务器地址，端口发一份

**Comment by luolongfei** [comment]
还有可能是你当前云服务器的 ip 被谷歌风控了

**Comment by luolongfei** [comment]
$host = 'smtp.gmail.com';
            $secure = 'tls';
            $port = 587;

**Comment by luolongfei** [comment]
你自定义配置，和程序自动配置的效果是一样的

**Comment by Muska-Ami** [comment]
还有自动配置的啊草没写我还以为要自己配置

**Comment by luolongfei** [comment]
你应该看文档

**Comment by Muska-Ami** [comment]
![image](https://user-images.githubusercontent.com/79651409/150987472-ad9c1f3f-9e0d-4013-9c7c-19cd74eec875.png)

**Comment by Muska-Ami** [comment]
我邮箱核对过了啊，没错啊

**Comment by luolongfei** [comment]
gmail 说你不正确就是不正确，你核对密码没有

**Comment by luolongfei** [comment]
你启用了二次验证吧

**Comment by Muska-Ami** [comment]
开了，用的应用密码

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/150988991-7d6b8391-c370-4146-bf67-8b9eff8badec.png)
这里说的什么

**Comment by Muska-Ami** [comment]
发出来太长了
https://support.google.com/mail/answer/7126229?p=BadCredentials&visit_id=637787127145010217-3558335743&rd=2#cantsignin&zippy=%2C%E6%88%91%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E8%87%AA%E5%B7%B1%E7%9A%84%E7%94%B5%E5%AD%90%E9%82%AE%E4%BB%B6%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by luolongfei** [comment]
你按 gmail 提示的排错没有

**Comment by Muska-Ami** [comment]
排了

**Comment by luolongfei** [comment]
我刚刚测试了腾讯云函数 gmail 送信正常，无法重现你的问题，而你的问题一定是你 gmail 的应用密码或者账户不正确，或者你没有根据文档说明设置启用 gmail 的 smtp 等功能。
![image](https://user-images.githubusercontent.com/34597923/151116767-39ca5c48-3cef-46ac-b557-07570a6d0517.png)
