### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by Jio0oiJ** [luolongfei/freenom#36]
**描述问题**
```
root@NAS:/www/server/php/74/bin# php /data/wwwroot/freenom/run                 
 [2022-02-02 01:18:20] {"type":64,"message":"require(): Failed opening required '\/data\/wwwroot\/freenom\/resources\/lang\/en_US:en.php' (include_path='.:')","file":"\/data\/wwwroot\/freenom\/libs\/Lang.php","line":22}

```

**重现步骤**
```
root@NAS:/www/server/php/74/bin# php /data/wwwroot/freenom/run   
```

**截图&日志**

**你做了哪些尝试**
```
描述你发现问题后做了哪些尝试，方便我快速排除某些问题，提高沟通效率。
```

**环境信息**
 - debian 10
 - php7.4
 - freenom续期脚本版本 v0.4.4

**额外的备注**
- Add any other context about the problem here.

**Comment by luolongfei** [comment]
你的环境是 NAS？请先使用已发布的v0.4.4，暂不直接拉取最新的多语言版本。

**Comment by luolongfei** [comment]
@18271211 你使用旧版会不会有这个问题？

**Comment by Jio0oiJ** [comment]
> @18271211 你使用旧版会不会有这个问题？

旧版貌似不会，不过我用的是一年以前的版本，后来就一直没更新过

**Comment by Jio0oiJ** [comment]
> @18271211 你使用旧版会不会有这个问题？



> 你的环境是 NAS？请先使用已发布的v0.4.4，暂不直接拉取最新的多语言版本。

是nas，但就是debian buster，不是nas系统

**Comment by luolongfei** [comment]
你指的旧版是哪一个版本？

**Comment by luolongfei** [comment]
从哪个版本开始有这个问题？

**Comment by Jio0oiJ** [comment]
> 从哪个版本开始有这个问题？

找不到了，已经删了，21年头的某个版本，然后现在就直接跳到最新的了，直接git clone下来的。

**Comment by Jio0oiJ** [comment]
> > 从哪个版本开始有这个问题？
> 
> 找不到了，已经删了，21年头的某个版本，然后现在就直接跳到最新的了，直接git clone下来的。

刚试了下，用release的0.4.4没问题，git clone下来的最新代码不能用。

**Comment by luolongfei** [comment]
那先用 release 的 v0.4.4 吧，最新的源码尝试支持了多语言，在普通的 vps 上部署没发现问题，兼容性还需要调试，待调试完毕才会发布新版本

**Comment by luolongfei** [comment]
@18271211 
最新 clone 的代码，在 debian10 ，php7.4 的环境中已经能正常运行了。可以试试在你的环境里能否正常执行。
![image](https://user-images.githubusercontent.com/34597923/155837269-f67e303c-3486-43ec-a0d6-2d675b8de608.png)

**Comment by luolongfei** [comment]
我这边先关闭问题了，如果还有情况可以随时重新打开。
