### ISSUE TITLE
Action 打码处理时，把必要信息也打码了

### ISSUE THREAD

**Issue by jokin1999** [luolongfei/freenom#37]
**描述问题**
```
Action 打码处理时，把必要信息也打码了
```
**重现步骤**
```
Action 运行时
```
**截图&日志**

![image](https://user-images.githubusercontent.com/16080182/87238949-d4c4c000-c43b-11ea-8ffb-e3ec0388a015.png)

**环境信息**
 - GitHub Action
 - freenom续期脚本版本 v0.2.5

**额外的备注**
- 无

**Comment by luolongfei** [comment]
@jokin1999 当前程序中只对邮箱做了打码处理，其它地方的码是GitHub自己打上的，不受控制。
