### ISSUE TITLE
发信邮箱无法使用网易yeah.net后缀邮箱

### ISSUE THREAD

**Issue by lem0nb** [luolongfei/freenom#38]
**描述问题**
```
发信邮箱无法使用网易yeah.net后缀邮箱
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - centos7 x64
 - php7.2
 - freenom续期脚本版本 v0.2.2

**额外的备注**
- github action

**Comment by luolongfei** [comment]
@lem0nb 发信邮箱用163或者qq邮箱吧，其它邮箱没时间去对应

**Comment by lem0nb** [comment]
@luolongfei 好的
