### ISSUE TITLE
在 Github Action 上运行时密码中特殊字符处理出错

### ISSUE THREAD

**Issue by lyc8503** [luolongfei/freenom#39]
**描述问题**

在 Github Action 上运行时使用了 Lastpass 生成的含有特殊字符的密码, 程序报密码错误, 但实际上密码是对的.

**重现步骤**

将 Freenom 密码改成包含特殊符号的(比如 $%\/& 之类的), 在 VPS 上正常登陆, 但在 Github Action 上运行提示密码错误.

**截图&日志**

```
主人
呜哇哇哇~程序执行出错啦~

账户：[REMOVED]
异常原因：
具体是在/home/runner/work/freenom/freenom/app/Console/FreeNom.php文件的第144行，抛出了一个异常。异常的内容是登录 freenom 失败，请检查账户和密码是否正确(Error code: 34520009)，快去看看吧。
```

**环境信息**
 - Github Action

**Comment by lyc8503** [comment]
应该是 Workflow 里的那个 sh 脚本执行 sed 时未转义导致的.

**Comment by luolongfei** [comment]
@lyc8503 试试在“$%/&”之类的特殊字符前面加上“\”呢，shell命令我不太熟悉，你要是知道怎么在命令行自动转义字符，欢迎提 pull requests。

**Comment by lyc8503** [comment]
> @lyc8503 试试在“$%/&”之类的特殊字符前面加上“\”呢，shell命令我不太熟悉，你要是知道怎么在命令行自动转义字符，欢迎提 pull requests。

手动转义是可以的, 但是要完全分清楚哪些是需要转义的字符就有些困难... 我也不会自动转义, 等别人提 PR 或者现在 Readme 中对此做一个提示说明?

**Comment by luolongfei** [comment]
@lyc8503 已经在变量表格的备注里加上了说明。想了想，在 GitHub actions 环境下， shell 命令行理论上没法做到自动加上反斜线转义，因为输入的字符你必须得先经过命令行，才能继续进一步处理，而经过命令行时没转义的字符就直接被解析了，来不及进一步处理。不过应该可以比较曲折的处理，比如把所有变量先通过一定格式存入一个文件，在想办法生成需要的命令，但是那样比较麻烦，还是手动加反斜线比较简单。

需要转义的字符可以简单认为：除了字母和数字外的所有字符，都加上”\“。

**Comment by lyc8503** [comment]
好像在命令行中实现自动转义的确比较复杂... 暂时在 Readme 中说明应该就可以了.
以后我还是换一个简单的密码吧.  :(
(很多网站或软件处理 Lastpass 生成带特殊符号的密码都会出 Bug, 我已经被坑出经验了.)
