### ISSUE TITLE
Call to undefined function GuzzleHttp\\_idn_uri_convert()

### ISSUE THREAD

**Issue by KenBillionsYuan** [luolongfei/freenom#39]
最近几天在执行函数的时候遇到了这个错误，以往并没有这个问题
平台：阿里云函数

错误类型：UnhandledInvocationError
返回结果
`{"errorMessage":"Call to undefined function GuzzleHttp\\_idn_uri_convert()","errorType":"Error","stackTrace":{"file":"\/code\/vendor\/guzzlehttp\/guzzle\/src\/Client.php","line":220,"traceString":""}}`
日志输出
```
FunctionCompute php7.2 runtime inited.
FC Invoke Start RequestId: 7ba666f6-39ec-4caf-ab42-d5ab9df35cc6
2022-02-04T07:35:03Z 7ba666f6-39ec-4caf-ab42-d5ab9df35cc6 [INFO] 开始执行阿里云函数
FC Invoke End RequestId: 7ba666f6-39ec-4caf-ab42-d5ab9df35cc6
array (
  'errorMessage' => 'Call to undefined function GuzzleHttp\\_idn_uri_convert()',
  'errorType' => 'Error',
  'stackTrace' => 
  array (
    'file' => '/code/vendor/guzzlehttp/guzzle/src/Client.php',
    'line' => 220,
    'traceString' => '',
  ),
)
```

**Comment by luolongfei** [comment]
哪个版本？

**Comment by luolongfei** [comment]
最近几天突然出现这个问题？有没有做什么操作？

**Comment by KenBillionsYuan** [comment]
0.44
没有啊，就是放在那里不管的

**Comment by luolongfei** [comment]
每天执行都会出现这个情况吗？先继续观察一下。我空了看一下

**Comment by KenBillionsYuan** [comment]
看了一下，应该是从1.26号开始的，之后就一直失败了

**Comment by luolongfei** [comment]
想确定一下，你是否用的这个版本：https://github.com/luolongfei/freenom/releases/download/v0.4.4/freenom_scf.zip

我刚刚测试了之前部署的v0.4.4，并没有出现你这里的问题，然后重新部署了一遍也没有出现问题。
- 你可以尝试把旧的云函数内容全部删除，然后重新部署一遍，看看是否还有问题？
- 你之前拿到代码后是否执行过 composer 相关命令？
- 你部署的时候，启用的是哪种送信功能？


如果重新部署后问题依旧，请详细描述你的部署流程，选择的环境配置等信息。

**Comment by luolongfei** [comment]
@KenBillionsYuan

**Comment by KenBillionsYuan** [comment]
重新部署之后就可以了
