### ISSUE TITLE
腾讯云函数添加后测试失败

### ISSUE THREAD

**Issue by 9bo** [luolongfei/freenom#4]
返回结果

Text
{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds","requestId":"179f949c-648a-4746-b828-edf350886988","statusCode":433}

执行日志

UTF-8
START RequestId: 179f949c-648a-4746-b828-edf350886988

Event RequestId: 179f949c-648a-4746-b828-edf350886988

[2021-09-27 18:31:41] 当前程序版本 v0.3_scf 

END RequestId: 179f949c-648a-4746-b828-edf350886988

Report RequestId: 179f949c-648a-4746-b828-edf350886988 Duration:3000ms Memory:128MB MemUsage:13.7305MB

**Comment by luolongfei** [comment]
云函数部署在哪个地区？发信邮箱有没有用 gmail？做了哪些尝试？

**Comment by 9bo** [comment]
![1](https://user-images.githubusercontent.com/90546443/135021547-8cf9d1d1-29b1-4fb1-8351-674ab54c25b0.jpg)
![2](https://user-images.githubusercontent.com/90546443/135021558-8fd163fe-b533-4965-8acf-20157b013db4.jpg)
![3](https://user-images.githubusercontent.com/90546443/135021570-a182094f-66a9-46da-84e7-ad043fc1b0a8.jpg)

**Comment by 9bo** [comment]
# 是否启用邮件推送功能 true：启用 false：不启用 Whether to enable email push features true: enabled false: not enabled
MAIL_ENABLE=false

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/135024937-783a0122-8936-444c-ab58-9506c71c9f92.png)
一看你就没按文档中说的来。

**Comment by luolongfei** [comment]
https://github.com/luolongfei/next-freenom/blob/main/resources/screenshot/scf.png

**Comment by 9bo** [comment]
是我的问题 新版本有个初始化超时时间和执行超时时间 搞混淆了 图片你也可以更新一下新版本的设置步骤了
