### ISSUE TITLE
bug_report出错：登录 freenom 出错。错误信息：cURL error 6

### ISSUE THREAD

**Issue by yeaman2020** [luolongfei/freenom#40]
**描述问题**
```
[2022-02-06 22:50:51] 当前程序版本 v0.4.4 
[2022-02-06 22:50:51] 共发现 1 个 freenom 账户，处理中 
[2022-02-06 22:50:56] 出错：登录 freenom 出错。错误信息：cURL error 6: Could not resolve host: my.freenom.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)(Error code: 34520002) 
[Info] 已自动指定执行时间，续期任务将在北京时间每天 「17:32」 执行
[Info] 在没有手动指定 RUN_AT 环境变量的情况下，每次重启容器，程序都会重新在 06 ~ 23 点全时段中自动随机指定一个执行时间，目的是防止很多人在同一个时间点执行任务导致 Freenom 无法稳定提供服务
[Info] 计划任务：32 17 * * * php /app/run > /app/logs/freenom_cron.log 2>&1

```

**重现步骤**
```
重启 docker （非重启容器）后还是出现现这种情况，
```

**截图&日志**

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-7bfeb394-1a3a-4e53-9a65-80e040a2be64/1895dc6f-9fdd-433a-b92c-0f7480c94db6.png)

**环境信息**
 - centos7 x64
 - php7.2
 - freenom续期脚本版本 v0.2.2

**Comment by yeaman2020** [comment]
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-7bfeb394-1a3a-4e53-9a65-80e040a2be64/03318bdf-ca1d-44fb-a6d6-adf5115d5b81.png)

**Comment by yeaman2020** [comment]
修改dns也不行

**Comment by luolongfei** [comment]
80.80.80.80是什么厂商提供的 DNS？改成8.8.8.8和1.1.1.1呢

**Comment by luolongfei** [comment]
你的机器是什么？vps？NAS？从你的机器上能否访问外网？

**Comment by luolongfei** [comment]
你用的 docker 镜像是哪个？

**Comment by luolongfei** [comment]
参考此处解决 https://github.com/luolongfei/freenom/issues/87
