### ISSUE TITLE
SMTP 错误：登录失败。，快去看看吧

### ISSUE THREAD

**Issue by xiaomustudent** [luolongfei/freenom#41]
具体是在\/home\/runner\/work\/freenom\/freenom\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php文件的第2024行，抛出了一个异常。异常的内容是SMTP 错误：登录失败。，快去看看吧

老哥 这是什么意思

**Comment by luolongfei** [comment]
@xiaomustudent 这个有更详细的报错信息吧？登录失败有几种情况：
1、你发信邮箱账户或密码填写错误
2、你用的谷歌邮箱
如果是第2种，文档里说了，谷歌邮箱会限制这种登录方式，换成163邮箱就行了

**Comment by xiaomustudent** [comment]
好的 我去试试 谢谢了
