### ISSUE TITLE
配置好env，执行后出现问题，用的最新docker镜像

### ISSUE THREAD

**Issue by yeyinghai** [luolongfei/freenom#41]
大佬您好，出现这个问题，期待您的回答。
具体是在/app/app/Console/FreeNom.php文件的第195行，抛出了一个异常。异常的内容是获取域名状态页面出错，可能是未登录或者登录失效，请重试。(Error code: 34520009)，快去看看吧。
![image](https://user-images.githubusercontent.com/15318670/153592827-97c7119f-5bec-4df8-96f8-140a3f5dca49.png)

**Comment by luolongfei** [comment]
错误 34520009 获取域名状态页面后未能匹配到登录信息，可能的原因是登录的 cookie 失效，也可能是因为网络问题加载域名信息页面超时出错导致未能匹配到域名信息和登录信息。尝试重启 freenom 容器，问题是否还存在？

**Comment by NaiHeKK** [comment]
> 大佬您好，出现这个问题，期待您的回答。 具体是在/app/app/Console/FreeNom.php文件的第195行，抛出了一个异常。异常的内容是获取域名状态页面出错，可能是未登录或者登录失效，请重试。(Error code: 34520009)，快去看看吧。 ![image](https://user-images.githubusercontent.com/15318670/153592827-97c7119f-5bec-4df8-96f8-140a3f5dca49.png)

我这同样的问题，通过修改密码解决了。修改之前我只能通过edge登录不能通过chrome登录。

**Comment by luolongfei** [comment]
> 我这同样的问题，通过修改密码解决了。修改之前我只能通过edge登录不能通过chrome登录。

还有这种问题？
