### ISSUE TITLE
用了几天出错了

### ISSUE THREAD

**Issue by hzys** [luolongfei/freenom#42]
**描述问题**
运行提示出错：Server error: `POST https://my.freenom.com/dologin.php` resulted in a `5***3 Service Unavailable: Back-end server is at capacity` response ，请问如何解决呢？手动访问那个网址是403
**重现步骤**
之前用了几天好好的，今天突然来了邮件。
具体是在/home/runner/work/freenom/freenom/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php文件的第113行，抛出了一个异常。异常的内容是Server error: `POST https://my.freenom.com/dologin.php` resulted in a `503 Service Unavailable: Back-end server is at capacity` response
**环境信息**
 - freenom续期脚本版本

**Comment by jyeric** [comment]
错误报告：
```
主人，出错了。具体是在/home/runner/work/freenom/freenom/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php文件的第113行，抛出了一个异常。异常的内容是Server error: `POST https://my.freenom.com/dologin.php` resulted in a `503 Service Unavailable: Back-end server is at capacity` response，快去看看吧。（账户：xxxxxxxxxxx）
```


同样出现本错误

**Comment by RouRouX** [comment]
因为大家都集中在10点上去自动续期，freenom服务器受不了了，建议自己修改执行时间，避免集中访问

**Comment by jyeric** [comment]
> 因为大家都集中在10点上去自动续期，freenom服务器受不了了，建议自己修改执行时间，避免集中访问

啊这，这个脚本已经厉害到能把freenom服务器搞瘫了？

**Comment by RouRouX** [comment]
> > 因为大家都集中在10点上去自动续期，freenom服务器受不了了，建议自己修改执行时间，避免集中访问
> 
> 啊这，这个脚本已经厉害到能把freenom服务器搞瘫了？

看上去是这样的，CC攻击结果就是报503，服务器资源占满了。

**Comment by RouRouX** [comment]
[脚本参考位置](https://github.com/luolongfei/freenom/blob/d729390591b2af31ac70050ee65ece31676c7c4e/.github/workflows/run.yml#L22)
修改自己fork仓库里面的actions脚本
`- cron: 00 02 * * *`
数字00是分钟数（00-59），数字02个是小时设置（00-23）

**Comment by jokin1999** [comment]
看起来不像是脚本导致的，freenom到现在还是瘫痪的

**Comment by hzys** [comment]
> [脚本参考位置](https://github.com/luolongfei/freenom/blob/d729390591b2af31ac70050ee65ece31676c7c4e/.github/workflows/run.yml#L22)
> 修改自己fork仓库里面的actions脚本
> `- cron: 00 02 * * *`
> 数字00是分钟数（00-59），数字02个是小时设置（00-23）

应该不是这个原因，手动执行同样无效

**Comment by jyeric** [comment]
> 看起来不像是脚本导致的，freenom到现在还是瘫痪的

应该是freenom的问题 换个时间应该有用

上午的时候我手动执行脚本的时候提示成功了

**Comment by luolongfei** [comment]
@hzys @jokin1999 @jyeric 这个应该是 freenom 的服务器抽风导致的，至于什么原因让它服务器抽风无从知晓，脚本无法登录的时候人工去网页上也无法登录。等 freenom 修复就可以了。

**Comment by hzys** [comment]
> @hzys @jokin1999 @jyeric 这个应该是 freenom 的服务器抽风导致的，至于什么原因让它服务器抽风无从知晓，脚本无法登录的时候人工去网页上也无法登录。等 freenom 修复就可以了。

嗯嗯，现在已经正常了，顺带把时间改了下，错峰运行
