### ISSUE TITLE
添加支持Cloudflare Workers部署

### ISSUE THREAD

**Issue by noctiro** [luolongfei/freenom#42]
**Is your feature request related to a problem? Please describe.**
添加一个部署方式多一种选择（主要是更方便点）

**Describe the solution you'd like**
添加支持Cloudflare Workers部署

**Comment by luolongfei** [comment]
docker 是目前最方便的，新的部署方式欢迎提 PR

**Comment by superen7527** [comment]
> docker 是目前最方便的，新的部署方式欢迎提 PR

也建议出一个Cloudflare Workers部署  服务器有时候没续费 。

自己弄不来 如果可以的话十分感谢

**Comment by luolongfei** [comment]
cf 不支持 php

**Comment by xxj7527** [comment]
>
