### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by evafza** [luolongfei/freenom#43]
**描述问题**
```
A clear and concise description of what the bug is.
```
我是使用TG通知的，设置了不使用email通知，早上10点收到如下TG信息：

主人，出错了。具体是在/home/runner/work/freenom/freenom/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php文件的第200行，抛出了一个异常。异常的内容是cURL error 28: Operation timed out after 34522 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)，快去看看吧。（账户：XXXXX）

**重现步骤**
```
我是使用fork仓库，然后按照作者的步骤进行设置的，没有在VPS上操作。
```

**Comment by jokin1999** [comment]
应该是今天freenom的问题，可以看看 #42 的情况。

**Comment by hzys** [comment]
> 应该是今天freenom的问题，可以看看[＃42](https://github.com/luolongfei/freenom/issues/42)的情况。

现在手动执行同样无效

**Comment by jokin1999** [comment]
freenom还没恢复……程序怎么可能生效

**Comment by hzys** [comment]
> freenom还没恢复……程序怎么可能生效

那应该是昨天就出问题了吧

**Comment by luolongfei** [comment]
@evafza 这个报错是请求 freenom 超时了，是 freenom 的服务器抽风导致的。等 freenom 官方修复了就正常了。

**Comment by zynowhere** [comment]
同样的文件第200行
异常为：cURL error 7: Failed to connect to 2001::1f0d:4329: Network is unreachable (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)
是我的网络问题么

**Comment by luolongfei** [comment]
> 同样的文件第200行
> 异常为：cURL error 7: Failed to connect to 2001::1f0d:4329: Network is unreachable (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
> 是我的网络问题么
> 我实在centos 7 拉取源码部署的

你网络问题
