### ISSUE TITLE
腾讯云函数执行出错

### ISSUE THREAD

**Issue by Salomens** [luolongfei/freenom#47]
**描述问题**
```
部署完后
END RequestId: 7c31cb0e-42da-4450-b16b-5aaca63b7a84
Report RequestId: 7c31cb0e-42da-4450-b16b-5aaca63b7a84 Duration:3000ms Memory:512MB MemUsage:13.6208MB
```

**重现步骤**
```
点测试后出现以下
```

**截图&日志**
![Uploading image.png…]()

**你做了哪些尝试**
```
描述你发现问题后做了哪些尝试，方便我快速排除某些问题，提高沟通效率。
```

**环境信息**
 - php7.2
 - 最新版本

**额外的备注**
- Add any other context about the problem here.

**Comment by Salomens** [comment]
![image](https://user-images.githubusercontent.com/64776123/155126158-55b096cc-7652-4b9e-b5ad-a67cd99bc92d.png)

**Comment by luolongfei** [comment]
@Salomens 重新创建函数，记得修改执行时间，默认执行时间太短只有3秒。根据我文档中图片里的设置来。
