### ISSUE TITLE
频繁的用不同IP检测域名是否要续费Freenom会触发它的人机身份验证吗

### ISSUE THREAD

**Issue by wanghurui** [luolongfei/freenom#47]
RT

**Comment by luolongfei** [comment]
@wanghurui 每天一次的频率不算频繁，另外就目前来看freenom几乎没什么人机检测机制。使用脚本登录和真人手工登录几乎没有什么差别，很难检测，除非加上验证码，但是那样的话真人每次登录也得输入验证码，用户体检会很差。

**Comment by ldxw** [comment]
我现在运行后显示 `出错：登录` freenom 失败，请检查账户和密码是否正确(Error code: 3452***9) `
改完密码后就可以登录，然后在用这个程序运行就又会出现以上问题，然后本机登录就显示 `Login Details Incorrect. Please try again.`

@luolongfei

**Comment by luolongfei** [comment]
@ldxw 新问题请开新issue并详细描述问题，以及你做了哪些尝试。
