### ISSUE TITLE
[feature_request] 希望增加 Outlook 和 Office365 支持

### ISSUE THREAD

**Issue by QingxuMo** [luolongfei/freenom#49]
手上只有 Gmail 和 Outlook 邮箱，加上 Gmail 还可能会有问题，对于我这种用户很不友好啊（

**Comment by luolongfei** [comment]
@QingxuMo 已支持 outlook 邮箱，但是微软的人品不好，无论是发送到qq邮箱还是gmail邮箱，都会先出现在垃圾箱里，另外第一次使用 outlook 邮箱需要在邮箱里打开smtp功能以及验证手机代码。

**Comment by QingxuMo** [comment]
> @QingxuMo 已支持 outlook 邮箱，但是微软的人品不好，无论是发送到qq邮箱还是gmail邮箱，都会先出现在垃圾箱里，另外第一次使用 outlook 邮箱需要在邮箱里打开smtp功能以及验证手机代码。

了解，谢谢作者大大了😂
