### ISSUE TITLE
腾讯云函数上传失败，请帮忙看一下原因。

### ISSUE THREAD

**Issue by Remonli** [luolongfei/freenom#5]
上传失败，提示 "get ETag error, please add "ETag" to CORS ExposeHeader setting"

另外是否云函数设置那里配置了环境变量，文件夹里的.env,就不用配置了？

![图片](https://user-images.githubusercontent.com/9067053/136712740-f404b9ec-0a0f-47b4-9d24-b5a7ffe46247.png)

**Comment by luolongfei** [comment]
1、这个报错是腾讯的跨域配置问题，尝试换网络换浏览器或者换时间段再试。
2、是的
