### ISSUE TITLE
运行成功 但是 么有 邮件通知 咋回事  感谢回答

### ISSUE THREAD

**Issue by LoveForeverBoa** [luolongfei/freenom#50]
**描述问题**
```
按照教程来的 运行成功 但是没有邮件发送过来  
  
**截图&日志**
https://imgchr.com/i/w78og1
https://imgchr.com/i/w7GcRA


**环境信息**

**额外的备注**

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/93730567-ce04b700-fbfb-11ea-8255-282ad3f36e78.png)
@LoveForeverBoa 你应该没有完全按照教程来，默认的接受通知的邮箱你没有改，如果你是在GitHub actions上运行，需要追加一个名称为TO的秘密变量，变量的内容就是你的常用邮箱，用于接受机器人发送的通知邮件，如果你是在自己VPS上运行，就应该修改.env文件中的TO项对应的邮箱地址。截图中这个应该是你的邮箱发的吧，默认收信邮箱是我的，你需要改成你自己的。

**Comment by LoveForeverBoa** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/34597923/93730567-ce04b700-fbfb-11ea-8255-282ad3f36e78.png)
> @LoveForeverBoa 你应该没有完全按照教程来，默认的接受通知的邮箱你没有改，如果你是在GitHub actions上运行，需要追加一个名称为TO的秘密变量，变量的内容就是你的常用邮箱，用于接受机器人发送的通知邮件，如果你是在自己VPS上运行，就应该修改.env文件中的TO项对应的邮箱地址。截图中这个应该是你的邮箱发的吧，默认收信邮箱是我的，你需要改成你自己的。

谢谢你  我今天删除了 重新搞了下 可以了
