### ISSUE TITLE
Actions运行到Setting时报错，请大佬帮忙看看

### ISSUE THREAD

**Issue by phylis92857388** [luolongfei/freenom#52]
**Actions运行到Setting时报错，请大佬帮忙看看**

**根据大佬的教程简单布置，
fork项目，
添加secrets，分别为MAIL_PASSWORD，MAIL_USERNAME，MULTIPLE_ACCOUNTS和TO，其中MULTIPLE_ACCOUNTS里面的账号密码都由<>包裹，
Actions同意，
更改redeme.md为Freenom：freenom域名自动续期-感谢luolongfei大佬，
再回到Actions时Update README.md前面是个×，
点击Run it on action发现是Setting时报错**

**截图&日志**
https://pan.cngas.tk/0:/Images/freenom/freenom.png

**Comment by luolongfei** [comment]
@phylis92857388 看错误信息问题可能出在命令行参数处。你的账户密码中是否有特殊字符（除英文数字外的字符）？

**Comment by phylis92857388** [comment]
特殊字符全部用\处理了

**Comment by luolongfei** [comment]
@phylis92857388 你重新fork一份执行，别删，我看看执行结果

**Comment by luolongfei** [comment]
这个报错是shell相关错误，大概率是有关输入字符的问题

**Comment by phylis92857388** [comment]
就是密码的问题，我将密码的特殊字符全部处理掉了重新运行OK

**Comment by phylis92857388** [comment]
全部处理的意思是将密码更改为只有字母和数字，不是用\处理

**Comment by luolongfei** [comment]
是的，文档中有说在所有除字母数字外的字符前加转义字符“\”，否则shell命令行可能将字符识别为代码

**Comment by phylis92857388** [comment]
感谢大佬帮助
