### ISSUE TITLE
多账户设置问题

### ISSUE THREAD

**Issue by qwe3306** [luolongfei/freenom#53]
**描述问题**
```
# 多账户支持 Support for multiple accounts
MULTIPLE_ACCOUNTS=''
```
两个账户 类似下面这种
**123456@qq.com      
L@123456+**

**4567890@gmail.com  
L@123456.**

 - freenom续期脚本版本 v0.2.5

**额外的备注**
按照多账户设置要怎么设置
我是 这样的 ` '123456@qq.com@L\@123456+|4567890@gmail.com@L\@123456.'`

**Comment by luolongfei** [comment]
文档中有注释，必须是这个格式MULTIPLE_ACCOUNTS='<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>'

**Comment by luolongfei** [comment]
如果是在GitHub actions上执行，就设置一个秘密变量名为MULTIPLE_ACCOUNTS，值为<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>

**Comment by qwe3306** [comment]
> 如果是在GitHub actions上执行，就设置一个秘密变量名为MULTIPLE_ACCOUNTS，值为<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>

谢谢老哥。问题解决
