### ISSUE TITLE
获取域名状态页面出错

### ISSUE THREAD

**Issue by i2stay** [luolongfei/freenom#55]
主人，出错了，获取域名状态页面出错，可能是未登录或者登录失效，请重试。(Error code: 34520009)
具体是在/var/user/app/Console/FreeNom.php文件的第204行，抛出了一个异常。异常的内容是获取域名状态页面出错，可能是未登录或者登录失效，请重试。(Error code: 34520009)，快去看看吧。（账户：）

**Comment by luolongfei** [comment]
请根据模版提问。
