### ISSUE TITLE
针对 hax vps 报错 cURL error 6: Could not resolve host: my.freenom.com 的解决方案

### ISSUE THREAD

**Issue by Altria002** [luolongfei/freenom#57]
**描述问题**
执行报错

**重现步骤**
安装好docker，修改env文件后，重启docker，在输入日志
**截图&日志**
出错：登录 freenom 出错。错误信息：cURL error 6: Could not resolve host: my.freenom.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.freenom.com/dologin.php(Error code: 34520002) 
**你做了哪些尝试**
重新编辑env文件

**环境信息**
 - Ubantu 20
 - php8.0
 - freenom续期脚本版本 v0.4.5

**额外的备注**
- Add any other context about the problem here.

**Comment by luolongfei** [comment]
试试 systemctl restart docker

**Comment by Altria002** [comment]
![image](https://user-images.githubusercontent.com/53386594/157784251-e0566e4b-64c5-4165-b9c4-044c25aad9f9.png)

**Comment by Altria002** [comment]
![image](https://user-images.githubusercontent.com/53386594/157784385-55c87a85-ea49-4b34-8ac4-97073c569499.png)

**Comment by Altria002** [comment]
貌似还是不行，是要代理吗

**Comment by luolongfei** [comment]
你用的 hax 是纯 ipv6 地址，freenom 不支持 ipv6 ，建议你为 vps 添加一个 cloudflare 的 warp 代理，这样你的 vps 就有了 ipv4 地址，就可以访问了

**Comment by luolongfei** [comment]
添加 warp 代理有一键脚本

**Comment by Altria002** [comment]
已解决，多谢

**Comment by luolongfei** [comment]
不客气。

**Comment by kiss2u** [comment]
> 已解决，多谢

怎么解决的，我也是同样的问题

**Comment by Altria002** [comment]
纯ipv6的需要套warp

**Comment by sandeli** [comment]
我用的github actions 为freenom免费域名自动续期，也出现这个错误~~怎么办？啥不懂啊~~~

**Comment by luolongfei** [comment]
@sandeli github action 用于续期有封号风险，建议换成 https://github.com/luolongfei/freenom#-%E9%80%9A%E8%BF%87-Railway-%E9%83%A8%E7%BD%B2

**Comment by sandeli** [comment]
已换vps部署~感谢提醒

**Comment by wimdaw** [comment]
railway要验证卡，还支持其他平台嘛？比如说Koyeb，Render，Repl.it

**Comment by luolongfei** [comment]
@wimdaw 什么时候开始要验证卡的？我部署的时候并不用验证卡的

**Comment by wimdaw** [comment]
不清楚，我之前也不要，但是在所有项目删除后，就弹出验证卡，我的GIhub账号也不止6个月了，之前就用过railway

**Comment by luolongfei** [comment]
那先观察一段时间，看有没有更多的人遇到同样情况，我这边目前是不需要卡的

**Comment by wimdaw** [comment]
那还有其他方案嘛，免费不用服务器的？

**Comment by kitkw** [comment]
> @sandeli github action 用于续期有封号风险，建议换成 https://github.com/luolongfei/freenom#-%E9%80%9A%E8%BF%87-Railway-%E9%83%A8%E7%BD%B2

github action 早2天开始我也连不上帐号了。尝试部署到koyeb 成功显示Healthy，但没有收到邮件感觉没生效。帮忙看看感谢~
![屏幕截图 2022-07-17 060230](https://user-images.githubusercontent.com/31963066/179373510-e8c3c3ac-25c2-4eeb-9a6b-1be62f682753.png)
![屏幕截图 2022-07-17 061052](https://user-images.githubusercontent.com/31963066/179373512-0be783eb-40be-490a-98f5-3ca3262368fd.png)
![屏幕截图 2022-07-17 061136](https://user-images.githubusercontent.com/31963066/179373514-6090ffe8-94ff-4c74-92b6-d9e77b8671aa.png)
Detected 281018368 Bytes of RAM
PHP memory_limit is 128M Bytes
Starting php-fpm with 2 workers...
Starting httpd...
Application ready for connections on port 8080.

**Comment by luolongfei** [comment]
@wimdaw 参考文档

**Comment by luolongfei** [comment]
@kitkw 暂不支持 koyeb

**Comment by luolongfei** [comment]
@kitkw 暂不支持 koyeb

**Comment by luolongfei** [comment]
有任何问题请开新 issue，不要在这里提出。
