### ISSUE TITLE
通过直接拉取源码部署报错

### ISSUE THREAD

**Issue by y785201595** [luolongfei/freenom#58]
**描述问题**
通过直接拉取源码部署

**重现步骤**
```
最后一步的时候验证的时候
cd /data/wwwroot/freenom/ && php run
报错
[2022-03-12 18:56:34] {"type":2,"message":"require(\/data\/wwwroot\/freenom\/resources\/lang\/zh_cn:zh.php): Failed to open stream: No such file or directory","file":"\/data\/wwwroot\/freenom\/libs\/Lang.php","line":22}
**截图&日志**


**环境信息**
 - debian11 x64
 - php8.0
 - freenom续期脚本版本 v0.4.5

**额外的备注**
- 直接拉取源码部署

**Comment by luolongfei** [comment]
在 /data/wwwroot/freenom/ 目录下，执行 composer dump-autoload 试试

**Comment by luolongfei** [comment]
你的环境是否：
**环境信息**
 - debian11 x64
 - php8.0
 - freenom续期脚本版本 v0.4.5

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/158091698-721f8f23-db7e-42da-a549-305cf9cc254e.png)
我无法在同环境下重现你的问题，你需要给我能百分百重现的步骤，问题将被关闭，你可以随时重开。

**Comment by y785201595** [comment]
> 在 /data/wwwroot/freenom/ 目录下，执行 composer dump-autoload 试试
![微信截图_20220317131143](https://user-images.githubusercontent.com/68041856/158741715-db39358f-d7da-47c7-afd2-5dfdd8111522.png)

**Comment by y785201595** [comment]
换了 个7.4的PHP还是有问题

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/158743880-fb998345-a67c-4be1-80a1-8adba05af070.png)

你的问题报错很明确了，是因为你在用宝塔面板，它默认禁用了 putenv 方法，而代码里会用到此方法来设置环境变量。所以你一开始贴的错误就有问题。
