### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by konamichou** [luolongfei/freenom#6]
**描述问题**
```
邮件截图显示503错误，坐等freenom修复还是freenom改url了？
Server error: `POST https://my.freenom.com/dologin.php` resulted in a `503 Service Unavailable: Back-end server is at capacity` response
在https://my.freenom.com/clientarea.php页面上手动登录时OK的
```

**截图&日志**
![image](https://user-images.githubusercontent.com/11663256/136747948-70e9e4c9-0f17-4b7f-ab09-d7c79feb76d9.png)

**你做了哪些尝试**
```
找了一下登录页的源码
<form method="post" action="dologin.php" class="form-stacked">
      。。。
</form>
又好像url没变
```

**环境信息**
腾讯云函数

**额外的备注**
在此之前都是OK的，今天第一次出现

**Comment by luolongfei** [comment]
@konamichou 这个情况一定不是url 改变，如果 url 变了，该报 404。503 的话是 freenom 的服务临时不可用。

因为很多人完全按截图中的时间来设置的执行时间，可能导致很多人在同一时间点向 freenom 服务器发起请求，导致 freenom 应付不过来。所以，处置方式是建议你更换脚本的执行时间，最好是一个和大多数人的执行时间都不一样的时间点。
