### ISSUE TITLE
feature_request

### ISSUE THREAD

**Issue by lolifamily** [luolongfei/freenom#60]
希望能够添加自动登录hetrixtools的需求

**Comment by luolongfei** [comment]
hetrixtools 是什么工具？自动登录是想实现什么效果？

**Comment by lolifamily** [comment]
hetrixtools 是一个网站监控工具并可以提供免费 status page，但是如果90天不登录至dashboard账号会被永久删除

**Comment by luolongfei** [comment]
https://hetrixtools.com/auth.php

**Comment by luolongfei** [comment]
@lolifamily 简单看了下，这个站点的登录流程简单得不像话。你直接把下面这行shell里的用户名和密码改成你的，自己创建一个计划任务，任务频率每天一次就行了：
curl --location --request POST 'https://hetrixtools.com/auth.php' --header 'Accept: text/html, */*; q=0.01' --header 'X-Requested-With: XMLHttpRequest' --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' --header 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --header 'Sec-Fetch-Site: same-origin' --header 'Sec-Fetch-Mode: cors' --header 'Sec-Fetch-Dest: empty' --header 'Referer: https://hetrixtools.com/login/' --header 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,und;q=0.6' --data-urlencode 'm=1' --data-urlencode 'username=你的用户名' --data-urlencode 'password=你的密码' --data-urlencode 'remember=0'


登录成功应该会返回一段js代码，里面有欢迎balabala的...

**Comment by lolifamily** [comment]
这好像还需要进入/dashboard界面才行呢。
而且我还想进行邮件通知啊
