### ISSUE TITLE
登录 freenom 出错。错误信息：Client error: `POST https://my.freenom.com/dologin.php` resulted in a `429 Too Many Requests` response(Error code: 34520002)

### ISSUE THREAD

**Issue by GitSarp** [luolongfei/freenom#60]
**描述问题**
```
开始使用ok，这几天邮件提示“具体是在/root/freenom/app/Console/FreeNom.php文件的第131行，抛出了一个异常。异常的内容是登录 freenom 出错。错误信息：Client error: `POST https://my.freenom.com/dologin.php` resulted in a `429 Too Many Requests` response(Error code: 34520002)，快去看看吧。”
```

**重现步骤**
```
步骤一
```

**截图&日志**
<img width="551" alt="image" src="https://user-images.githubusercontent.com/14067824/158940823-a9a39582-f504-4a26-bfe7-51b93c09d7b4.png">

**环境信息**
 - centos7 x64
 - php7.0
 - freenom续期脚本版本 未知

**Comment by GitSarp** [comment]
环境信息更正：
- php7.4
- freenom续期脚本版本 v.0.4.5

**Comment by luolongfei** [comment]
你的脚本执行时间是什么时候？

**Comment by GitSarp** [comment]
> 你的脚本执行时间是什么时候？
应该是每天上午9点

**Comment by luolongfei** [comment]
把你的脚本执行时间，改为其它任何时段即可，具体原因我文档里有写过。

**Comment by GitSarp** [comment]
时间改了，看昨天的日志是成功的
