### ISSUE TITLE
最近总是报错emmm

### ISSUE THREAD

**Issue by samondlee** [luolongfei/freenom#61]
Check warning

GitHub Actions
/ Run it on action
.github#L1
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
 Check failure on line 1 in .github

@github-actionsgithub-actions
/ Run it on action
.github#L1
Process completed with exit code ***27.

**Comment by luolongfei** [comment]
你应该没有使用最新版本的代码吧？

**Comment by samondlee** [comment]
> 你应该没有使用最新版本的代码吧？

啊这 用了最新版本就好了
