### ISSUE TITLE
可以增加个变量设定检查间隔天数吗

### ISSUE THREAD

**Issue by sdwflizheng** [luolongfei/freenom#62]
大佬，可以增加个变量设定检查间隔天数吗？
接受邮箱填写的运营商邮箱，收到邮件会短信提醒，所以不想关闭邮箱提醒
但是每天1次的频率，邮件(短信)提醒太频繁了
freenom域名免费续期期限是到期前14天内，所以可以添加一个变量设定自动运行的间隔天数吗？
比如设置为每10天检测一次^_^

**Comment by sdwflizheng** [comment]
![image](https://user-images.githubusercontent.com/72728273/103448926-4d198900-4cdb-11eb-8031-12e2a2187779.png)

**Comment by wangzhankun** [comment]
请问这里修改的是哪个文件呢？
