### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by zhangsubo** [luolongfei/freenom#62]
**描述问题**

```
0.4.4 无法更新到最新版0.4.5
```

**重现步骤**

```
 2862  docker rm -f freenom
 2863  docker rmi -f luolongfei/freenom
 2864  docker run -d --name freenom --restart always -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom
 2865  docker run -d --name freenom --restart always -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom\n
 2866  docker restart freenom
 2867  docker logs freenom
```

**截图&日志**
[2022-03-19 23:19:23] 当前程序版本 v0.4.4
[2022-03-19 23:19:23] 共发现 1 个 freenom 账户，处理中
[2022-03-19 23:19:35] 当前通知频率为「仅当有续期操作时」，故本次不会推送通知
[2022-03-19 23:19:35] *********：执行成功，今次没有需要续期的域名。
[Info] 已自动指定执行时间，续期任务将在北京时间每天 「13:24」 执行
[Info] 在没有手动指定 RUN_AT 环境变量的情况下，每次重启容器，程序都会重新在 06 ~ 23 点全时段中自动随机指定一个执行时间，目的是防止很多人在同一个时间点执行任务导致 Freenom 无法稳定提供服务
[Info] 计划任务：24 13 * * * php /app/run > /app/logs/freenom_cron.log 2>&1
[2022-03-19 23:21:57] FreeNom 续期工具有新的版本可用，最新版本为 v0.4.5（https://github.com/luolongfei/freenom/releases/tag/v0.4.5）
[2022-03-19 23:22:18] 邮件发送失败：SMTP 错误：数据不被接受。
[2022-03-19 23:22:18] 当前程序版本 v0.4.4
[2022-03-19 23:22:18] 共发现 1 个 freenom 账户，处理中
[2022-03-19 23:22:26] 当前通知频率为「仅当有续期操作时」，故本次不会推送通知
[2022-03-19 23:22:26] ********：执行成功，今次没有需要续期的域名。
**你做了哪些尝试**

```
重复以上命令多次，依旧无法更新
```

**环境信息**

- 系统：  *ubuntu server 20.04*
- PHP 版本：  *（例如 php8.0）*
- 脚本版本：  *0.4.4*
- 是否 Docker：  *是，docker v20.10.8*

**额外的备注**

家庭网络环境下 nas，

**Comment by luolongfei** [comment]
在执行 docker 命令的过程中有无任何报错信息？

**Comment by zhangsubo** [comment]
没有错误，拉取成功的

**Comment by zhangsubo** [comment]
![image](https://user-images.githubusercontent.com/10377598/159279078-cb78bf97-1b87-41a4-9bff-02d796430dbf.png)

**Comment by luolongfei** [comment]
那就很奇怪了🤔看起来好像也没什么问题，这个操作流程按理该获取的最新代码才对，我先标记一下，等空了我看看能不能重现

**Comment by zhangsubo** [comment]
我知道问题了，是因为我 docker 增加了镜像，用的是这两个：

```json
"registry-mirrors": [
    "https://docker.mirrors.ustc.edu.cn/",
    "https://vgi5zicv.mirror.aliyuncs.com/"
  ]
```

换了镜像后可以用了。。。-_-||

辛苦啦

**Comment by luolongfei** [comment]
原来如此，那就是镜像网站没有及时同步最新代码。
