### ISSUE TITLE
呜哇哇哇~程序执行出错啦~

### ISSUE THREAD

**Issue by jiangbeth** [luolongfei/freenom#63]
![image](https://user-images.githubusercontent.com/8001330/159646069-da717a1e-0e42-4b47-83d5-7e1f3e541770.png)
异常原因：
具体是在/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php文件的第200行，抛出了一个异常。异常的内容是cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)，快去看看吧。

**Comment by luolongfei** [comment]
请按模板提问。
