### ISSUE TITLE
action 运行错误2

### ISSUE THREAD

**Issue by anderson-ryen** [luolongfei/freenom#66]
![Screenshot_2021-01-30-11-54-18-164_com microsoft emmx](https://user-images.githubusercontent.com/51238895/106346457-530e8400-62f2-11eb-8e72-f99aa56c3747.png)

请问一下  这个是什么情况

**Comment by luolongfei** [comment]
@anderson-ryen 你的密码中是否有特殊字符？在 github action 的配置中写配置的时候，应该在特殊字符前面加上“\”进行转义，另外在配置各种秘密变量时，内容中不要包括单引号“'”或者双引号“"”。

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/106442794-ad584200-64b6-11eb-94f1-9fc1c7a6bb7d.png)

**Comment by anderson-ryen** [comment]
感谢，密码没有特殊字符，为了省麻烦，直接重新fork一遍，估计是.env里面填错了，因为确保了函数无误。
