### ISSUE TITLE
github action从单用户改成多用户后收不到邮箱

### ISSUE THREAD

**Issue by loadingfd** [luolongfei/freenom#68]
之前是正常的，看log也是执行成功，是否是设计成只有续费时候发邮件呢？如果是那么怎么一直发邮件呢？谢谢

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/107007648-c66e3500-67cd-11eb-8ccb-a3af030f6943.png)
在 github action 中配置一个名为 NOTICE_FREQ 的秘密变量，其值改为1则每次执行都会发送邮件

续期成功才发邮件还是每次执行都发邮件，这是由你自己控制的

另外你当前fork的代码版本是多少？

**Comment by loadingfd** [comment]
是0.2.5的版本但是好像并不是最新的
