### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by makebl** [luolongfei/freenom#69]
这2天开始TG推送一直提示api错误了，以前一直好好的，是tg那边的问题吗

**Comment by makebl** [comment]
![image](https://user-images.githubusercontent.com/78850005/163241247-a710b5b5-4dbc-4c0f-b7ce-d8e5c33fea95.png)

**Comment by makebl** [comment]
![image](https://user-images.githubusercontent.com/78850005/163241740-a88ffe35-92fc-4c0e-a6a3-8e43deac558f.png)
![image](https://user-images.githubusercontent.com/78850005/163241780-1675da8e-eddc-49e3-aa22-4154953079f9.png)

**Comment by makebl** [comment]
这2天一直这样 也没找到问题

**Comment by makebl** [comment]
![image](https://user-images.githubusercontent.com/78850005/163242042-4f42800b-cead-43c2-9f94-c78d40f1666d.png)
![image](https://user-images.githubusercontent.com/78850005/163242061-6946df2d-6699-4e06-9acf-c8c53598cc27.png)

**Comment by luolongfei** [comment]
请按模版提问。
