### ISSUE TITLE
是否可以增加企业微信，或者企业微信机器人通知通知

### ISSUE THREAD

**Issue by CC342** [luolongfei/freenom#7]
是否可以增加企业微信，或者企业微信机器人通知通知

**Comment by luolongfei** [comment]
企业微信通知和server酱是计划中的功能，下一版会对通知相关功能进行重构和整合，届时会追加微信通知相关功能。

**Comment by wfniub** [comment]
老哥server酱还没退出吗！

**Comment by luolongfei** [comment]
还没时间整合

> 老哥server酱还没退出吗！

@wfniub

**Comment by luolongfei** [comment]
@wfniub v0.4.3版已经支持 server 酱和企业微信，但是不建议使用 server 酱，建议直接使用企业微信，每天送信条数限制不会像 server 酱那么狠。并且可以直接看到送信内容，不用点到 server 酱的网站里去，也不用开什么 server 酱会员，就调腾讯 api 这么简单的一件事情还要人开会员，有点过分。

**Comment by luolongfei** [comment]
@CC342 已增加企业微信送信功能。

**Comment by CC342** [comment]
> @CC342 已增加企业微信送信功能。

好的，谢谢。辛苦啦

**Comment by luolongfei** [comment]
@CC342 不客气，举手之劳。

**Comment by wfniub** [comment]
> @wfniub 1900

感谢大佬的更新！
