### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by xiaoming140** [luolongfei/freenom#70]
异常原因：
具体是在/home/runner/work/freenom/freenom/vendor/phpmailer/phpmailer/src/PHPMailer.php文件的第1876行，抛出了一个异常。异常的内容是SMTP 错误：数据不被接受。，快去看看吧。

这是怎么回事？（163的授权码是正确的，第一次的时候还可以，第二次就不行了）

**Comment by luolongfei** [comment]
打开debug模式，提供更详细的日志
