### ISSUE TITLE
Actions 频率优化建议

### ISSUE THREAD

**Issue by if1y** [luolongfei/freenom#72]
其实用不着每天执行一次，Freenom 是到期前14天可续，那么其实10天左右执行一次就好了。

怕有意外的话，6天左右执行一次也够。

这也是对 Github Actions 免费资源的一种保护，同时降低推送的干扰频率。

**Comment by sdwflizheng** [comment]
参考：https://github.com/luolongfei/freenom/issues/62

**Comment by if1y** [comment]
> 参考：#62

我知道自己修改 workflow 可以实现。
我的意思是希望作者从他的仓库去做这个修改，很多人都是 fork 完直接使用，所以会带来一系列连锁浪费。

**Comment by luolongfei** [comment]
> 同时降低推送的干扰频率
-- 推送频率是可以设置为仅在出错或者有续期操作时才触发

> 对 Github Actions 免费资源的一种保护
-- 一天一次的频率我认为并不算高，并且脚本本身几乎不消耗资源
@if1y
