### ISSUE TITLE
玩客云搭建后执行失败shuf: clock_gettime(MONOTONIC) failed

### ISSUE THREAD

**Issue by dan3577** [luolongfei/freenom#73]
执行错误截图
![image](https://user-images.githubusercontent.com/52194615/164913620-e2dce310-4b80-4ab7-aa72-686985a9e8d1.png)

**你做了哪些尝试**
重装freenom，重拉镜像，编辑.env

**环境信息**
Welcome to Debian GNU/Linux 10 (buster) with Linux 5.9.0-rc7-aml-s812 build By BugScaner Support Wifi Adapter
No end-user support: built from trunk

System load:   15%              Up time:       5 days 23:58             Local users:   2                
Memory usage:  17% of 988M      IP:            192.168.2.164
CPU temp:      36°C             Usage of /:    40% of 6.5G

**Comment by luolongfei** [comment]
我手边没有玩客云设备，没法重现你的问题。这个报错可能跟你的 docker 有关。尝试使用其它镜像看是否有相同的问题？

**Comment by rkongzy** [comment]
nanopi neo2,armbian系统docker安装也出现了同样的问题，google了半天好像和libseccomp版本有关系

**Comment by luolongfei** [comment]
@dan3577 @rkongzy 那可能是 docker 相关安全限制，试试在执行命令里加上 --security-opt seccomp=unconfined

**Comment by luolongfei** [comment]
如果有用，记得回来反馈

**Comment by dan3577** [comment]
加了--security-opt seccomp=unconfined还是一样的效果，，，如果方便的话，，可以远程试试

**Comment by dan3577** [comment]
![image](https://user-images.githubusercontent.com/52194615/165506336-6a8bafae-96c8-4564-8524-ebc1946aee64.png)
![image](https://user-images.githubusercontent.com/52194615/165506369-00f580ed-6214-4a4e-91c7-4ab57bccdf11.png)

**Comment by luolongfei** [comment]
@dan3577 参数位置不要加错，你把 --security-opt seccomp=unconfined 移到前面去，比如 —name freenom --security-opt seccomp=unconfined 注意空格

**Comment by luolongfei** [comment]
@dan3577 有没有新进展？

**Comment by rkongzy** [comment]
谢谢大佬，添加 --security-opt seccomp=unconfined  后启动成功了，一直到忙到现在才有时间测试回复，不好意思

**Comment by luolongfei** [comment]
没关系，不客气

**Comment by llss66** [comment]
创建一个空 json 数据文件 `/etc/docker/seccomp-config.json`：

```
{}
```

然后修改 `/etc/docker/daemon.json`:

```
{
  "seccomp-profile": "/etc/docker/seccomp-config.json"
}
```

重启 docker 

```bash
systemctl restart docker
```

**Comment by dan3577** [comment]
> @dan3577 有没有新进展？

感谢，已解决
