### ISSUE TITLE
60天 就会自动停止

### ISSUE THREAD

**Issue by LoveForeverBoa** [luolongfei/freenom#74]
大佬 这个怎么解决

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/107721898-c6fc5380-6d18-11eb-869a-8c390bcf2747.png)
不懂你什么意思，action上我这边已经有九个月了都没停止。

**Comment by MicePilot** [comment]
![image](https://user-images.githubusercontent.com/13869645/108295720-2522ae00-71d3-11eb-9596-824e0598e82b.png)
应该是这个邮件，进去点击 continue 应该就行了

**Comment by luolongfei** [comment]
看 GitHub 官方文档，确实会禁用60天不活跃的仓库的 workflow：https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
> Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.
> 
看说明貌似是针对所有仓库的，不过我自己的仓库已经有5个月没活跃了也没有被禁用，有些意外。
看官方文档，仓库 workflow 被禁用后有两种重新启用的方式，一是像你这样点进去手动启用，二是调用 GitHub 官方的 REST API（参考：https://docs.github.com/cn/rest/reference/actions#enable-a-workflow），调用 REST API示例：

```shell
curl \
  -X PUT \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/luolongfei/freenom/actions/workflows/42/enable
```

这属于 GitHub 官方的限制，解决方案也不是没有，就是比较繁琐。可以单独新建一个仓库 A，在A仓库中加个 workflow，这个 workflow 只做一件事，就是去启用 freenom 所在仓库的 workflow（当然可以加上检查 freenom 所在仓库的 workflow 状态的逻辑），而 freenom 所在仓库也再加个 workflow，也只做一件事，去启用 A 仓库的 workflow，它们互相启用，这样理论上就能达到永不停用的效果。

其实还是更推荐在 vps 上部署。

**Comment by MicePilot** [comment]
> 看 GitHub 官方文档，确实会禁用60天不活跃的仓库的 workflow：https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
> 
> > Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.
> 
> 看说明貌似是针对所有仓库的，不过我自己的仓库已经有5个月没活跃了也没有被禁用，有些意外。
> 看官方文档，仓库 workflow 被禁用后有两种重新启用的方式，一是像你这样点进去手动启用，二是调用 GitHub 官方的 REST API（参考：[https://docs.github.com/cn/rest/reference/actions#enable-a-workflow），调用](https://docs.github.com/cn/rest/reference/actions#enable-a-workflow%EF%BC%89%EF%BC%8C%E8%B0%83%E7%94%A8) REST API示例：
> 
> ```shell
> curl \
>   -X PUT \
>   -H "Accept: application/vnd.github.v3+json" \
>   https://api.github.com/repos/luolongfei/freenom/actions/workflows/42/enable
> ```
> 
> 这属于 GitHub 官方的限制，解决方案也不是没有，就是比较繁琐。可以单独新建一个仓库 A，在A仓库中加个 workflow，这个 workflow 只做一件事，就是去启用 freenom 所在仓库的 workflow（当然可以加上检查 freenom 所在仓库的 workflow 状态的逻辑），而 freenom 所在仓库也再加个 workflow，也只做一件事，去启用 A 仓库的 workflow，它们互相启用，这样理论上就能达到永不停用的效果。
> 
> 其实还是更推荐在 vps 上部署。

请问自动续期会检查 ip 归属吗，我之前申请域名的时候挂的 vpn，美国 ip，我腾讯云有个服务器，如果部署到国内服务器上进行续期的话，会不会有问题

**Comment by luolongfei** [comment]
@MicePilot 据我观察 freenom 是没有限制续期的 ip 的。只要你通过国内的 vps 能登录应该就没问题。

**Comment by zhzhzhy** [comment]
> 看 GitHub 官方文档，确实会禁用60天不活跃的仓库的 workflow：https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
> 
> > Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.
> 
> 看说明貌似是针对所有仓库的，不过我自己的仓库已经有5个月没活跃了也没有被禁用，有些意外。
> 看官方文档，仓库 workflow 被禁用后有两种重新启用的方式，一是像你这样点进去手动启用，二是调用 GitHub 官方的 REST API（参考：[https://docs.github.com/cn/rest/reference/actions#enable-a-workflow），调用](https://docs.github.com/cn/rest/reference/actions#enable-a-workflow%EF%BC%89%EF%BC%8C%E8%B0%83%E7%94%A8) REST API示例：
> 
> ```shell
> curl \
>   -X PUT \
>   -H "Accept: application/vnd.github.v3+json" \
>   https://api.github.com/repos/luolongfei/freenom/actions/workflows/42/enable
> ```
> 
> 这属于 GitHub 官方的限制，解决方案也不是没有，就是比较繁琐。可以单独新建一个仓库 A，在A仓库中加个 workflow，这个 workflow 只做一件事，就是去启用 freenom 所在仓库的 workflow（当然可以加上检查 freenom 所在仓库的 workflow 状态的逻辑），而 freenom 所在仓库也再加个 workflow，也只做一件事，去启用 A 仓库的 workflow，它们互相启用，这样理论上就能达到永不停用的效果。
> 
> 其实还是更推荐在 vps 上部署。

参考大佬的方法，用REST `api写了一个action,每天互相唤醒，防止60天停掉[https://github.com/zhzhzhy/Workflow-Keep-Alive](https://github.com/zhzhzhy/Workflow-Keep-Alive)

**Comment by luolongfei** [comment]
@zhzhzhy 👍
