### ISSUE TITLE
freenom域名自动续期检测报错

### ISSUE THREAD

**Issue by yikexiaoyao** [luolongfei/freenom#75]
Server error: `POST https://my.freenom.com/dologin.php` resulted in a `503 Service Unavailable: Back-end server is at capacity` response
请问大佬，我今天上午像往常一样收到域名检测邮件，但是报了这个错误，登录GitHub重新运行action，一开始报错，几秒后又显示没有问题，不知道是怎么回事，希望能帮忙看一下，非常感谢

**Comment by luolongfei** [comment]
@yikexiaoyao 这个是 freenom 服务器的问题，可以忽略，当脚本访问不了 freenom 时，你人工去也访问不了

**Comment by luolongfei** [comment]
503应该是 freenom 服务器过载了，你可以改改 yaml 文件里的定时任务的时间，错峰运行

**Comment by yikexiaoyao** [comment]
非常感谢，祝新年快乐

**Comment by luolongfei** [comment]
不客气，同乐！
