### ISSUE TITLE
运行后没有收到信息也没有续期域名

### ISSUE THREAD

**Issue by binhe-cpu** [luolongfei/freenom#76]
请问这个运行正常吗？
![image](https://user-images.githubusercontent.com/61576528/107918453-a811f180-6fa4-11eb-8a4f-f5557bc31f33.png)

**Comment by luolongfei** [comment]
默认是每次执行都会发信，除非你配置了送信频率为仅在有续期操作或报错时

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/108026845-1f5a8a80-7064-11eb-86d9-0b677d80a16b.png)
你缺少配置

**Comment by luolongfei** [comment]
你应该先阅读文档，文档里有具体的操作步骤

**Comment by binhe-cpu** [comment]
我是按说明文档设置的
![image](https://user-images.githubusercontent.com/61576528/108061852-e1755a80-7093-11eb-8471-6c82d739889c.png)

**Comment by binhe-cpu** [comment]
晚上又试了下，还是一样
![image](https://user-images.githubusercontent.com/61576528/108062001-1f727e80-7094-11eb-96c3-2bc6312e7543.png)

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/108162205-973db900-7127-11eb-94e9-28e5f7cf21fa.png)
@binhe-cpu 我注意到你修改了.env.example，并且在文件中使用了错误的注释符号“#”，你把这两行错误的注释干掉，然后再看看？

**Comment by luolongfei** [comment]
程序自动配置时是copy的这个.env.example文件的内容，这个文件内容被改错了，理论上会有问题。或者你重新fork一份再操作。

**Comment by ldxw** [comment]
> 程序自动配置时是copy的这个.env.example文件的内容，这个文件内容被改错了，理论上会有问题。或者你重新fork一份再操作。

我重新fork 在添加了  可是还是不行，还是显示没有添加密钥

**Comment by luolongfei** [comment]
@ldxw 那你倒是添加密码等相关配置啊……

**Comment by luolongfei** [comment]
@ldxw 你可以试试在vps上能不能正常跑，然后再在 github actions 上测试，因为 github actions 上没有太多的日志信息，不方便定位问题。

**Comment by luolongfei** [comment]
@ldxw 对了，你能不能截个图，给我看看是哪里显示的未添加密钥？

**Comment by ldxw** [comment]
> @ldxw 你可以试试在vps上能不能正常跑，然后再在 github actions 上测试，因为 github actions 上没有太多的日志信息，不方便定位问题。

知道什么问题了，是邮箱账号密码有特殊字符，我把邮箱密码特殊字符前面添加/字符就可以了，

**Comment by luolongfei** [comment]
@ldxw ok!

**Comment by ldxw** [comment]
> @ldxw ok!

要搞docker版本吗？

**Comment by luolongfei** [comment]
@ldxw docker版本有网友弄了，你可以翻一下在issue里

**Comment by ldxw** [comment]
> @luolongfei  好吧。。

**Comment by binhe-cpu** [comment]
谢谢大佬，就是这两个注释符号的原因，我把这个两处改掉就可以了，谢谢了！

**Comment by dayunnas** [comment]
怎么查看是否成功了，我也没有收到任何邮件

**Comment by dayunnas** [comment]
@luolongfei 
![Uploading image.png…]()

**Comment by dayunnas** [comment]
![image](https://user-images.githubusercontent.com/80449837/112922123-8593fc00-913e-11eb-878e-1606d88e037f.png)

**Comment by luolongfei** [comment]
@dayunnas 新问题开新 issues。
