### ISSUE TITLE
密码中含有%号也会报错

### ISSUE THREAD

**Issue by Remonli** [luolongfei/freenom#8]
我的freenom 密码有% , 也会报错 , 查了半天才发现是这个问题。

请更新一下以免其他人也遇到，谢谢！

**Comment by Remonli** [comment]
奇怪，另一个账号密码也有%，但是可以用。

先关了吧，抱歉。

**Comment by luolongfei** [comment]
可以说一下具体的环境和具体的报错内容，%号并不是什么关键字，理论上不会报错。

**Comment by Remonli** [comment]
腾讯云函数，问题出在哪我也不知道，原密码在网站登录正常就是脚本这边报密码错误。
改了密码之后，两边都可以正常登录了。

**Comment by luolongfei** [comment]
如果把密码改回含%的那种再次重现报错，那可能就是腾讯有什么处理。
