### ISSUE TITLE
Actions 的多账户配置

### ISSUE THREAD

**Issue by huangjackey1111** [luolongfei/freenom#83]
**描述问题**
```
Actions 的多账户配置了但是邮件没有另一个账户的信息
```
**重现步骤**
```
配置了FREENOM_USERNAME、FREENOM_PASSWORD、MULTIPLE_ACCOUNTS，但是邮件中只出现了FREENOM_USERNAME、FREENOM_PASSWORD对应的账户，MULTIPLE_ACCOUNTS里面配置的账户并没有出现。是否Actions不支持多账户呢？
```

**Comment by luolongfei** [comment]
邮件是单独发送的，多个账户不会出现在同一封邮件中。执行过程中有没报错？

**Comment by huangjackey1111** [comment]
> 邮件是单独发送的，多个账户不会出现在同一封邮件中。执行过程中有没报错？

![image](https://user-images.githubusercontent.com/42202931/109266186-aa950680-7842-11eb-9b0c-c018a1b6cdd5.png)
貌似也没有报错，只是显示了一个账户的信息

**Comment by luolongfei** [comment]
你配置的 MULTIPLE_ACCOUNTS 的格式是怎样的？

**Comment by huangjackey1111** [comment]
> 你配置的 MULTIPLE_ACCOUNTS 的格式是怎样的？

MULTIPLE_ACCOUNTS 只设置了另外一个账号密码，第一个账户是通过FREENOM_USERNAME、FREENOM_PASSWORD设置的
MULTIPLE_ACCOUNTS是这样的
aaa@bb.com@xxxxxxxxx

**Comment by luolongfei** [comment]
@huangjackey1111 你多账户的格式有问题，文档中写明的是<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>，这里的<>符号不能省略，把格式改正确就对了。

**Comment by huangjackey1111** [comment]
> @huangjackey1111 你多账户的格式有问题，文档中写明的是<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>，这里的<>符号不能省略，把格式改正确就对了。

果然是要<>，之前以为这个只是一个标识符。谢谢了！！
