### ISSUE TITLE
Actions怎么能不配置邮箱,只设置tg

### ISSUE THREAD

**Issue by insoxin** [luolongfei/freenom#84]

**Comment by luolongfei** [comment]
文档中有详细说明，可以完全自定义启用何种送信方式。

**Comment by insoxin** [comment]
> 文档中有详细说明，可以完全自定义启用何种送信方式。

不填邮箱会报错的

**Comment by luolongfei** [comment]
有个是否启用邮箱功能的参数，你配置了不启用邮箱功能的话，是不会去读邮箱配置的

**Comment by insoxin** [comment]
> 有个是否启用邮箱功能的参数，你配置了不启用邮箱功能的话，是不会去读邮箱配置的

好的好的懂了懂了

**Comment by luolongfei** [comment]
MAIL_ENABLE | 是否启用邮件推送功能 | true | 否 | true：启用false：不启用默认启用，如果设为false，不启用邮件推送功能，则上面的MAIL_USERNAME、MAIL_PASSWORD、TO变量变为非必须，可不设置
-- | -- | -- | -- | --
