### ISSUE TITLE
github actions 运行出错

### ISSUE THREAD

**Issue by huaxinCLUB** [luolongfei/freenom#87]
**描述问题**
```
Run php7.*** run
  **mphp7.*** run
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/e4994732-b8e***-44***f-9***94-f8dea9d08***ec.sh: line ***: php7.***: command not found
Error: Process completed with exit code ***27.
```
**重现步骤**
```
步骤一
```
**截图&日志**
![image](https://user-images.githubusercontent.com/57068786/109928549-8634a080-7d00-11eb-986b-3e2b594d5d57.png)

**环境信息**
forked [RouRouX/freenom](https://github.com/huaxinCLUB/freenom)

**额外的备注**
- Add any other context about the problem here.

**Comment by luolongfei** [comment]
这个 RouRouX/freenom 仓库可能不是最新的代码，最新代码 fork luolongfei/freenom，并最新的文档说明进行配置。

**Comment by huaxinCLUB** [comment]
使用luolongfei的仓库问题解决了
