### ISSUE TITLE
Github Actions ..... 沒有出現 update readme.md

### ISSUE THREAD

**Issue by rice818** [luolongfei/freenom#91]
跟著一步步設定...

但到了...

5、查看执行详情

沒有預期出現 "update readme.md"

如何解決? 謝謝

**Comment by luolongfei** [comment]
@rice818 查看执行详情的时候，并不一定是出现"update readme.md"字样，演示的截图里面，github action 那里的意思是显示由于某次 push 操作触发了脚本执行，push 操作的说明我填写的是“update readme.md”，仅此而已。而你的 action 触发是由定时器触发的：
![image](https://user-images.githubusercontent.com/34597923/114976997-84dac400-9eb9-11eb-91e0-2548ce1e6e0a.png)

整个执行过程是没问题的。具体要看是否执行成功，需要按下图这样：

![image](https://user-images.githubusercontent.com/34597923/114977163-d5522180-9eb9-11eb-9e1a-f9f43795f80b.png)

我看你的执行过程是成功了的，但是邮箱配置有问题，最后导致没有发送通知邮件：
![image](https://user-images.githubusercontent.com/34597923/114976692-fcf4ba00-9eb8-11eb-94b2-1e8bbebbcb1f.png)

你需要检查一下你的送信邮箱的设置，推荐使用163邮箱作为送信邮箱，然后用自己常用的邮箱作为收信邮箱。具体是邮箱的哪一步有问题，需要开启 debug 模式才能明了。
