### ISSUE TITLE
Actions secrets的名字

### ISSUE THREAD

**Issue by CJXCK520** [luolongfei/freenom#96]
你好作者，这个Actions secrets名字是你md里写着的FREENOM_PASSWORD吗？我参数都设置好了，运行action什么都没有

**Comment by CJXCK520** [comment]
![image](https://user-images.githubusercontent.com/74248712/116267383-f0bd0680-a7ae-11eb-9bac-3f36d4fadc72.png)
参数都设置好了，没弄tg机器人，不知道怎么回事啊？？

**Comment by luolongfei** [comment]
https://github.com/luolongfei/freenom#%E5%8F%AA%E9%9C%80%E7%AE%80%E5%8D%95-6-%E6%AD%A5

**Comment by luolongfei** [comment]
你参数是不是没设置全？应该按文档里说的，设置所有必须的变量
https://github.com/luolongfei/freenom#%E5%8F%AA%E9%9C%80%E7%AE%80%E5%8D%95-6-%E6%AD%A5
![image](https://user-images.githubusercontent.com/34597923/116383505-7ab9ad80-a849-11eb-9ba8-ab7251e25bcc.png)
上面的表格里面列举了所有必须和非必须的变量，这里的所有必须变量都需要配置

**Comment by luolongfei** [comment]
> ![image](https://user-images.githubusercontent.com/74248712/116267383-f0bd0680-a7ae-11eb-9bac-3f36d4fadc72.png)
> 参数都设置好了，没弄tg机器人，不知道怎么回事啊？？

你这里是没有触发 github action 执行。默认情况下，每天的10点左右 GitHub action 会自动执行。看了下你今天的执行情况，明显没有配置和账户相关的 Actions secrets
![image](https://user-images.githubusercontent.com/34597923/116384270-4692bc80-a84a-11eb-9586-4b624b0815d0.png)

**Comment by luolongfei** [comment]
你把文档里说的那些秘密变量都配置上应该就可以了。

**Comment by CJXCK520** [comment]
每一个变量创建一个New secret是吧作者大大

**Comment by luolongfei** [comment]
> 每一个变量创建一个New secret是吧作者大大

是的，New secret就是创建一个新的秘密变量，需要分别创建所有必须的秘密变量
![image](https://user-images.githubusercontent.com/34597923/116501232-e2700700-a8e2-11eb-8549-1a36089edafd.png)

**Comment by CJXCK520** [comment]
![image](https://user-images.githubusercontent.com/74248712/116807357-5f121800-ab65-11eb-9497-106eb78cb59e.png)
奇了个怪，作者大大，我变量填了，运行后是这个结果

**Comment by luolongfei** [comment]
@CJXCK520 你变量中是否有特殊字符？特殊字符需要用反斜线转义，比如“$”需要写为“\$”。
